-- Synonyme PUBLIC : BQUEPRV_IDCOMPTE
-- Cible      : ARTHUS.BQUEPRV_IDCOMPTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM BQUEPRV_IDCOMPTE FOR ARTHUS.BQUEPRV_IDCOMPTE;
