-- Synonyme PUBLIC : EXTPROCGS19_PROC
-- Cible      : ARTHUS.EXTPROCGS19_PROC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM EXTPROCGS19_PROC FOR ARTHUS.EXTPROCGS19_PROC;
