-- Synonyme PUBLIC : EXTPROCNO06_PROC
-- Cible      : ARTHUS.EXTPROCNO06_PROC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM EXTPROCNO06_PROC FOR ARTHUS.EXTPROCNO06_PROC;
