-- Synonyme PUBLIC : EXTPROCRB01_PROC
-- Cible      : ARTHUS.EXTPROCRB01_PROC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM EXTPROCRB01_PROC FOR ARTHUS.EXTPROCRB01_PROC;
