-- Synonyme PUBLIC : EXTPROCRS01_PROC
-- Cible      : ARTHUS.EXTPROCRS01_PROC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM EXTPROCRS01_PROC FOR ARTHUS.EXTPROCRS01_PROC;
