-- Synonyme PUBLIC : EXTPROCPV01_PROC
-- Cible      : ARTHUS.EXTPROCPV01_PROC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM EXTPROCPV01_PROC FOR ARTHUS.EXTPROCPV01_PROC;
