-- Synonyme PUBLIC : EXTPROCQG01_PROC
-- Cible      : ARTHUS.EXTPROCQG01_PROC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM EXTPROCQG01_PROC FOR ARTHUS.EXTPROCQG01_PROC;
