-- Synonyme PUBLIC : HISTO_SNTR_SANTE
-- Cible      : ARTHUS.HISTO_SNTR_SANTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_SNTR_SANTE FOR ARTHUS.HISTO_SNTR_SANTE;
