-- Synonyme PUBLIC : ID_DECLA_PRESTIJ
-- Cible      : ARTHUS.ID_DECLA_PRESTIJ
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM ID_DECLA_PRESTIJ FOR ARTHUS.ID_DECLA_PRESTIJ;
