-- Synonyme PUBLIC : ID_REMISE_PRESTIJ
-- Cible      : ARTHUS.ID_REMISE_PRESTIJ
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM ID_REMISE_PRESTIJ FOR ARTHUS.ID_REMISE_PRESTIJ;
