-- Synonyme PUBLIC : ID_STOCK_FACT_SP
-- Cible      : ARTHUS.ID_STOCK_FACT_SP
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM ID_STOCK_FACT_SP FOR ARTHUS.ID_STOCK_FACT_SP;
