-- Synonyme PUBLIC : MLOG$_ADHE_CNTRT
-- Cible      : ARTHUS.MLOG$_ADHE_CNTRT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM MLOG$_ADHE_CNTRT FOR ARTHUS.MLOG$_ADHE_CNTRT;
