-- Synonyme PUBLIC : NUMREMISE_REPORT
-- Cible      : ARTHUS.NUMREMISE_REPORT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM NUMREMISE_REPORT FOR ARTHUS.NUMREMISE_REPORT;
