-- Synonyme PUBLIC : NUMREMISE_EXTERNE
-- Cible      : ARTHUS.NUMREMISE_EXTERNE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM NUMREMISE_EXTERNE FOR ARTHUS.NUMREMISE_EXTERNE;
