-- Synonyme PUBLIC : RUPD$_ADHE_CNTRT
-- Cible      : ARTHUS.RUPD$_ADHE_CNTRT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM RUPD$_ADHE_CNTRT FOR ARTHUS.RUPD$_ADHE_CNTRT;
