-- Synonyme PUBLIC : SEQ_STOCK_ENTITE
-- Cible      : ARTHUS.SEQ_STOCK_ENTITE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SEQ_STOCK_ENTITE FOR ARTHUS.SEQ_STOCK_ENTITE;
