-- Synonyme PUBLIC : SEQ_STOCK_ENTITE_R
-- Cible      : ARTHUS.SEQ_STOCK_ENTITE_R
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SEQ_STOCK_ENTITE_R FOR ARTHUS.SEQ_STOCK_ENTITE_R;
