-- Synonyme PUBLIC : SYS_EXPORT_FULL_02
-- Cible      : ARTHUS.SYS_EXPORT_FULL_02
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SYS_EXPORT_FULL_02 FOR ARTHUS.SYS_EXPORT_FULL_02;
