-- Synonyme PUBLIC : SYS_EXPORT_FULL_01
-- Cible      : ARTHUS.SYS_EXPORT_FULL_01
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SYS_EXPORT_FULL_01 FOR ARTHUS.SYS_EXPORT_FULL_01;
