-- Synonyme PUBLIC : TMP_P_MAJ_ANO_NOEMIE
-- Cible      : ARTHUS.TMP_P_MAJ_ANO_NOEMIE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM TMP_P_MAJ_ANO_NOEMIE FOR ARTHUS.TMP_P_MAJ_ANO_NOEMIE;
