-- Synonyme PUBLIC : V_CPTA_PRESTA_SANTE
-- Cible      : ARTHUS.V_CPTA_PRESTA_SANTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM V_CPTA_PRESTA_SANTE FOR ARTHUS.V_CPTA_PRESTA_SANTE;
