-- Synonyme PUBLIC : V_DCPTCIE_PRDG_DCS
-- Cible      : ARTHUS.V_DCPTCIE_PRDG_DCS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM V_DCPTCIE_PRDG_DCS FOR ARTHUS.V_DCPTCIE_PRDG_DCS;
