CREATE TRIGGER ARTHUS."AF_INS_REPARTITION_BENE"
AFTER INSERT ON REPARTITION_BENE
FOR EACH ROW
BEGIN
INSERT INTO HISTO_DEST (IDREPARTITION, NUMBENE, USERCREA, DATECREA, TYPE_DEST, NUMBENE_DEST, DEBUT  )
 VALUES (:NEW.IDREPARTITION,:NEW.NUMBENE, f_numutil(), SYSDATE,:NEW.TYPE_DEST,:NEW.NUMBENE_DEST, :NEW.debut);
END;