CREATE TRIGGER ARTHUS."TRG_BF_INS_HISTO_ADHESION"
BEFORE INSERT
ON histo_adhesion
FOR EACH ROW

BEGIN

  IF :new.IDHISTOADHE IS NULL THEN
    SELECT  IDHISTOADHE.nextval
          INTO  :new.IDHISTOADHE
          FROM  Dual;
  END IF;

END;