CREATE TRIGGER ARTHUS.TRG_BF_INS_INTERLOCUTEUR
BEFORE INSERT
ON interlocuteur
FOR EACH ROW

BEGIN

  IF :new.IDINTERLOCUTEUR IS NULL THEN
    SELECT  IDINTERLOCUTEUR.nextval
          INTO  :new.IDINTERLOCUTEUR
          FROM  Dual;
  END IF;

END;