CREATE TRIGGER ARTHUS.TRG_BF_INS_ADHE_CNTRT_MEMBRE
BEFORE INSERT
ON adhe_cntrt_membre
FOR EACH ROW

BEGIN

  IF :new.IDADHECNTRTMB IS NULL THEN
    SELECT  IDADHECNTRTMB.nextval
          INTO  :new.IDADHECNTRTMB
          FROM  Dual;
  END IF;

END;