CREATE TRIGGER ARTHUS.TRG_AF_INS_RAPPEL
  AFTER INSERT ON RAPPEL
  REFERENCING NEW AS new
  FOR EACH ROW
DECLARE
 V_IDHISTORAPPEL histo_rappel.idhistorappel%type;
BEGIN

 --INSERT (new vlaues)
--    SELECT MAX(IDHISTORAPPEL)+1  INTO V_IDHISTORAPPEL FROM HISTO_RAPPEL;
    SELECT IDHISTORAPPEL.NEXTVAL INTO v_IDHISTORAPPEL FROM DUAL; -- PBO M0006431


		INSERT INTO HISTO_RAPPEL
					(IDRAPPEL,
					IDHISTORAPPEL,
					CONTEXTE,
					ENTITE,
					TYPE,
					REFERENCE,
					REVISION,
					CREATION,
					CREATEUR,
					MAJ,
					MODIFICATEUR,
					ETAT,
					RESPONSABLE,
					COMMENTAIRE,
					ACTION_HISTO)

			VALUES (:new.IDRAPPEL,
					v_IDHISTORAPPEL,
					:new.CONTEXTE,
					:new.ENTITE,
					:new.TYPE,
					:new.REFERENCE,
					:new.REVISION,
					:new.CREATION,
					:new.CREATEUR,
					SYSDATE,
					:new.MODIFICATEUR,
					:new.ETAT,
					:new.RESPONSABLE,
					:new.COMMENTAIRE,
					'I');


EXCEPTION
    WHEN OTHERS THEN NULL;
END;