CREATE TRIGGER ARTHUS."TRG_BF_INS_ANNUL_ENCAIS" 
   BEFORE INSERT ON ANNUL_ENCAIS
   REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
   
DECLARE
LOC_REMISE REMISE_BANQUE.NUMREMISE%Type;

BEGIN
    SELECT NUMREMISE INTO LOC_REMISE
    FROM REMISE_BANQUE
    WHERE NUMENCAISMT = :new.NUMENCAISMT ;
    
    -- insertion dans REMISE_BANQUE_ANNUL dans tous les cas
    INSERT INTO REMISE_BANQUE_ANNUL (NUMENCAISMT , NUMREMISE , TYPE , ETS_PAYEUR , LIEU_PMT , NOM_TIREUR , DATE_ANNUL , NUMUTIL_ANNUL)
    SELECT   NUMENCAISMT , NUMREMISE , TYPE , ETS_PAYEUR , LIEU_PMT , NOM_TIREUR , SYSDATE , F_NUMUTIL
    FROM REMISE_BANQUE
    WHERE REMISE_BANQUE.NUMENCAISMT = :new.NUMENCAISMT ; 

    -- si numremise  = 0 alors suppression de l'enreg dans REMISE_BANQUE
    IF LOC_REMISE = 0 THEN
      DELETE FROM REMISE_BANQUE WHERE REMISE_BANQUE.NUMENCAISMT = :new.NUMENCAISMT ;  
    END IF ;

EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL ; 
END ;