CREATE TRIGGER ARTHUS.TRG_BF_INS_UPD_LIBELLE_BIS
  BEFORE INSERT OR UPDATE
  ON LIBELLE_BIS
  FOR EACH ROW
BEGIN
  IF ( :NEW.CREATION IS NULL ) THEN
    :NEW.CREATION := TRUNC(SYSDATE);
    :NEW.MAJ := TRUNC(SYSDATE);
  ELSE
   :NEW.MAJ := TRUNC(SYSDATE);
  END IF;
END;