CREATE TRIGGER ARTHUS.trg_af_diu_decaismt
  AFTER DELETE OR INSERT OR UPDATE ON decaismt
  REFERENCING OLD AS old NEW AS new
  FOR EACH ROW
DECLARE
      l_action       VARCHAR2(1);
BEGIN
-- DELETE OR UPDATE (old values)
IF DELETING OR UPDATING THEN
   IF DELETING THEN
      l_action := 'D';
   END IF;
   IF UPDATING THEN
      l_action := 'U';
   END IF;
   INSERT INTO histo_decaismt (
      codope,
      numdecaismt,
      numcpte,
      numchq,
      modpmt,
      montant,
      monnaie,
      refpmt,
      datpay,
      typbene,
      numbene,
      debit,
      datcomp,
      numutil,
      numedit,
      datcompta,
      numdest,
      idcompta,
      datedit,
      flagpay,
      id_debit,
      date_debit,
      typdomi,
      numdomi,
      monnaie_d,
      montant_d,
      debit_d,
      montant_ec,
      type_ec,
      sens_ec,
      idreleve_compte,
      devise_ec,
      montant_ct,
      devise_ct,
      creation,
      dataffec,
      numdcptcie,
      numdcptcie_sin,
	  action_histo,
	  numutil_histo,
	  date_histo)
   VALUES (
      :old.codope,
      :old.numdecaismt,
      :old.numcpte,
      :old.numchq,
      :old.modpmt,
      :old.montant,
      :old.monnaie,
      :old.refpmt,
      :old.datpay,
      :old.typbene,
      :old.numbene,
      :old.debit,
      :old.datcomp,
      :old.numutil,
      :old.numedit,
      :old.datcompta,
      :old.numdest,
      :old.idcompta,
      :old.datedit,
      :old.flagpay,
      :old.id_debit,
      :old.date_debit,
      :old.typdomi,
      :old.numdomi,
      :old.monnaie_d,
      :old.montant_d,
      :old.debit_d,
      :old.montant_ec,
      :old.type_ec,
      :old.sens_ec,
      :old.idreleve_compte,
      :old.devise_ec,
      :old.montant_ct,
      :old.devise_ct,
      :old.creation,
      :old.dataffec,
      :old.numdcptcie,
      :old.numdcptcie_sin,
	  l_action,
	  f_numutil,
	  SYSDATE);
END IF;

-- INSERT (new vlaues)
IF INSERTING THEN
   INSERT INTO histo_decaismt (
      codope,
      numdecaismt,
      numcpte,
      numchq,
      modpmt,
      montant,
      monnaie,
      refpmt,
      datpay,
      typbene,
      numbene,
      debit,
      datcomp,
      numutil,
      numedit,
      datcompta,
      numdest,
      idcompta,
      datedit,
      flagpay,
      id_debit,
      date_debit,
      typdomi,
      numdomi,
      monnaie_d,
      montant_d,
      debit_d,
      montant_ec,
      type_ec,
      sens_ec,
      idreleve_compte,
      devise_ec,
      montant_ct,
      devise_ct,
      creation,
      dataffec,
      numdcptcie,
      numdcptcie_sin,
	  action_histo,
	  numutil_histo,
	  date_histo)
   VALUES (
      :new.codope,
      :new.numdecaismt,
      :new.numcpte,
      :new.numchq,
      :new.modpmt,
      :new.montant,
      :new.monnaie,
      :new.refpmt,
      :new.datpay,
      :new.typbene,
      :new.numbene,
      :new.debit,
      :new.datcomp,
      :new.numutil,
      :new.numedit,
      :new.datcompta,
      :new.numdest,
      :new.idcompta,
      :new.datedit,
      :new.flagpay,
      :new.id_debit,
      :new.date_debit,
      :new.typdomi,
      :new.numdomi,
      :new.monnaie_d,
      :new.montant_d,
      :new.debit_d,
      :new.montant_ec,
      :new.type_ec,
      :new.sens_ec,
      :new.idreleve_compte,
      :new.devise_ec,
      :new.montant_ct,
      :new.devise_ct,
      :new.creation,
      :new.dataffec,
      :new.numdcptcie,
      :new.numdcptcie_sin,
	  'I',
	  f_numutil,
	  SYSDATE);
END IF;

EXCEPTION
    WHEN OTHERS THEN NULL;
END;