CREATE TRIGGER ARTHUS.TRG_AF_UPD_UTILISATEURS_PROFIL
FOR UPDATE OR INSERT ON "ARTHUS"."UTILISATEURS"
COMPOUND TRIGGER

  fnumutil UTILISATEURS.NUMUTIL%TYPE ;

  --Executed before DML statement
  BEFORE STATEMENT IS
  BEGIN
    fnumutil := f_numutil;
  END BEFORE STATEMENT;

  AFTER EACH ROW IS
  BEGIN
    IF :NEW.profil <> :OLD.profil THEN
      INSERT INTO histo_utilisateurs (PROFIL, NUMUTIL, USERMAJ, DATEMAJ)
      VALUES (:NEW.profil, :NEW.numutil, fnumutil, SYSDATE);
    END IF;
  END AFTER EACH ROW;
END TRG_AF_UPD_UTILISATEURS_PROFIL;