CREATE TRIGGER ARTHUS.TRG_BF_INS_CONTACT
BEFORE INSERT
ON contact
FOR EACH ROW

BEGIN

  IF :new.IDCONTACT IS NULL THEN
    SELECT  IDCONTACT.nextval
          INTO  :new.IDCONTACT
          FROM  Dual;
  END IF;

END;