CREATE TRIGGER ARTHUS.TRG_BF_INS_FLUX
before INSERT ON FLUX
FOR EACH row
BEGIN
  IF inserting THEN
     IF :NEW.ID_FLUX IS NULL THEN
        SELECT IDFLUX.nextval INTO :NEW.ID_FLUX FROM dual;
      END IF;
  END IF;
END;