CREATE TRIGGER ARTHUS.trg_af_diu_decompte
  AFTER DELETE OR INSERT OR UPDATE ON decompte
  REFERENCING OLD AS old NEW AS new
  FOR EACH ROW
DECLARE
      l_action       VARCHAR2(1);
BEGIN
-- DELETE OR UPDATE (old values)
IF DELETING OR UPDATING THEN
   IF DELETING THEN
      l_action := 'D';
   END IF;
   IF UPDATING THEN
      l_action := 'U';
   END IF;
   INSERT INTO histo_decompte (
      numdec,
      numindiv,
      montant,
      datpay,
      modpmt,
      typbene,
      numbene,
      refpmt,
      cptcomp,
      monnaie,
      nbfeuille,
      numpmt,
      numbque,
      debit,
      flagedit,
      numgar,
      mtfrais,
      mtremb,
      autrb,
      mtreel,
      numdcptcie,
      numutil,
      monnaie_d,
      montant_d,
      mtfrais_d,
      debit_d,
      mtremb_d,
      autrb_d,
      mtreel_d,
      numdest,
      roledest,
      montant_ec,
      type_ec,
      sens_ec,
      devise_ec,
      montant_ct,
      devise_ct,
      idcompta,
	  action_histo,
	  numutil_histo,
	  date_histo)
   VALUES (
      :old.numdec,
      :old.numindiv,
      :old.montant,
      :old.datpay,
      :old.modpmt,
      :old.typbene,
      :old.numbene,
      :old.refpmt,
      :old.cptcomp,
      :old.monnaie,
      :old.nbfeuille,
      :old.numpmt,
      :old.numbque,
      :old.debit,
      :old.flagedit,
      :old.numgar,
      :old.mtfrais,
      :old.mtremb,
      :old.autrb,
      :old.mtreel,
      :old.numdcptcie,
      :old.numutil,
      :old.monnaie_d,
      :old.montant_d,
      :old.mtfrais_d,
      :old.debit_d,
      :old.mtremb_d,
      :old.autrb_d,
      :old.mtreel_d,
      :old.numdest,
      :old.roledest,
      :old.montant_ec,
      :old.type_ec,
      :old.sens_ec,
      :old.devise_ec,
      :old.montant_ct,
      :old.devise_ct,
      :old.idcompta,
	  l_action,
	  f_numutil,
	  SYSDATE);
END IF;

-- INSERT (new vlaues)
IF INSERTING THEN
   INSERT INTO histo_decompte (
      numdec,
      numindiv,
      montant,
      datpay,
      modpmt,
      typbene,
      numbene,
      refpmt,
      cptcomp,
      monnaie,
      nbfeuille,
      numpmt,
      numbque,
      debit,
      flagedit,
      numgar,
      mtfrais,
      mtremb,
      autrb,
      mtreel,
      numdcptcie,
      numutil,
      monnaie_d,
      montant_d,
      mtfrais_d,
      debit_d,
      mtremb_d,
      autrb_d,
      mtreel_d,
      numdest,
      roledest,
      montant_ec,
      type_ec,
      sens_ec,
      devise_ec,
      montant_ct,
      devise_ct,
      idcompta,
	  action_histo,
	  numutil_histo,
	  date_histo)
   VALUES (
      :new.numdec,
      :new.numindiv,
      :new.montant,
      :new.datpay,
      :new.modpmt,
      :new.typbene,
      :new.numbene,
      :new.refpmt,
      :new.cptcomp,
      :new.monnaie,
      :new.nbfeuille,
      :new.numpmt,
      :new.numbque,
      :new.debit,
      :new.flagedit,
      :new.numgar,
      :new.mtfrais,
      :new.mtremb,
      :new.autrb,
      :new.mtreel,
      :new.numdcptcie,
      :new.numutil,
      :new.monnaie_d,
      :new.montant_d,
      :new.mtfrais_d,
      :new.debit_d,
      :new.mtremb_d,
      :new.autrb_d,
      :new.mtreel_d,
      :new.numdest,
      :new.roledest,
      :new.montant_ec,
      :new.type_ec,
      :new.sens_ec,
      :new.devise_ec,
      :new.montant_ct,
      :new.devise_ct,
      :new.idcompta,
	  'I',
	  f_numutil,
	  SYSDATE);
END IF;

EXCEPTION
    WHEN OTHERS THEN NULL;
END;