CREATE TRIGGER ARTHUS.TRG_BF_INS_PIECES
before INSERT ON PIECES
FOR EACH row
BEGIN
  IF inserting THEN
     IF :NEW.IDPIECE IS NULL THEN
        SELECT SEQ_PIECES.nextval INTO :NEW.IDPIECE FROM dual;
      END IF;
  END IF;
END;