CREATE TRIGGER ARTHUS.trg_af_diu_remise_op_detail
  AFTER DELETE OR INSERT OR UPDATE ON remise_op_detail
  REFERENCING OLD AS old NEW AS new
  FOR EACH ROW
DECLARE
      l_action       VARCHAR2(1);
BEGIN
-- DELETE OR UPDATE (old values)
IF DELETING OR UPDATING THEN
   IF DELETING THEN
      l_action := 'D';
   END IF;
   IF UPDATING THEN
      l_action := 'U';
   END IF;
   INSERT INTO histo_remise_op_detail (
      numremise,
      numvirement,
      numcpte,
      numdecaismt,
      montant,
      codbque,
      guichet,
      compte,
      clerib,
      intitule,
      clef_iban,
      bban,
      bic,
      codpays,
      monnaie_d,
      montant_d,
      monnaie,
      modpmt,
      codbque_etrg,
      typ_bq_etrg,
      guichet_etrg,
      typ_gui_etrg,
      compte_etrg,
      clerib_etrg,
      typ_cle_etrg,
      numindiv_etrg,
      nature,
      montant_ct,
      monnaie_ct,
      montant_ec,
      type_ec,
      sens_ec,
      devise_ec,
      idreleve_compte,
	  action_histo,
	  numutil_histo,
	  date_histo)
   VALUES (
      :old.numremise,
      :old.numvirement,
      :old.numcpte,
      :old.numdecaismt,
      :old.montant,
      :old.codbque,
      :old.guichet,
      :old.compte,
      :old.clerib,
      :old.intitule,
      :old.clef_iban,
      :old.bban,
      :old.bic,
      :old.codpays,
      :old.monnaie_d,
      :old.montant_d,
      :old.monnaie,
      :old.modpmt,
      :old.codbque_etrg,
      :old.typ_bq_etrg,
      :old.guichet_etrg,
      :old.typ_gui_etrg,
      :old.compte_etrg,
      :old.clerib_etrg,
      :old.typ_cle_etrg,
      :old.numindiv_etrg,
      :old.nature,
      :old.montant_ct,
      :old.monnaie_ct,
      :old.montant_ec,
      :old.type_ec,
      :old.sens_ec,
      :old.devise_ec,
      :old.idreleve_compte,
	  l_action,
	  f_numutil,
	  SYSDATE);
END IF;

-- INSERT (new vlaues)
IF INSERTING THEN
   INSERT INTO histo_remise_op_detail (
      numremise,
      numvirement,
      numcpte,
      numdecaismt,
      montant,
      codbque,
      guichet,
      compte,
      clerib,
      intitule,
      clef_iban,
      bban,
      bic,
      codpays,
      monnaie_d,
      montant_d,
      monnaie,
      modpmt,
      codbque_etrg,
      typ_bq_etrg,
      guichet_etrg,
      typ_gui_etrg,
      compte_etrg,
      clerib_etrg,
      typ_cle_etrg,
      numindiv_etrg,
      nature,
      montant_ct,
      monnaie_ct,
      montant_ec,
      type_ec,
      sens_ec,
      devise_ec,
      idreleve_compte,
	  action_histo,
	  numutil_histo,
	  date_histo)
   VALUES (
      :new.numremise,
      :new.numvirement,
      :new.numcpte,
      :new.numdecaismt,
      :new.montant,
      :new.codbque,
      :new.guichet,
      :new.compte,
      :new.clerib,
      :new.intitule,
      :new.clef_iban,
      :new.bban,
      :new.bic,
      :new.codpays,
      :new.monnaie_d,
      :new.montant_d,
      :new.monnaie,
      :new.modpmt,
      :new.codbque_etrg,
      :new.typ_bq_etrg,
      :new.guichet_etrg,
      :new.typ_gui_etrg,
      :new.compte_etrg,
      :new.clerib_etrg,
      :new.typ_cle_etrg,
      :new.numindiv_etrg,
      :new.nature,
      :new.montant_ct,
      :new.monnaie_ct,
      :new.montant_ec,
      :new.type_ec,
      :new.sens_ec,
      :new.devise_ec,
      :new.idreleve_compte,
	  'I',
	  f_numutil,
	  SYSDATE);
END IF;

EXCEPTION
    WHEN OTHERS THEN NULL;
END;