CREATE TRIGGER ARTHUS.TRG_BF_INS_PRDGECHANGE
before INSERT ON PRDGECHANGE
FOR EACH row
BEGIN
  IF inserting THEN
     IF :NEW.IDFLUX IS NULL THEN
        SELECT IDFLUXPRDG.nextval INTO :NEW.IDFLUX FROM dual;
      END IF;
  END IF;
END;