-- Synonyme PUBLIC : ADHE_CNTRT_MEMBRESAVFS
-- Cible      : ARTHUS.ADHE_CNTRT_MEMBRESAVFS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM ADHE_CNTRT_MEMBRESAVFS FOR ARTHUS.ADHE_CNTRT_MEMBRESAVFS;
