-- Synonyme PUBLIC : ADR_INTERNATIONALE
-- Cible      : ARTHUS.ADR_INTERNATIONALE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM ADR_INTERNATIONALE FOR ARTHUS.ADR_INTERNATIONALE;
