-- Synonyme PUBLIC : AFFECTATION_ANNUL
-- Cible      : ARTHUS.AFFECTATION_ANNUL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM AFFECTATION_ANNUL FOR ARTHUS.AFFECTATION_ANNUL;
