-- Synonyme PUBLIC : AFFIL_PORTE_QTTC_INDIV
-- Cible      : ARTHUS.AFFIL_PORTE_QTTC_INDIV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM AFFIL_PORTE_QTTC_INDIV FOR ARTHUS.AFFIL_PORTE_QTTC_INDIV;
