-- Synonyme PUBLIC : AFFIL_PORTE_QTTC_ELT
-- Cible      : ARTHUS.AFFIL_PORTE_QTTC_ELT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM AFFIL_PORTE_QTTC_ELT FOR ARTHUS.AFFIL_PORTE_QTTC_ELT;
