-- Synonyme PUBLIC : AFFIL_PORTE_PAIEMENT
-- Cible      : ARTHUS.AFFIL_PORTE_PAIEMENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM AFFIL_PORTE_PAIEMENT FOR ARTHUS.AFFIL_PORTE_PAIEMENT;
