-- Synonyme PUBLIC : AFFIL_PORTE_FORCAGE
-- Cible      : ARTHUS.AFFIL_PORTE_FORCAGE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM AFFIL_PORTE_FORCAGE FOR ARTHUS.AFFIL_PORTE_FORCAGE;
