-- Synonyme PUBLIC : AFFIL_PORTE_QTTC
-- Cible      : ARTHUS.AFFIL_PORTE_QTTC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM AFFIL_PORTE_QTTC FOR ARTHUS.AFFIL_PORTE_QTTC;
