-- Synonyme PUBLIC : AFFIL_PORTE_ARRET
-- Cible      : ARTHUS.AFFIL_PORTE_ARRET
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM AFFIL_PORTE_ARRET FOR ARTHUS.AFFIL_PORTE_ARRET;
