-- Synonyme PUBLIC : AFFIL_PORTE_CNTRT
-- Cible      : ARTHUS.AFFIL_PORTE_CNTRT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM AFFIL_PORTE_CNTRT FOR ARTHUS.AFFIL_PORTE_CNTRT;
