-- Synonyme PUBLIC : ANO_COMPTE_TIERS
-- Cible      : ARTHUS.ANO_COMPTE_TIERS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM ANO_COMPTE_TIERS FOR ARTHUS.ANO_COMPTE_TIERS;
