-- Synonyme PUBLIC : CALCUL_BKP_OPIEVOY
-- Cible      : ARTHUS.CALCUL_BKP_OPIEVOY
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM CALCUL_BKP_OPIEVOY FOR ARTHUS.CALCUL_BKP_OPIEVOY;
