-- Synonyme PUBLIC : COMPTA_OPE_COMPTE
-- Cible      : ARTHUS.COMPTA_OPE_COMPTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM COMPTA_OPE_COMPTE FOR ARTHUS.COMPTA_OPE_COMPTE;
