-- Synonyme PUBLIC : COMPTE_EXTRANET_TEMPO
-- Cible      : ARTHUS.COMPTE_EXTRANET_TEMPO
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM COMPTE_EXTRANET_TEMPO FOR ARTHUS.COMPTE_EXTRANET_TEMPO;
