-- Synonyme PUBLIC : COMPTA_LIB_REGLT
-- Cible      : ARTHUS.COMPTA_LIB_REGLT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM COMPTA_LIB_REGLT FOR ARTHUS.COMPTA_LIB_REGLT;
