-- Synonyme PUBLIC : COND_SOUSCRIPTION
-- Cible      : ARTHUS.COND_SOUSCRIPTION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM COND_SOUSCRIPTION FOR ARTHUS.COND_SOUSCRIPTION;
