-- Synonyme PUBLIC : COND_PROPOSITION
-- Cible      : ARTHUS.COND_PROPOSITION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM COND_PROPOSITION FOR ARTHUS.COND_PROPOSITION;
