-- Synonyme PUBLIC : COND_ADHESION_GAR
-- Cible      : ARTHUS.COND_ADHESION_GAR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM COND_ADHESION_GAR FOR ARTHUS.COND_ADHESION_GAR;
