-- Synonyme PUBLIC : CONTROL_ADHESION
-- Cible      : ARTHUS.CONTROL_ADHESION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM CONTROL_ADHESION FOR ARTHUS.CONTROL_ADHESION;
