-- Synonyme PUBLIC : CONV_PRELEVEMENT_DETAIL
-- Cible      : ARTHUS.CONV_PRELEVEMENT_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM CONV_PRELEVEMENT_DETAIL FOR ARTHUS.CONV_PRELEVEMENT_DETAIL;
