-- Synonyme PUBLIC : DCPTCIE_PREV_DETAIL
-- Cible      : ARTHUS.DCPTCIE_PREV_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM DCPTCIE_PREV_DETAIL FOR ARTHUS.DCPTCIE_PREV_DETAIL;
