-- Synonyme PUBLIC : DEMANDE_TIERS_PAYANT
-- Cible      : ARTHUS.DEMANDE_TIERS_PAYANT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM DEMANDE_TIERS_PAYANT FOR ARTHUS.DEMANDE_TIERS_PAYANT;
