-- Synonyme PUBLIC : DETTE_PREV_DETAIL
-- Cible      : ARTHUS.DETTE_PREV_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM DETTE_PREV_DETAIL FOR ARTHUS.DETTE_PREV_DETAIL;
