-- Synonyme PUBLIC : DEVIS_SANTE_DETAIL
-- Cible      : ARTHUS.DEVIS_SANTE_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM DEVIS_SANTE_DETAIL FOR ARTHUS.DEVIS_SANTE_DETAIL;
