-- Synonyme PUBLIC : DOS_SIN_DETENTEUR
-- Cible      : ARTHUS.DOS_SIN_DETENTEUR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM DOS_SIN_DETENTEUR FOR ARTHUS.DOS_SIN_DETENTEUR;
