-- Synonyme PUBLIC : DOSSIER_SINISTRE
-- Cible      : ARTHUS.DOSSIER_SINISTRE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM DOSSIER_SINISTRE FOR ARTHUS.DOSSIER_SINISTRE;
