-- Synonyme PUBLIC : DSN_CRM_CONTEXTE
-- Cible      : ARTHUS.DSN_CRM_CONTEXTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM DSN_CRM_CONTEXTE FOR ARTHUS.DSN_CRM_CONTEXTE;
