-- Synonyme PUBLIC : DSN_FICHE_CONTRAT
-- Cible      : ARTHUS.DSN_FICHE_CONTRAT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM DSN_FICHE_CONTRAT FOR ARTHUS.DSN_FICHE_CONTRAT;
