-- Synonyme PUBLIC : ECHANGE_HOMONYME
-- Cible      : ARTHUS.ECHANGE_HOMONYME
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM ECHANGE_HOMONYME FOR ARTHUS.ECHANGE_HOMONYME;
