-- Synonyme PUBLIC : FORCAGE_TRAITEMENT
-- Cible      : ARTHUS.FORCAGE_TRAITEMENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM FORCAGE_TRAITEMENT FOR ARTHUS.FORCAGE_TRAITEMENT;
