-- Synonyme PUBLIC : FRML_PRIME_SIMPLE
-- Cible      : ARTHUS.FRML_PRIME_SIMPLE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM FRML_PRIME_SIMPLE FOR ARTHUS.FRML_PRIME_SIMPLE;
