-- Synonyme PUBLIC : GAR_PARAM_DETAIL
-- Cible      : ARTHUS.GAR_PARAM_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM GAR_PARAM_DETAIL FOR ARTHUS.GAR_PARAM_DETAIL;
