-- Synonyme PUBLIC : GEST_DETAIL_RISQ
-- Cible      : ARTHUS.GEST_DETAIL_RISQ
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM GEST_DETAIL_RISQ FOR ARTHUS.GEST_DETAIL_RISQ;
