-- Synonyme PUBLIC : HISTO_TABLE_HISTO_FRMLVAR
-- Cible      : ARTHUS.HISTO_TABLE_HISTO_FRMLVAR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_TABLE_HISTO_FRMLVAR FOR ARTHUS.HISTO_TABLE_HISTO_FRMLVAR;
