-- Synonyme PUBLIC : HISTO_PORTE_NATFRAIS
-- Cible      : ARTHUS.HISTO_PORTE_NATFRAIS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_PORTE_NATFRAIS FOR ARTHUS.HISTO_PORTE_NATFRAIS;
