-- Synonyme PUBLIC : HISTO_NTFRS_TYPE_SUP
-- Cible      : ARTHUS.HISTO_NTFRS_TYPE_SUP
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_NTFRS_TYPE_SUP FOR ARTHUS.HISTO_NTFRS_TYPE_SUP;
