-- Synonyme PUBLIC : HISTO_COURRIER_INFO
-- Cible      : ARTHUS.HISTO_COURRIER_INFO
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_COURRIER_INFO FOR ARTHUS.HISTO_COURRIER_INFO;
