-- Synonyme PUBLIC : HISTO_FRML_PRIME_SIMPLE
-- Cible      : ARTHUS.HISTO_FRML_PRIME_SIMPLE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_FRML_PRIME_SIMPLE FOR ARTHUS.HISTO_FRML_PRIME_SIMPLE;
