-- Synonyme PUBLIC : HISTO_CONTRAT_REF
-- Cible      : ARTHUS.HISTO_CONTRAT_REF
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_CONTRAT_REF FOR ARTHUS.HISTO_CONTRAT_REF;
