-- Synonyme PUBLIC : HISTO_FRML_REASS
-- Cible      : ARTHUS.HISTO_FRML_REASS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_FRML_REASS FOR ARTHUS.HISTO_FRML_REASS;
