-- Synonyme PUBLIC : HISTO_PRELEVEMENT
-- Cible      : ARTHUS.HISTO_PRELEVEMENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_PRELEVEMENT FOR ARTHUS.HISTO_PRELEVEMENT;
