-- Synonyme PUBLIC : HISTO_ADHESIONSAVFS
-- Cible      : ARTHUS.HISTO_ADHESIONSAVFS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_ADHESIONSAVFS FOR ARTHUS.HISTO_ADHESIONSAVFS;
