-- Synonyme PUBLIC : HISTO_TABLE_CALCUL
-- Cible      : ARTHUS.HISTO_TABLE_CALCUL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_TABLE_CALCUL FOR ARTHUS.HISTO_TABLE_CALCUL;
