-- Synonyme PUBLIC : HISTO_FRML_REVAL
-- Cible      : ARTHUS.HISTO_FRML_REVAL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_FRML_REVAL FOR ARTHUS.HISTO_FRML_REVAL;
