-- Synonyme PUBLIC : HISTO_TYPE_MONTURE
-- Cible      : ARTHUS.HISTO_TYPE_MONTURE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_TYPE_MONTURE FOR ARTHUS.HISTO_TYPE_MONTURE;
