-- Synonyme PUBLIC : HISTO_FLUX_WS_SC
-- Cible      : ARTHUS.HISTO_FLUX_WS_SC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_FLUX_WS_SC FOR ARTHUS.HISTO_FLUX_WS_SC;
