-- Synonyme PUBLIC : HISTO_LIBFORMATH
-- Cible      : ARTHUS.HISTO_LIBFORMATH
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_LIBFORMATH FOR ARTHUS.HISTO_LIBFORMATH;
