-- Synonyme PUBLIC : HISTO_DECOMPTE_PREV
-- Cible      : ARTHUS.HISTO_DECOMPTE_PREV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_DECOMPTE_PREV FOR ARTHUS.HISTO_DECOMPTE_PREV;
