-- Synonyme PUBLIC : HISTO_PARTENARIAT
-- Cible      : ARTHUS.HISTO_PARTENARIAT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_PARTENARIAT FOR ARTHUS.HISTO_PARTENARIAT;
