-- Synonyme PUBLIC : HISTO_REMISE_PRELEV
-- Cible      : ARTHUS.HISTO_REMISE_PRELEV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_REMISE_PRELEV FOR ARTHUS.HISTO_REMISE_PRELEV;
