-- Synonyme PUBLIC : HISTO_PROPOSITION
-- Cible      : ARTHUS.HISTO_PROPOSITION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_PROPOSITION FOR ARTHUS.HISTO_PROPOSITION;
