-- Synonyme PUBLIC : HISTO_NTFRS_DETAIL
-- Cible      : ARTHUS.HISTO_NTFRS_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_NTFRS_DETAIL FOR ARTHUS.HISTO_NTFRS_DETAIL;
