-- Synonyme PUBLIC : HISTO_REMISE_VIRE_DETAIL
-- Cible      : ARTHUS.HISTO_REMISE_VIRE_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_REMISE_VIRE_DETAIL FOR ARTHUS.HISTO_REMISE_VIRE_DETAIL;
