-- Synonyme PUBLIC : HISTO_FRML_PREST
-- Cible      : ARTHUS.HISTO_FRML_PREST
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_FRML_PREST FOR ARTHUS.HISTO_FRML_PREST;
