-- Synonyme PUBLIC : HISTO_PORTE_CONTRAT
-- Cible      : ARTHUS.HISTO_PORTE_CONTRAT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_PORTE_CONTRAT FOR ARTHUS.HISTO_PORTE_CONTRAT;
