-- Synonyme PUBLIC : HISTO_RENEW_LENTILLE
-- Cible      : ARTHUS.HISTO_RENEW_LENTILLE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_RENEW_LENTILLE FOR ARTHUS.HISTO_RENEW_LENTILLE;
