-- Synonyme PUBLIC : HISTO_SINISTRE_SANTE
-- Cible      : ARTHUS.HISTO_SINISTRE_SANTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_SINISTRE_SANTE FOR ARTHUS.HISTO_SINISTRE_SANTE;
