-- Synonyme PUBLIC : HISTO_GAR_PARAM_DETAIL
-- Cible      : ARTHUS.HISTO_GAR_PARAM_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_GAR_PARAM_DETAIL FOR ARTHUS.HISTO_GAR_PARAM_DETAIL;
