-- Synonyme PUBLIC : HISTO_CALCUL_ANNUL
-- Cible      : ARTHUS.HISTO_CALCUL_ANNUL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_CALCUL_ANNUL FOR ARTHUS.HISTO_CALCUL_ANNUL;
