-- Synonyme PUBLIC : HISTO_FRMLVAR_DETAIL
-- Cible      : ARTHUS.HISTO_FRMLVAR_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_FRMLVAR_DETAIL FOR ARTHUS.HISTO_FRMLVAR_DETAIL;
