-- Synonyme PUBLIC : HISTO_NTFRS_MATIERE
-- Cible      : ARTHUS.HISTO_NTFRS_MATIERE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_NTFRS_MATIERE FOR ARTHUS.HISTO_NTFRS_MATIERE;
