-- Synonyme PUBLIC : HISTO_AFFECTATION
-- Cible      : ARTHUS.HISTO_AFFECTATION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_AFFECTATION FOR ARTHUS.HISTO_AFFECTATION;
