-- Synonyme PUBLIC : HISTO_NTFRS_OPTIQUE
-- Cible      : ARTHUS.HISTO_NTFRS_OPTIQUE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_NTFRS_OPTIQUE FOR ARTHUS.HISTO_NTFRS_OPTIQUE;
