-- Synonyme PUBLIC : HISTO_UTILISATEURS
-- Cible      : ARTHUS.HISTO_UTILISATEURS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_UTILISATEURS FOR ARTHUS.HISTO_UTILISATEURS;
