-- Synonyme PUBLIC : HISTO_NTFRS_TYP_VISION
-- Cible      : ARTHUS.HISTO_NTFRS_TYP_VISION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_NTFRS_TYP_VISION FOR ARTHUS.HISTO_NTFRS_TYP_VISION;
