-- Synonyme PUBLIC : HISTO_REMISE_VIRE
-- Cible      : ARTHUS.HISTO_REMISE_VIRE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_REMISE_VIRE FOR ARTHUS.HISTO_REMISE_VIRE;
