-- Synonyme PUBLIC : HISTO_PRELEVEMENT_DETAIL
-- Cible      : ARTHUS.HISTO_PRELEVEMENT_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_PRELEVEMENT_DETAIL FOR ARTHUS.HISTO_PRELEVEMENT_DETAIL;
