-- Synonyme PUBLIC : HISTO_CENTREPAYEUR
-- Cible      : ARTHUS.HISTO_CENTREPAYEUR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM HISTO_CENTREPAYEUR FOR ARTHUS.HISTO_CENTREPAYEUR;
