-- Synonyme PUBLIC : INTERM_TYPAPPORT
-- Cible      : ARTHUS.INTERM_TYPAPPORT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM INTERM_TYPAPPORT FOR ARTHUS.INTERM_TYPAPPORT;
