-- Synonyme PUBLIC : MAXACT_BKP_OPIEVOY
-- Cible      : ARTHUS.MAXACT_BKP_OPIEVOY
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM MAXACT_BKP_OPIEVOY FOR ARTHUS.MAXACT_BKP_OPIEVOY;
