-- Synonyme PUBLIC : NTFRS_CCAM_RGRPT
-- Cible      : ARTHUS.NTFRS_CCAM_RGRPT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM NTFRS_CCAM_RGRPT FOR ARTHUS.NTFRS_CCAM_RGRPT;
