-- Synonyme PUBLIC : NTFRS_TYP_VISION
-- Cible      : ARTHUS.NTFRS_TYP_VISION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM NTFRS_TYP_VISION FOR ARTHUS.NTFRS_TYP_VISION;
