-- Synonyme PUBLIC : OLD_SNTRPRT_CETIP
-- Cible      : ARTHUS.OLD_SNTRPRT_CETIP
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM OLD_SNTRPRT_CETIP FOR ARTHUS.OLD_SNTRPRT_CETIP;
