-- Synonyme PUBLIC : PARAM_DEMANDE_TP
-- Cible      : ARTHUS.PARAM_DEMANDE_TP
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PARAM_DEMANDE_TP FOR ARTHUS.PARAM_DEMANDE_TP;
