-- Synonyme PUBLIC : PARAM_TIERS_PAYANT
-- Cible      : ARTHUS.PARAM_TIERS_PAYANT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PARAM_TIERS_PAYANT FOR ARTHUS.PARAM_TIERS_PAYANT;
