-- Synonyme PUBLIC : PERS_HISTO_MORALE
-- Cible      : ARTHUS.PERS_HISTO_MORALE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PERS_HISTO_MORALE FOR ARTHUS.PERS_HISTO_MORALE;
