-- Synonyme PUBLIC : PERS_TIERSPAYANT
-- Cible      : ARTHUS.PERS_TIERSPAYANT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PERS_TIERSPAYANT FOR ARTHUS.PERS_TIERSPAYANT;
