-- Synonyme PUBLIC : PERS_INTERMEDIAIRE
-- Cible      : ARTHUS.PERS_INTERMEDIAIRE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PERS_INTERMEDIAIRE FOR ARTHUS.PERS_INTERMEDIAIRE;
