-- Synonyme PUBLIC : PERS_CENTREPAYEUR
-- Cible      : ARTHUS.PERS_CENTREPAYEUR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PERS_CENTREPAYEUR FOR ARTHUS.PERS_CENTREPAYEUR;
