-- Synonyme PUBLIC : PERS_HISTO_PHYSSAVFS
-- Cible      : ARTHUS.PERS_HISTO_PHYSSAVFS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PERS_HISTO_PHYSSAVFS FOR ARTHUS.PERS_HISTO_PHYSSAVFS;
