-- Synonyme PUBLIC : PORTE_ADHESION_SAV
-- Cible      : ARTHUS.PORTE_ADHESION_SAV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PORTE_ADHESION_SAV FOR ARTHUS.PORTE_ADHESION_SAV;
