-- Synonyme PUBLIC : PORTE_ENTITE_ORDRE
-- Cible      : ARTHUS.PORTE_ENTITE_ORDRE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PORTE_ENTITE_ORDRE FOR ARTHUS.PORTE_ENTITE_ORDRE;
