-- Synonyme PUBLIC : PRELEVEMENT_DETAIL
-- Cible      : ARTHUS.PRELEVEMENT_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PRELEVEMENT_DETAIL FOR ARTHUS.PRELEVEMENT_DETAIL;
