-- Synonyme PUBLIC : PREV_REGLT_DELEG
-- Cible      : ARTHUS.PREV_REGLT_DELEG
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PREV_REGLT_DELEG FOR ARTHUS.PREV_REGLT_DELEG;
