-- Synonyme PUBLIC : PROCEDURES_OBJECTS
-- Cible      : ARTHUS.PROCEDURES_OBJECTS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PROCEDURES_OBJECTS FOR ARTHUS.PROCEDURES_OBJECTS;
