-- Synonyme PUBLIC : QTTC_GLOBAL_DELETE
-- Cible      : ARTHUS.QTTC_GLOBAL_DELETE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM QTTC_GLOBAL_DELETE FOR ARTHUS.QTTC_GLOBAL_DELETE;
