-- Synonyme PUBLIC : QUEST_SL_TEMP_EXPLAIN1
-- Cible      : ARTHUS.QUEST_SL_TEMP_EXPLAIN1
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM QUEST_SL_TEMP_EXPLAIN1 FOR ARTHUS.QUEST_SL_TEMP_EXPLAIN1;
