-- Synonyme PUBLIC : RAPPEL_SIN_PREV_SAL
-- Cible      : ARTHUS.RAPPEL_SIN_PREV_SAL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM RAPPEL_SIN_PREV_SAL FOR ARTHUS.RAPPEL_SIN_PREV_SAL;
