-- Synonyme PUBLIC : RAPPEL_SIN_PREV_MAINT
-- Cible      : ARTHUS.RAPPEL_SIN_PREV_MAINT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM RAPPEL_SIN_PREV_MAINT FOR ARTHUS.RAPPEL_SIN_PREV_MAINT;
