-- Synonyme PUBLIC : RAPPEL_SOUSCRIPT
-- Cible      : ARTHUS.RAPPEL_SOUSCRIPT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM RAPPEL_SOUSCRIPT FOR ARTHUS.RAPPEL_SOUSCRIPT;
