-- Synonyme PUBLIC : RECOURS_SINISTRE
-- Cible      : ARTHUS.RECOURS_SINISTRE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM RECOURS_SINISTRE FOR ARTHUS.RECOURS_SINISTRE;
