-- Synonyme PUBLIC : REGLE_REP_DONNEES
-- Cible      : ARTHUS.REGLE_REP_DONNEES
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM REGLE_REP_DONNEES FOR ARTHUS.REGLE_REP_DONNEES;
