-- Synonyme PUBLIC : REMISE_OP_DETAIL
-- Cible      : ARTHUS.REMISE_OP_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM REMISE_OP_DETAIL FOR ARTHUS.REMISE_OP_DETAIL;
