-- Synonyme PUBLIC : REMISE_VIRE_DETAIL
-- Cible      : ARTHUS.REMISE_VIRE_DETAIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM REMISE_VIRE_DETAIL FOR ARTHUS.REMISE_VIRE_DETAIL;
