-- Synonyme PUBLIC : REMISE_COMPTA_GLOBALE
-- Cible      : ARTHUS.REMISE_COMPTA_GLOBALE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM REMISE_COMPTA_GLOBALE FOR ARTHUS.REMISE_COMPTA_GLOBALE;
