-- Synonyme PUBLIC : REMISE_BANQUE_ANNUL
-- Cible      : ARTHUS.REMISE_BANQUE_ANNUL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM REMISE_BANQUE_ANNUL FOR ARTHUS.REMISE_BANQUE_ANNUL;
