-- Synonyme PUBLIC : REMISE_TRANSFERT
-- Cible      : ARTHUS.REMISE_TRANSFERT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM REMISE_TRANSFERT FOR ARTHUS.REMISE_TRANSFERT;
