-- Synonyme PUBLIC : REP_FONCTION_TOUS
-- Cible      : ARTHUS.REP_FONCTION_TOUS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM REP_FONCTION_TOUS FOR ARTHUS.REP_FONCTION_TOUS;
