-- Synonyme PUBLIC : REPARTITION_BENE
-- Cible      : ARTHUS.REPARTITION_BENE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM REPARTITION_BENE FOR ARTHUS.REPARTITION_BENE;
