-- Synonyme PUBLIC : SEQRUB_BKP_OPIEVOY
-- Cible      : ARTHUS.SEQRUB_BKP_OPIEVOY
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SEQRUB_BKP_OPIEVOY FOR ARTHUS.SEQRUB_BKP_OPIEVOY;
