-- Synonyme PUBLIC : SINISTRE_SANTE_ANNUL
-- Cible      : ARTHUS.SINISTRE_SANTE_ANNUL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SINISTRE_SANTE_ANNUL FOR ARTHUS.SINISTRE_SANTE_ANNUL;
