-- Synonyme PUBLIC : SINISTRE_ANNUL_SAV
-- Cible      : ARTHUS.SINISTRE_ANNUL_SAV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SINISTRE_ANNUL_SAV FOR ARTHUS.SINISTRE_ANNUL_SAV;
