-- Synonyme PUBLIC : SINISTRE_PORTE_FORCAGE
-- Cible      : ARTHUS.SINISTRE_PORTE_FORCAGE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SINISTRE_PORTE_FORCAGE FOR ARTHUS.SINISTRE_PORTE_FORCAGE;
