-- Synonyme PUBLIC : SINISTRE_DEV_ANNUL
-- Cible      : ARTHUS.SINISTRE_DEV_ANNUL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SINISTRE_DEV_ANNUL FOR ARTHUS.SINISTRE_DEV_ANNUL;
