-- Synonyme PUBLIC : SINISTRE_FORCAGE
-- Cible      : ARTHUS.SINISTRE_FORCAGE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SINISTRE_FORCAGE FOR ARTHUS.SINISTRE_FORCAGE;
