-- Synonyme PUBLIC : SNTR_DOSSIER_ANNUL
-- Cible      : ARTHUS.SNTR_DOSSIER_ANNUL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM SNTR_DOSSIER_ANNUL FOR ARTHUS.SNTR_DOSSIER_ANNUL;
