-- Synonyme PUBLIC : TRAV_LECTURE_FICHIER
-- Cible      : ARTHUS.TRAV_LECTURE_FICHIER
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM TRAV_LECTURE_FICHIER FOR ARTHUS.TRAV_LECTURE_FICHIER;
