-- Synonyme PUBLIC : TRAV_PRELEVEMENT
-- Cible      : ARTHUS.TRAV_PRELEVEMENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM TRAV_PRELEVEMENT FOR ARTHUS.TRAV_PRELEVEMENT;
