-- Synonyme PUBLIC : VIR_PORTE_FORCAGE
-- Cible      : ARTHUS.VIR_PORTE_FORCAGE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM VIR_PORTE_FORCAGE FOR ARTHUS.VIR_PORTE_FORCAGE;
