-- Synonyme PUBLIC : ZONES_INCLUSIONS
-- Cible      : ARTHUS.ZONES_INCLUSIONS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM ZONES_INCLUSIONS FOR ARTHUS.ZONES_INCLUSIONS;
