CREATE procedure ARTHUS.charge_adhecoll ( a_numgar in number,
					   t_donnee out pk_texte.donnee)
is
BEGIN
      Select	numgar,
		refcie,
		d2e(datsous),
		d2e(dateff),
		substr(pk_libelle.f_lib('TYPG',typgar),1,15),
		substr(pk_libelle.f_lib('FRAC',fract),1,15),
		renouv,
		substr(pk_libelle.f_lib('ET_CONT',pk_histo_contrat.f_sel_etat(a_numgar,sysdate)),1,15),
		substr(pk_libelle.f_lib('TYPQ',typequit),1,15),
		numquerable,
		to_char(eche_anniv,'dd/mm'),
		revision,
		refcie_chapeau,
		substr(pk_libelle.f_lib('TYPC',type_calc),1,15),
		substr(pk_libelle.f_lib('NATC',nat_calc),1,15),
		substr(pk_libelle.f_lib('GESPR',gest_prest),1,15),
                --substr(pk_libelle.f_lib('GESRP',gest_prest),1,15),
		substr(pk_libelle.f_lib('GESCO',gest_cotis),1,15),
		substr(pk_libelle.f_lib('MREGL',mregl),1,15),
		substr(pk_libelle.f_lib('COLLEGE',college),1,25),
		substr(pk_libelle.f_lib('TYP_CONT',type_contrat),1,15),
		substr(pk_libelle.f_lib('TYPE_TERME',type_terme),1,15),
		substr(pk_libelle.f_lib('ARRONDI',arrondi),1,15),
		pk_personne.f_nom( delegataire, 32, 1 ),
		pk_personne.f_nom( deleg_prest, 32, 1 ),
                delai,
                numgar_ref

	Into	t_donnee(1),
		t_donnee(2),
		t_donnee(3),
		t_donnee(4),
		t_donnee(5),
		t_donnee(6),
		t_donnee(7),
		t_donnee(8),
		t_donnee(9),
		t_donnee(10),
		t_donnee(11),
		t_donnee(12),
		t_donnee(13),
		t_donnee(14),
		t_donnee(15),
		t_donnee(16),
		t_donnee(17),
		t_donnee(18),
		t_donnee(19),
		t_donnee(21),
		t_donnee(22),
		t_donnee(23),
		t_donnee(24),
		t_donnee(25),
		t_donnee(26),
                t_donnee(27)
	From	contrat
	Where 	numgar=a_numgar;
END;
/
