CREATE PROCEDURE ARTHUS.MAJ_Applications IS

CURSOR C1 IS
	SELECT DISTINCT APPLICATIONS.CODAPLI, APPLICATIONS.NOM, APPLICATIONS.TYPE, APPLICATIONS.FONCTION,
	APPLICATIONS.SEC, APPLICATIONS.CLE1, APPLICATIONS.CLE2
FROM APPLICATIONS
ORDER BY CODAPLI, FONCTION;

R1 C1%ROWTYPE;

BEGIN
	OPEN C1;
	LOOP
		FETCH C1 INTO R1;
		EXIT WHEN C1%NOTFOUND;
		-- DELETE FROM APPLICATIONS WHERE CODAPLI = R1.CODAPLI AND FONCTION = R1.FONCTION;
		INSERT INTO APPLICATIONS (CODAPLI, NOM, TYPE, FONCTION, SEC, CLE1, CLE2, CREATION)
		VALUES (R1.CODAPLI, R1.NOM, R1.TYPE, R1.FONCTION, R1.SEC, R1.CLE1, R1.CLE2, Sysdate);
	END LOOP;
	CLOSE C1;
END;
/
