CREATE PROCEDURE ARTHUS.p_annul_sinistre (i_numsin IN sinistre.numsin%TYPE) IS
  next_numsin sinistre.numsin%TYPE;
BEGIN
  select numsin.nextval
  into next_numsin
  from dual;

  insert into sinistre (CODFRAIS,
                        NUMGAR,
                        NUMINDIV,
                        DATSIN,
                        mtprest,
                        mtremb,
                        mtfrais,
                        autrb,
                        mtfran,
                        mtmax,
                        mtreel,
                        nbacte,
                        datsai,
                        SENS,
                        NUMASSU,
                        NUMBENE,
                        TYPBENE,
                        numdec,
                        numsin,
                        username,
                        numannul,
                        flagam,
                        NUMPOPU,
                        NUMFOR,
                        NUM_FACT,
                        NUMMATH,
                        NUMPC,
                        X,
                        IDADHESION,
                        FLAG_REGIME,
                        MONNAIE,
                        EDTDCPT)
                (select CODFRAIS,
                        NUMGAR,
                        NUMINDIV,
                        DATSIN,
                        mtprest*-1,
                        mtremb*-1,
                        mtfrais*-1,
                        autrb*-1,
                        mtfran*-1,
                        mtmax*-1,
                        mtreel*-1,
                        nbacte*-1,
                        trunc(sysdate),
                        SENS,
                        NUMASSU,
                        NUMBENE,
                        TYPBENE,
                        0,
                        next_numsin,
                        f_numutil,
                        numsin,
                        'a',
                        NUMPOPU,
                        NUMFOR,
                        NUM_FACT,
                        NUMMATH,
                        NUMPC,
                        X,
                        IDADHESION,
                        FLAG_REGIME,
                        MONNAIE,
                        EDTDCPT
                from sinistre
                where numsin = i_numsin);

   insert into sinistre_dev (NUMSIN,DEV_CT,DEV_IN,DEV_OUT,MTFRAIS_CT,MTFRAIS_IN,
                      MTFRAIS_OUT,MTPREST_CT,MTPREST_IN,MTPREST_OUT,MTREMB_CT,
                      MTREMB_IN,MTREMB_OUT,MTREEL_CT,MTREEL_IN,MTREEL_OUT,
                      AUTRB_CT,AUTRB_IN,AUTRB_OUT,NUMDEC,NUMINDIV)
   select next_numsin,
          DEV_CT,
          DEV_IN,
          DEV_OUT,
          MTFRAIS_CT*-1,
          MTFRAIS_IN*-1,
          MTFRAIS_OUT*-1,
          MTPREST_CT*-1,
          MTPREST_IN*-1,
          MTPREST_OUT*-1,
          MTREMB_CT*-1,
          MTREMB_IN*-1,
          MTREMB_OUT*-1,
          MTREEL_CT*-1,
          MTREEL_IN*-1,
          MTREEL_OUT*-1,
          AUTRB_CT*-1,
          AUTRB_IN*-1,
          AUTRB_OUT*-1,
          0,
          NUMINDIV
   from sinistre_dev
   where numsin = i_numsin;

END p_annul_sinistre;
/
