CREATE procedure ARTHUS.p_fichier IS

--
VIREMENT		UTL_FILE.FILE_TYPE;
--
Begin
--
    DBMS_OUTPUT.PUT_LINE('DEBUT');
--
	VIREMENT:=UTL_FILE.FOPEN('EXPORT','fichier.txt','W');
--
    DBMS_OUTPUT.PUT_LINE('OUVERTURE OK');
--

	UTL_FILE.PUT_LINE(VIREMENT,'tata test titi');
--
    DBMS_OUTPUT.PUT_LINE('ECRITURE OK');
--

	UTL_FILE.FCLOSE(VIREMENT);

--
    DBMS_OUTPUT.PUT_LINE('FERMETURE OK');
--

EXCEPTION
  WHEN UTL_FILE.INTERNAL_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('UTL_FILE.INTERNAL_ERROR');

  WHEN UTL_FILE.INVALID_FILEHANDLE THEN
    DBMS_OUTPUT.PUT_LINE('UTL_FILE.INVALID_FILEHANDLE');

  WHEN UTL_FILE.INVALID_MODE THEN
    DBMS_OUTPUT.PUT_LINE('UTL_FILE.INVALID_MODE');

  WHEN UTL_FILE.INVALID_OPERATION THEN
    DBMS_OUTPUT.PUT_LINE('UTL_FILE.INVALID_OPERATION');

  WHEN UTL_FILE.INVALID_PATH THEN
    DBMS_OUTPUT.PUT_LINE('UTL_FILE.INVALID_PATH');

  WHEN UTL_FILE.READ_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('UTL_FILE.READ_ERROR');

  WHEN UTL_FILE.WRITE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('UTL_FILE.WRITE_ERROR');

  WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('UTL_FILE.VALUE_ERROR');

--
End;
/
