CREATE PROCEDURE ARTHUS.P_INSERT_TRAV_SAISIE(  P_TRAV_SAISIE  IN TRAV_SAISIE%ROWTYPE)
IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

  INSERT INTO TRAV_SAISIE VALUES P_TRAV_SAISIE;
  COMMIT;
END P_INSERT_TRAV_SAISIE;
/
