CREATE PROCEDURE ARTHUS.P_Trt_Rel_Cpte IS

	CURSOR C_RC IS
		SELECT ALL RELEVE_COMPTE.NUM_ECRITURE, RELEVE_COMPTE.MONTANT_BQUE
		FROM RELEVE_COMPTE;
	R_RC C_RC%ROWTYPE;

BEGIN
  OPEN C_RC;
  LOOP
  	FETCH C_RC INTO R_RC;
  	EXIT WHEN C_RC%NOTFOUND;
  	P_COMPUTE_EC (R_RC.MONTANT_BQUE, R_RC.NUM_ECRITURE);
  END LOOP;
  CLOSE C_RC;
  --
  UPDATE RELEVE_COMPTE
  		SET VALIDE = 'O';
  --
  COMMIT;
  --
  EXCEPTION
  	WHEN OTHERS THEN ROLLBACK;
  END;
/
