-- Synonyme PUBLIC : PK_AFFICHE_TEXTE
-- Cible      : ARTHUS.PK_AFFICHE_TEXTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_AFFICHE_TEXTE FOR ARTHUS.PK_AFFICHE_TEXTE;
