-- Synonyme PUBLIC : PK_CALCUL_DOSSIER
-- Cible      : ARTHUS.PK_CALCUL_DOSSIER
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_CALCUL_DOSSIER FOR ARTHUS.PK_CALCUL_DOSSIER;
