-- Synonyme PUBLIC : PK_CONVERT_TO_XLSX
-- Cible      : ARTHUS.PK_CONVERT_TO_XLSX
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_CONVERT_TO_XLSX FOR ARTHUS.PK_CONVERT_TO_XLSX;
