-- Synonyme PUBLIC : PK_CORRIGE_TEXTE
-- Cible      : ARTHUS.PK_CORRIGE_TEXTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_CORRIGE_TEXTE FOR ARTHUS.PK_CORRIGE_TEXTE;
