-- Synonyme PUBLIC : PK_DEV_VR01B_SEPA
-- Cible      : ARTHUS.PK_DEV_VR01B_SEPA
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_DEV_VR01B_SEPA FOR ARTHUS.PK_DEV_VR01B_SEPA;
