-- Synonyme PUBLIC : PK_EXTRACTION_AUTO
-- Cible      : ARTHUS.PK_EXTRACTION_AUTO
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_EXTRACTION_AUTO FOR ARTHUS.PK_EXTRACTION_AUTO;
