-- Synonyme PUBLIC : PK_EXTRACTION_CLI
-- Cible      : ARTHUS.PK_EXTRACTION_CLI
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_EXTRACTION_CLI FOR ARTHUS.PK_EXTRACTION_CLI;
