-- Synonyme PUBLIC : PK_EXPORT_CRM_DSN
-- Cible      : ARTHUS.PK_EXPORT_CRM_DSN
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_EXPORT_CRM_DSN FOR ARTHUS.PK_EXPORT_CRM_DSN;
