-- Synonyme PUBLIC : PK_FRAIS_RESEAUX
-- Cible      : ARTHUS.PK_FRAIS_RESEAUX
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_FRAIS_RESEAUX FOR ARTHUS.PK_FRAIS_RESEAUX;
