-- Synonyme PUBLIC : PK_GEST_COTIS_AF06T
-- Cible      : ARTHUS.PK_GEST_COTIS_AF06T
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_GEST_COTIS_AF06T FOR ARTHUS.PK_GEST_COTIS_AF06T;
