-- Synonyme PUBLIC : PK_HISTO_CONTRAT
-- Cible      : ARTHUS.PK_HISTO_CONTRAT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_HISTO_CONTRAT FOR ARTHUS.PK_HISTO_CONTRAT;
