-- Synonyme PUBLIC : PK_INS_HISTO_EXPORT
-- Cible      : ARTHUS.PK_INS_HISTO_EXPORT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_INS_HISTO_EXPORT FOR ARTHUS.PK_INS_HISTO_EXPORT;
