-- Synonyme PUBLIC : PK_IMPORT_VIREMENT
-- Cible      : ARTHUS.PK_IMPORT_VIREMENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_IMPORT_VIREMENT FOR ARTHUS.PK_IMPORT_VIREMENT;
