-- Synonyme PUBLIC : PK_IMPORT_AFFIL_DSN
-- Cible      : ARTHUS.PK_IMPORT_AFFIL_DSN
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_IMPORT_AFFIL_DSN FOR ARTHUS.PK_IMPORT_AFFIL_DSN;
