-- Synonyme PUBLIC : PK_MAIL_RATTRAPE
-- Cible      : ARTHUS.PK_MAIL_RATTRAPE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_MAIL_RATTRAPE FOR ARTHUS.PK_MAIL_RATTRAPE;
