-- Synonyme PUBLIC : PK_PRDG_DYNAMIC_CURSOR
-- Cible      : ARTHUS.PK_PRDG_DYNAMIC_CURSOR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_PRDG_DYNAMIC_CURSOR FOR ARTHUS.PK_PRDG_DYNAMIC_CURSOR;
