-- Synonyme PUBLIC : PK_REQUETE_ENGLOB
-- Cible      : ARTHUS.PK_REQUETE_ENGLOB
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_REQUETE_ENGLOB FOR ARTHUS.PK_REQUETE_ENGLOB;
