-- Synonyme PUBLIC : PK_SANTECLAIR_FACTURATION
-- Cible      : ARTHUS.PK_SANTECLAIR_FACTURATION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_SANTECLAIR_FACTURATION FOR ARTHUS.PK_SANTECLAIR_FACTURATION;
