-- Synonyme PUBLIC : PK_SPSANTE_FACTURATION
-- Cible      : ARTHUS.PK_SPSANTE_FACTURATION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_SPSANTE_FACTURATION FOR ARTHUS.PK_SPSANTE_FACTURATION;
