-- Synonyme PUBLIC : PK_WS_WEB_MAJ_BACK
-- Cible      : ARTHUS.PK_WS_WEB_MAJ_BACK
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_WS_WEB_MAJ_BACK FOR ARTHUS.PK_WS_WEB_MAJ_BACK;
