-- Synonyme PUBLIC : PK_WS_WEB_MAJ_FRONT
-- Cible      : ARTHUS.PK_WS_WEB_MAJ_FRONT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_WS_WEB_MAJ_FRONT FOR ARTHUS.PK_WS_WEB_MAJ_FRONT;
