-- Synonyme PUBLIC : PK_WS_CLEAN_DEMANDE
-- Cible      : ARTHUS.PK_WS_CLEAN_DEMANDE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_WS_CLEAN_DEMANDE FOR ARTHUS.PK_WS_CLEAN_DEMANDE;
