-- Synonyme PUBLIC : PK_WS_BACK_SANTECLAIR
-- Cible      : ARTHUS.PK_WS_BACK_SANTECLAIR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM PK_WS_BACK_SANTECLAIR FOR ARTHUS.PK_WS_BACK_SANTECLAIR;
