CREATE FUNCTION ARTHUS.F_Dcpt_RoleDest (I_NUMSIN IN Number)
    RETURN NUMBER
IS
--
 CURSOR C_Sntr IS
	SELECT  nvl(COURR_DEST.TYPE, 15) RoleDest
	FROM SINISTRE, SNTR_DOSSIER, COURR_DEST
	WHERE SINISTRE.NUMSIN=I_NUMSIN
	AND SINISTRE.NUMSIN=SNTR_DOSSIER.NUMSIN_SNTR(+)
	AND SNTR_DOSSIER.NUM_DOSSIER=COURR_DEST.ID(+)
	AND COURR_DEST.CODE(+)=28
	AND COURR_DEST.VALIDE(+)=1;

 R_sntr C_Sntr%ROWTYPE;

 O_RoleDest number(3);
--
BEGIN


	    OPEN C_Sntr;
	    FETCH C_Sntr INTO R_sntr;
	    IF C_Sntr%FOUND THEN
			O_RoleDest:=R_sntr.RoleDest;
	    Else
	    	O_RoleDest:=15;
	    end if;

	    CLOSE C_Sntr;

	    RETURN(O_RoleDest);

END;
