CREATE FUNCTION ARTHUS.F_FIND_PLV(i_codfrais NTFRS_PLV.codfrais%TYPE, i_BR NTFRS_PLV.BASEREMB%TYPE, i_date DATE) RETURN NUMBER IS
  loc_PLC NTFRS_PLV.PLV%TYPE;
BEGIN
	SELECT PLV INTO loc_PLC
	FROM NTFRS_PLV
	WHERE codfrais = i_codfrais
	AND BASEREMB =i_BR
	AND i_date BETWEEN DATAPPLI AND NVL(DATPER,i_date) ;

	RETURN loc_PLC;
EXCEPTION
	WHEN NO_DATA_FOUND THEN RETURN NULL;
	WHEN OTHERS THEN RETURN -1;

END F_FIND_PLV;
