CREATE FUNCTION ARTHUS.F_IDHISTO_RAPPEL(i_idrappel IN number) return number  AS
retour number;
BEGIN
  BEGIN
  SELECT MAX(IDHISTORAPPEL) INTO retour FROM HISTO_RAPPEL h2 
  WHERE h2.IDRAPPEL = i_idrappel;
  return retour;
  EXCEPTION WHEN NO_DATA_FOUND THEN
  RETURN NULL;
  END;

END F_IDHISTO_RAPPEL;
