CREATE function ARTHUS.f_idcotis(
			A_Type 	IN NUMBER,
			A_Clef	IN NUMBER)
	RETURN NUMBER
	AS
		Loc_Retour	 number default 0;
		CURSOR C1 IS
			SELECT ALL
				QTTC_GLOBAL.IDADHESION,
				QTTC_GLOBAL.NUMGAR,
				QTTC_GLOBAL.NUMQUERABLE
			FROM QTTC_GLOBAL
			WHERE QTTC_GLOBAL.NUMQUIT = A_Clef;
		R1 C1%ROWTYPE;
BEGIN
	OPEN C1;
	FETCH C1 INTO R1;
	IF A_Type = 1 AND R1.IDADHESION = 0 THEN
		Loc_Retour := R1.NUMGAR;
	ELSIF
		A_Type = 1 AND R1.IDADHESION <> 0 THEN
		Loc_Retour := R1.IDADHESION;
	ELSIF
		A_Type = 2 THEN
		Loc_Retour := R1.NUMQUERABLE;
	ELSE
		Loc_Retour := R1.NUMGAR;
	END IF;
	CLOSE C1;
	RETURN(Loc_Retour);
	EXCEPTION
		WHEN OTHERS THEN RETURN(0);
		CLOSE C1;
END f_idcotis;
