CREATE FUNCTION ARTHUS.F_idadhesion_dcpt_sante (I_NUMDEC   IN NUMBER)
	RETURN NUMBER IS
	CURSOR CUR_SNTR IS
		SELECT DISTINCT IDADHESION FROM SNTR
		           WHERE SNTR.NUMDEC = I_NUMDEC;
	REC_SNTR CUR_SNTR%ROWTYPE;
BEGIN
	OPEN CUR_SNTR;
	FETCH CUR_SNTR INTO REC_SNTR;
	IF CUR_SNTR%NOTFOUND THEN
		RETURN(0);
	ELSE
		RETURN(REC_SNTR.IDADHESION);
	END IF;
	--
	CLOSE CUR_SNTR;
EXCEPTION
	WHEN OTHERS THEN RETURN(0);
END;
