CREATE FUNCTION ARTHUS.F_INFO_REG_ASSU (I_NUMINDIV   IN INDVS.NUMINDIV%TYPE)
                          RETURN NUMBER IS
   CURSOR CUR_INDVS IS
       SELECT ALL COUNT(*)
         FROM INDVS, ADHESION
        WHERE (INDVS.NUMINDIV = I_NUMINDIV
          AND (INDVS.REGIME IS NULL
               OR INDVS.ORGBASE IS NULL
               OR INDVS.MATORG IS NULL
               OR INDVS.CLESS IS NULL
               OR INDVS.NATUR IS NULL
               OR ADHESION.NUMORG IS NULL))
          AND (INDVS.NUMASSU = ADHESION.NUMINDIV) ;

	L_NUMBER  NUMBER := 0;
BEGIN
    OPEN CUR_INDVS;
    FETCH CUR_INDVS INTO L_number;
    CLOSE CUR_INDVS;
    RETURN(L_NUMBER);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
