CREATE FUNCTION ARTHUS.F_numorg_LD (I_CODFRAIS IN VARCHAR2,
					I_NUMINDIV IN NUMBER,
					I_DATSIN IN DATE DEFAULT SYSDATE)
RETURN  NUMBER
IS
  CURSOR CUR_COUVERTURE IS
	SELECT ALL V_CVRT.IDADHESION, V_CVRT.NUMGAR, V_CVRT.NUMFOR,
		 V_CVRT.NUMINDIV, V_CVRT.NOMGAR, V_CVRT.DATAPLI, V_CVRT.DATPER,
		 V_CVRT.RANG, V_CVRT.ETAT, V_CVRT.MOTIF, V_CVRT.NUMGRPGAR
	FROM V_CVRT
	WHERE (V_CVRT.FLAG_REGIME = 'O'
	AND V_CVRT.TYPFOR = 1
	AND V_CVRT.NUMINDIV = I_NUMINDIV
	AND I_DATSIN BETWEEN V_CVRT.DATAPLI AND NVL(I_DATSIN, V_CVRT.DATPER))
	ORDER BY DATAPLI DESC;

  REC_COUVERTURE CUR_COUVERTURE%ROWTYPE;
--
  CURSOR CUR_CALCUL
        (CONTRAT IN NUMBER, GARANTIE IN NUMBER) IS
	SELECT ALL CALCUL.NUMFOR
	FROM CALCUL, SINISTRE_SANTE
	WHERE (CALCUL.NUMFOR = pk_qttc.F_sel_Numfor (CONTRAT, GARANTIE)
	 AND I_DATSIN BETWEEN CALCUL.DATAPLI AND NVL(I_DATSIN, CALCUL.DATPER)
	 AND CALCUL.DATAPLI < NVL(CALCUL.DATPER, (CALCUL.DATAPLI+1)))
	 AND (I_CODFRAIS = CALCUL.CODFRAIS);

  REC_CALCUL CUR_CALCUL%ROWTYPE;
--
  CURSOR CUR_FORMULE
	(CONTRAT IN NUMBER, GARANTIE IN NUMBER) IS
	SELECT ALL FRMLS.NUMASS
	FROM FRMLS
	WHERE FRMLS.NUMFOR = pk_qttc.F_sel_Numfor (CONTRAT, GARANTIE);
  REC_FORMULE CUR_FORMULE%ROWTYPE;
--
  LOC_ORGANISME NUMBER := NULL;

BEGIN
  OPEN CUR_COUVERTURE;
  LOOP
     FETCH CUR_COUVERTURE INTO REC_COUVERTURE;
     EXIT WHEN CUR_COUVERTURE%NOTFOUND OR LOC_ORGANISME IS NOT NULL;
     OPEN CUR_CALCUL (REC_COUVERTURE.NUMGAR, REC_COUVERTURE.NUMFOR);
     FETCH CUR_CALCUL INTO REC_CALCUL;
     IF CUR_CALCUL%FOUND
	THEN
	OPEN CUR_FORMULE (REC_COUVERTURE.NUMGAR, REC_COUVERTURE.NUMFOR);
	FETCH CUR_FORMULE INTO REC_FORMULE;
	IF CUR_FORMULE%FOUND
	   THEN
	   LOC_ORGANISME := REC_FORMULE.NUMASS;
	ELSE
	   LOC_ORGANISME := -1;
	END IF;
	CLOSE CUR_FORMULE;
     ELSE
	NULL;
     END IF;
     CLOSE CUR_CALCUL;
  END LOOP;
  CLOSE CUR_COUVERTURE;
  RETURN(LOC_ORGANISME);
END;
