CREATE FUNCTION ARTHUS.F_NUMGAR_INUSE (I_NUMGAR   IN ADHE_CNTRT.NUMGAR%TYPE)
	RETURN NUMBER IS
		CURSOR CUR_ACG IS
				SELECT 1
 					FROM ADHE_COLL_GAR
				 WHERE (ADHE_COLL_GAR.NUMGAR_REF = I_NUMGAR);
		REC_ACG CUR_ACG%ROWTYPE;

		CURSOR CUR_AC IS
				SELECT 1
 					FROM ADHE_CNTRT
				 WHERE (PK_QTTC.F_SEL_NUMGAR(ADHE_CNTRT.NUMGAR) = I_NUMGAR);
		REC_AC CUR_AC%ROWTYPE;

	 	CURSOR CUR_QG IS
				SELECT 1
 					FROM  QTTC_GLOBAL
				 WHERE (PK_QTTC.F_SEL_NUMGAR (QTTC_GLOBAL.NUMGAR) = I_NUMGAR);
    REC_QG CUR_QG%ROWTYPE;
BEGIN
	OPEN CUR_ACG;
	FETCH CUR_ACG INTO REC_ACG;
	IF CUR_ACG%NOTFOUND THEN
		CLOSE CUR_ACG;
		OPEN CUR_AC;
		FETCH CUR_AC INTO REC_AC;
		IF CUR_AC%NOTFOUND THEN
			CLOSE CUR_AC;
  		OPEN CUR_QG;
			FETCH CUR_QG INTO REC_QG;
			IF CUR_QG%NOTFOUND THEN
				RETURN (0);
			ELSE
				RETURN (1);
			END IF;
			CLOSE CUR_QG;
		ELSE
			RETURN (1);
		END IF;
		CLOSE CUR_AC;
	ELSE
		RETURN (1);
	END IF;
	CLOSE CUR_ACG;
	--
	EXCEPTION
		WHEN TOO_MANY_ROWS THEN RETURN(1);
		WHEN OTHERS THEN RETURN(0);
END;
