CREATE FUNCTION ARTHUS.F_SNTR_PREV_DEBUT(a_NoSin IN NUMBER) RETURN DATE
AS
  d_Result DATE;
BEGIN
  BEGIN
    -- Date de Fin du Sinistre
    SELECT max(debut) INTO d_Result
      FROM HISTO_SNTR_PREV
     WHERE NOSIN = a_NoSin AND ETAT = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
  END;
  RETURN TRUNC(d_Result);
EXCEPTION
   WHEN OTHERS THEN RETURN NULL;
END;
