CREATE FUNCTION ARTHUS.gs19_xit (
   SID             BINARY_INTEGER,
   sntrnumlig      BINARY_INTEGER,
   sntrcodfrais    VARCHAR2,
   sntrdatsin      VARCHAR2,
   sntrcodpays     BINARY_INTEGER,
   sntrtaux        DOUBLE PRECISION,
   sntrmtremb      DOUBLE PRECISION,
   sntrbaseremb    DOUBLE PRECISION,  -- Ajout pour le projet de la CCAM
   sntrmtfrais     DOUBLE PRECISION,
   sntrautrb       DOUBLE PRECISION,
   sntrnumindiv    BINARY_INTEGER,
   sntrcodmon      BINARY_INTEGER,
   sntrquantite    DOUBLE PRECISION,
   sntrcoeff       DOUBLE PRECISION,
   sntrdatsai      VARCHAR2,
   sntrnumassu     BINARY_INTEGER,
   sntrnumbene     BINARY_INTEGER,
   entetetypbene   BINARY_INTEGER,
   entetenumpc     BINARY_INTEGER,
   enteteref       VARCHAR2,
   numdossier      VARCHAR2,
   numligdossier   BINARY_INTEGER,
   devisoblg       VARCHAR2,
   TEST            VARCHAR2,
   nom             VARCHAR2,
   pwd             VARCHAR2,
   frcg            BINARY_INTEGER,
   frcg1           BINARY_INTEGER,
   frcg2           BINARY_INTEGER,
   frcg3           BINARY_INTEGER,
   frcg4           BINARY_INTEGER,
   frcg5           BINARY_INTEGER,
   frcg6           BINARY_INTEGER,
   frcg7           BINARY_INTEGER,
   frcg8           BINARY_INTEGER,
   frcg9           BINARY_INTEGER,
   frcg10          BINARY_INTEGER,
   sntrpdsqls      BINARY_INTEGER,
   sntrracmon      DOUBLE PRECISION,
   sntrspe_exe     DOUBLE PRECISION,
   cas             VARCHAR2,
   derog           VARCHAR2
)
   RETURN VARCHAR2
AS
EXTERNAL
   LIBRARY extprocgs19_xit
   NAME "gs19_xit"
   LANGUAGE c
   PARAMETERS (
      SID INT,
      sntrnumlig INT,
      sntrcodfrais STRING,
      sntrdatsin STRING,
      sntrcodpays INT,
      sntrtaux DOUBLE,
      sntrmtremb DOUBLE,
      sntrmtremb INDICATOR,
      sntrbaseremb DOUBLE,
      sntrbaseremb INDICATOR,
      sntrmtfrais DOUBLE,
      sntrautrb DOUBLE,
      sntrautrb INDICATOR,
      sntrnumindiv INT,
      sntrcodmon INT,
      sntrcodmon INDICATOR,
      sntrquantite DOUBLE,
      sntrcoeff DOUBLE,
      sntrdatsai STRING,
      sntrnumassu INT,
      sntrnumbene INT,
      entetetypbene INT,
      entetenumpc INT,
      enteteref STRING,
      enteteref INDICATOR,
      numdossier STRING,
      numligdossier INT,
      devisoblg STRING,
      TEST STRING,
      nom STRING,
      pwd STRING,
      frcg INT,
      frcg1 INT,
      frcg2 INT,
      frcg3 INT,
      frcg4 INT,
      frcg5 INT,
      frcg6 INT,
      frcg7 INT,
      frcg8 INT,
      frcg9 INT,
      frcg10 INT,
      sntrpdsqls INT,
      sntrracmon DOUBLE,
      sntrspe_exe DOUBLE,
      cas STRING,
	    cas INDICATOR,
      derog STRING,
	    derog INDICATOR,
      RETURN STRING
   );
