CREATE FORCE VIEW ARTHUS.ACTE AS
select  "CODFRAIS","LIBELLE","TYPE","RUBRIQUE","PRIXMIN","PRIXMAX","REMBTSSMIN",
"REMBTSSMAX","CNVTN","NOMBRE","SEL", "TYPE_ACTE" from ntfrs where type=2
GO
CREATE OR REPLACE PUBLIC SYNONYM ACTE FOR ARTHUS.ACTE
