CREATE FORCE VIEW ARTHUS.POPULATION AS
select numfor numpopu,datapli,datper,libelle,numfor,'' minanc,'' maxanc,type,'' numprod,numgar from gar_cntrt
GO
CREATE OR REPLACE SYNONYM ARTHUS.POPU FOR ARTHUS.POPULATION

GO
CREATE OR REPLACE PUBLIC SYNONYM POPU FOR ARTHUS.POPULATION

GO
CREATE OR REPLACE PUBLIC SYNONYM POPULATION FOR ARTHUS.POPULATION
