CREATE FORCE VIEW ARTHUS.RBRQ AS
SELECT "CODFRAIS", "LIBELLE", "TYPE", "RUBRIQUE", "PRIXMIN", "PRIXMAX",
          "REMBTSSMIN", "REMBTSSMAX", "CNVTN", "NOMBRE", "SEL", "TYPE_ACTE"
     FROM ntfrs
    WHERE TYPE = 1
GO
CREATE OR REPLACE PUBLIC SYNONYM RBRQ FOR ARTHUS.RBRQ
