CREATE FORCE VIEW ARTHUS.V_AFFECTATION_CPTA AS
SELECT CODOPE,NUMAFFEC,NUMDECAISMT,MONTANT,DATAFFEC,
          NUMCLI,MONTANT_D,MONNAIE,MONNAIE_D,IDCOMPTA,
          NBFEUILLE,MONTANT_EC,TYPE_EC,SENS_EC,DEVISE_EC,
          MONTANT_CT,DEVISE_CT
     FROM affectation
    WHERE affectation.numdecaismt IS NOT NULL
UNION ALL
   SELECT CODOPE,NUMAFFEC,NUMDECAISMT,MONTANT,DATAFFEC,
          NUMCLI,MONTANT_D,MONNAIE,MONNAIE_D,IDCOMPTA_INIT IDCOMPTA,
          NBFEUILLE,MONTANT_EC,TYPE_EC,SENS_EC,DEVISE_EC,
          MONTANT_CT,DEVISE_CT
     FROM affectation_annul
    WHERE NOT EXISTS (
          SELECT 1
            FROM affectation
           WHERE affectation.numaffec = affectation_annul.numaffec
             AND affectation.codope   = affectation_annul.codope
             AND affectation.numdecaismt IS NOT NULL )
GO
CREATE OR REPLACE PUBLIC SYNONYM V_AFFECTATION_CPTA FOR ARTHUS.V_AFFECTATION_CPTA
