CREATE FORCE VIEW ARTHUS.V_ARRET AS
SELECT IDARRET, NOSIN, DEBUT, LEAST(NVL(F_SNTR_PREV_FIN(NOSIN), FIN), FIN) FIN_PREV, TRAITE, CONTINU,
TYPE, PERIODE, CREATION, MAJ, NUMUTIL, BASE_REGIME,
BASE_AUTRE, BASE_CALCUL, RECEPTION
FROM ARRET
WHERE DEBUT<=NVL(F_SNTR_PREV_FIN(NOSIN), DEBUT)
GO
CREATE OR REPLACE PUBLIC SYNONYM V_ARRET FOR ARTHUS.V_ARRET
