CREATE FORCE VIEW ARTHUS.V_AVT2 AS
SELECT  AV.NUMTR        NUMTR,
        AV.NUMAV        NUMAV,
        AV.LIBINTAV     LIBINTAV,
        AV.DATEFFAV     DATEFFAV,
        AV.DATFINAV     DATFINAV
FROM    AVENANT AV
WHERE   AV.VALIDEAV = 'O'
AND     AV.TYPAV = 2
GO
CREATE OR REPLACE PUBLIC SYNONYM V_AVT2 FOR ARTHUS.V_AVT2
