CREATE FORCE VIEW ARTHUS.V_BA02 AS
select	typ_edition.editid,
		typ_edition.batchid,
		typ_edition.editlib,
		typ_edition.nb_char,
		typ_edition.nb_ex,
		typ_edition.impid,
		typ_edition.papid,
		typ_edition.imp_req,
		typ_edition.pap_req,
		typ_edition.purge,
		typ_edition.nb_pdg,
		typ_batch.batchlib,
		typ_batch.immediat,
		typ_batch.priorite,
		typ_batch.nb_maxi,
		typ_batch.periode,
		typ_batch.ordre,
		typ_batch.arret,
		typ_batch.userid,
		typ_batch.simultane,
		typ_batch.codapli,
		typ_batch.param,
		typ_batch.ressource,
		typ_batch.seqid,
		prdct.libelle per,
		param_batch.lib1,     param_batch.typ1,     param_batch.ctrl1,
		param_batch.valdeb1,  param_batch.valfin1,  param_batch.mnemo1,
		param_batch.lib2,     param_batch.typ2,     param_batch.ctrl2,
		param_batch.valdeb2,  param_batch.valfin2,  param_batch.mnemo2,
		param_batch.lib3,     param_batch.typ3,     param_batch.ctrl3,
		param_batch.valdeb3,  param_batch.valfin3,  param_batch.mnemo3,
		param_batch.lib4,     param_batch.typ4,     param_batch.ctrl4,
		param_batch.valdeb4,  param_batch.valfin4,  param_batch.mnemo4,
		param_batch.lib5,     param_batch.typ5,     param_batch.ctrl5,
		param_batch.valdeb5,  param_batch.valfin5,  param_batch.mnemo5,
		param_batch.lib6,     param_batch.typ6,     param_batch.ctrl6,
		param_batch.valdeb6,  param_batch.valfin6,  param_batch.mnemo6,
		param_batch.lib7,     param_batch.typ7,     param_batch.ctrl7,
		param_batch.valdeb7,  param_batch.valfin7,  param_batch.mnemo7,
		param_batch.lib8,     param_batch.typ8,     param_batch.ctrl8,
		param_batch.valdeb8,  param_batch.valfin8,  param_batch.mnemo8,
		param_batch.lib9,     param_batch.typ9,     param_batch.ctrl9,
		param_batch.valdeb9,  param_batch.valfin9,  param_batch.mnemo9,
		param_batch.lib10,    param_batch.typ10,    param_batch.ctrl10,
		param_batch.valdeb10, param_batch.valfin10, param_batch.mnemo10,
		param_batch.param1,
		param_batch.param2,
		param_batch.param3,
		param_batch.param4,
		param_batch.param5
	from	typ_edition, typ_batch, param_batch, libelle prdct
	where 	prdct.mnemo		=	'PRDCT'
	and	typ_batch.periode	=	prdct.code
	and	typ_edition.batchid	=	typ_batch.batchid
	and	param_batch.numbatch(+)	=	typ_batch.batchid
GO
CREATE OR REPLACE PUBLIC SYNONYM V_BA02 FOR ARTHUS.V_BA02
