CREATE FORCE VIEW ARTHUS.V_BENE_JUSTIF19 AS
SELECT TO_NUMBER(SINISTRE_PORTE.NUMREMISE || TO_CHAR(SINISTRE_PORTE.NUMSIN, 'FM000000000')) NUMDOSSIER,
       SINISTRE_PORTE.NUMASSU,
       NULL NUMASSU_RC,
       SINISTRE_PORTE.NUMINDIV,
       SINISTRE_PORTE.NUMREMISE,
       19 CODE,
       NULL DATE_JUSTIF,
       19 TYPE_PIECE
  FROM ARTHUS.SINISTRE_PORTE
 WHERE SINISTRE_PORTE.NUMPORTE = 1
   AND SINISTRE_PORTE.NUMREMISE IN
       (SELECT PORTE_REMISE.NUMREMISE
          FROM ARTHUS.PORTE_REMISE
         WHERE PORTE_REMISE.NUMPORTE = 1
           AND PORTE_REMISE.DATEPORTE > ADD_MONTHS(SYSDATE, -36))
GO
CREATE OR REPLACE PUBLIC SYNONYM V_BENE_JUSTIF19 FOR ARTHUS.V_BENE_JUSTIF19
