CREATE FORCE VIEW ARTHUS.V_COMPTA_SCHEMA_CM14 AS
SELECT DISTINCT
		COMPTA_SCHEMA.NUMSOC,
		COMPTA_SCHEMA.ROLESOC,
		COMPTA_SCHEMA.CODOPE,
		COMPTA_SCHEMA.SCDOPE
    FROM COMPTA_SCHEMA
GO
CREATE OR REPLACE PUBLIC SYNONYM V_COMPTA_SCHEMA_CM14 FOR ARTHUS.V_COMPTA_SCHEMA_CM14
