CREATE FORCE VIEW ARTHUS.V_COMPTA_SCHEMA AS
SELECT ALL COMPTA_SCHEMA.CODOPE,
                   COMPTA_SCHEMA.ROLESOC,
                   COMPTA_SCHEMA.NUMSOC
        FROM COMPTA_SCHEMA
  GROUP BY COMPTA_SCHEMA.CODOPE,
 		COMPTA_SCHEMA.ROLESOC,
        COMPTA_SCHEMA.NUMSOC
GO
CREATE OR REPLACE PUBLIC SYNONYM V_COMPTA_SCHEMA FOR ARTHUS.V_COMPTA_SCHEMA
