CREATE FORCE VIEW ARTHUS.V_COMPTA10_R AS
Select	contrat.numinterm 						numsoc,
	f_cpta_role(qttc_gar.numfor,1,2)						rolesoc,
	'qttc'										sur_entite,
	facture_regul.numfact_regul									cle_unique,
	'fact_regul'										entite,
	1	  										REG_PIECE,
	facture_regul.numfact_regul									cle,
	facture_regul.idcompta									idcompta,
	10		 									codope,
	'' 											scdope,
	''				    							codjnal,
	2											type_ope,
	f_assureur(qttc_gar.numfor)							cie,
	appel_regularise.numquerable 							indv,
	qttc_gar.numfor 									gar,
	0 											int,
	'' 											bqe,
	Substr( to_char(facture_regul.numfact_regul, '00000000'), 2, 8 ) 			refpiece,
	emission.datemis 								dat_piece,
	qttc_gar.numquit							lib_piece_1,
	appel_regularise.numquerable						lib_piece_2,
	-sum(	qttc_gar.mt_ttc_d)							montant1,
	-(ARTHUS.pk_cotis.totbrut_d(qttc_gar.numquit,qttc_gar.numfor) + ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor)) montant2,
	0											montant3,
	0											montant4,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor)  				montant5,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',1) 				montant6,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',2) 				montant7,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',3)  				montant8,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',4)  				montant9,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0)            				montant10,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,1)             				montant11,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,2)         				montant12,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,3)        				montant13,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,4)        				montant14,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor) 			montant15,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',1) 				montant16,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',2) 				montant17,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',3) 				montant18,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',4) 				montant19,
	0											montant20,
	0											montant21,
	0											montant22,
	0											montant23,
	0											montant24,
	0											montant25,
	0											montant26,
	0											montant27,
	0											montant28,
	0											montant29,
	0											montant30,
	qttc_gar.monnaie_d								devise,
	-sum(	qttc_gar.mt_ttc_d)						montant1_ct,
	-(ARTHUS.pk_cotis.totbrut_d(qttc_gar.numquit,qttc_gar.numfor) + ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor)) montant2_ct,
	0												montant3_ct,
	0												montant4_ct,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor)  		montant5_ct,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',1)  	montant6_ct,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',2) 		montant7_ct,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',3)  	montant8_ct,
	-ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',4)  	montant9_ct,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0)            		montant10_ct,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,1)             		montant11_ct,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,2)          		montant12_ct,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,3)         		montant13_ct,
	-ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,4)          		montant14_ct,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor)  		montant15_ct,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',1)  	montant16_ct,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',2)  	montant17_ct,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',3)  	montant18_ct,
	-ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',4)  	montant19_ct,
	0											montant20_ct,
	0											montant21_ct,
	0											montant22_ct,
	0											montant23_ct,
	0											montant24_ct,
	0											montant25_ct,
	0											montant26_ct,
	0											montant27_ct,
	0											montant28_ct,
	0											montant29_ct,
	0											montant30_ct,
	qttc_gar.monnaie_d							devise_ct,
	'C' ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,1,appel_regularise.debut))	VAR01,
	'NV'											VAR02,
	'NV'											VAR03,
	'NV'											VAR04,
	'NV'											VAR05,
	'NV'											VAR06,
	f_code_reass(appel_regularise.numgar,qttc_gar.numfor,appel_regularise.debut)				VAR07,
	to_char(f_nat_risq(appel_regularise.numgar,qttc_gar.numfor))							VAR08,
	to_char(f_code_cmcr(appel_regularise.numgar,qttc_gar.numfor))							VAR09,
	'M' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(qttc_gar.numfor,1,2))			VAR10,
	'G'  ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,2,appel_regularise.debut)) 	VAR11,
	'K1' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(qttc_gar.numfor,1,2))	VAR12,
	ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,1,appel_regularise.debut))			VAR13,
	CONTRAT.REFCIE_CHAPEAU								VAR14,
	to_char(CONTRAT.NUMGAR_REF)							VAR15,
	'NV'											VAR16,
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,appel_regularise.debut),1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),999999999 ) 	VAR17,
	'S' ||CONTRAT.REFCIE_CHAPEAU					VAR18,
	'H' ||CONTRAT.REFCIE_CHAPEAU							VAR19,
	to_char(CONTRAT.NUMGAR)								VAR20,
	ARTHUS.pk_personne.f_nom_compta(appel_regularise.numquerable)			VAR21,
	CONTRAT.PORTEFEUILLE							VAR22,
	to_char(appel_regularise.debut,'YYYY')						VAR23,
	'NV'											VAR24,
	'NV'											VAR25,
	'NV'											VAR26,
	'NV'											VAR27,
	'NV'											VAR28,
	'NV'											VAR29,
	to_char(appel_regularise.debut,'DD/MM/YYYY') 					VAR30
From 	contrat,
	qttc_gar,
	qttc_global appel_regularise,
	qttc_global	appel_regularisant,
	emission,
	facture_regul
Where	facture_regul.codope		= 4
and	facture_regul.idcompta		= -1
and	facture_regul.numfact		= appel_regularisant.numquit
and	appel_regularisant.numquit 	= emission.numfact
and	emission.codope 			= 4
and 	emission.type_doc			= 1
and	emission.numrelance		= 0
and	appel_regularise.numquit	= facture_regul.numfact_regul
and	appel_regularise.mt_ttc 	Is Not Null
and	qttc_gar.numquit			= appel_regularise.numquit
and	contrat.numgar 			= appel_regularise.numgar
group by
	contrat.numinterm,
	f_cpta_role(qttc_gar.numfor,1,2),
	facture_regul.idcompta,
	f_assureur(qttc_gar.numfor),
	appel_regularise.numquerable,
	qttc_gar.numfor,
	qttc_gar.numquit,
	emission.datemis,
	appel_regularise.debut,
	qttc_gar.monnaie_d,
	facture_regul.numfact_regul,
	ARTHUS.pk_cotis.totbrut_d(qttc_gar.numquit, qttc_gar.numfor),
	ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit, qttc_gar.numfor) ,
	ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit, qttc_gar.numfor, '',1) ,
	ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',2) ,
	ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit,qttc_gar.numfor, '',3),
	ARTHUS.pk_cotis.tottaxe_d(qttc_gar.numquit, qttc_gar.numfor, '',4) ,
	ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0),
	ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,1) ,
	ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,2) ,
	ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit, qttc_gar.numfor, '', 0,3) ,
	ARTHUS.pk_cotis.totfrais_d(qttc_gar.numquit,qttc_gar.numfor, '', 0,4) ,
	ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor),
	ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit, qttc_gar.numfor, '',1),
	ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit,qttc_gar.numfor, '',2) ,
	ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit, qttc_gar.numfor, '',3) ,
	ARTHUS.pk_cotis.totcomm_d(qttc_gar.numquit, qttc_gar.numfor, '',4) ,
	f_code_reass(appel_regularise.numgar,qttc_gar.numfor,appel_regularise.debut),
	to_char(f_nat_risq(appel_regularise.numgar,qttc_gar.numfor))	,
	to_char(f_code_cmcr(appel_regularise.numgar,qttc_gar.numfor)),
	'M' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(qttc_gar.numfor,1,2)),
	'G' ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,2,appel_regularise.debut)),
	'K1' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(qttc_gar.numfor,1,2)),
	ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,1,appel_regularise.debut)),
	CONTRAT.REFCIE_CHAPEAU,
	'S' ||CONTRAT.REFCIE_CHAPEAU,
	'H' ||CONTRAT.REFCIE_CHAPEAU,
	to_char(CONTRAT.NUMGAR_REF),
	CONTRAT.PORTEFEUILLE,
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,appel_regularise.debut),1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),999999999 ),
	'S' ||CONTRAT.REFCIE_CHAPEAU,
	to_char(CONTRAT.NUMGAR),
	ARTHUS.pk_personne.f_nom_compta(appel_regularise.numquerable),
	to_char(appel_regularise.debut,'DD/MM/YYYY')
---------------------------------------------------------------------------------------------
--			Frais globaux (numfor=0)
---------------------------------------------------------------------------------------------
Union All
	Select	contrat.numinterm 						numsoc,
	f_cpta_role(contrat.numgar,2,2)						rolesoc,
	'qttc'										sur_entite,
	facture_regul.numfact_regul									cle_unique,
	'fact_regul'										entite,
	1	  										REG_PIECE,
	facture_regul.numfact_regul									cle,
	facture_regul.idcompta									idcompta,
	10		 									codope,
	'' 											scdope,
	''				    							codjnal,
	2											type_ope,
	contrat.numorg									cie,
	appel_regularise.numquerable 							indv,
	0											gar,
	0 											int,
	'' 											bqe,
	Substr( to_char(facture_regul.numfact_regul, '00000000'), 2, 8 ) 			refpiece,
	emission.datemis 								dat_piece,
	appel_regularise.numquit							lib_piece_1,
	appel_regularise.numquerable						lib_piece_2,
	0											montant1,
	0 											montant2,
	0 											montant3,
	0                       							montant4,
	0 											montant5,
	0 											montant6,
	0											montant7,
	0											montant8,
	0											montant9,
	0											montant10,
	0											montant11,
	0											montant12,
	0											montant13,
	0											montant14,
	0											montant15,
	0											montant16,
	0											montant17,
	0											montant18,
	0											montant19,
	0											montant20,
	0											montant21,
	0											montant22,
	0											montant23,
	0											montant24,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0) ) 			montant25,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0,'','',1) ) 	montant26,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0,'','',2) ) 	montant27,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0,'','',3) ) 	montant28,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0,'','',4) ) 	montant29,
	0											montant30,
	appel_regularise.monnaie_d						devise,
	0											montant1_ct,
	0 											montant2_ct,
	0 											montant3_ct,
	0                       					montant4_ct,
	0 											montant5_ct,
	0 											montant6_ct,
	0											montant7_ct,
	0											montant8_ct,
	0											montant9_ct,
	0											montant10_ct,
	0											montant11_ct,
	0											montant12_ct,
	0											montant13_ct,
	0											montant14_ct,
	0											montant15_ct,
	0											montant16_ct,
	0											montant17_ct,
	0											montant18_ct,
	0											montant19_ct,
	0											montant20_ct,
	0											montant21_ct,
	0											montant22_ct,
	0											montant23_ct,
	0											montant24_ct,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0) ) 			montant25_ct,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0,'','',1) ) 	montant26_ct,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0,'','',2) ) 	montant27_ct,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0,'','',3) ) 	montant28_ct,
	-sum( ARTHUS.pk_cotis.totfrais_d(appel_regularise.numquit, 0,'','',4) ) 	montant29_ct,
	0											montant30_ct,
	appel_regularise.monnaie_d						devise_ct,
	'C' ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,1,appel_regularise.debut))	VAR01,
	'NV'											VAR02,
	'NV'											VAR03,
	'NV'											VAR04,
	'NV'											VAR05,
	'NV'											VAR06,
	'NV'        									VAR07,
	'NV'											VAR08,
	'NV'											VAR09,
	'M' ||ARTHUS.pk_personne.f_nom_compta(contrat.numorg)					VAR10,
	'G' ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,2,appel_regularise.debut))	VAR11,
	'NV'											VAR12,
	ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,1,appel_regularise.debut))		VAR13,
	CONTRAT.REFCIE_CHAPEAU								VAR14,
	to_char(CONTRAT.NUMGAR_REF)							VAR15,
	'NV'											VAR16,
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,appel_regularise.debut),1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),999999999 )	VAR17,
	'S' ||CONTRAT.REFCIE_CHAPEAU							VAR18,
	'H' ||CONTRAT.REFCIE_CHAPEAU							VAR19,
	to_char(CONTRAT.NUMGAR)								VAR20,
	ARTHUS.pk_personne.f_nom_compta(appel_regularise.numquerable)			VAR21,
	CONTRAT.PORTEFEUILLE							VAR22,
	to_char(appel_regularise.debut,'YYYY') 						VAR23,
	'NV'											VAR24,
	'NV'											VAR25,
	'NV'											VAR26,
	'NV'											VAR27,
	'NV'											VAR28,
	'NV'											VAR29,
	to_char(appel_regularise.debut,'DD/MM/YYYY') 					VAR30
From 	contrat,
	qttc_global appel_regularise,
	qttc_global	appel_regularisant,
	emission,
	facture_regul
Where	facture_regul.codope		= 4
and	facture_regul.idcompta		= -1
and	facture_regul.numfact		= appel_regularisant.numquit
and	appel_regularisant.numquit 	= emission.numfact
and	emission.codope 			= 4
and 	emission.type_doc			= 1
and	emission.numrelance		= 0
and	appel_regularise.numquit	= facture_regul.numfact_regul
and	appel_regularise.mt_ttc 	Is Not Null
and	contrat.numgar 			= appel_regularise.numgar
and	Exists (
	Select	1
	from	qttc_frais
	Where	numquit = appel_regularise.numquit
	and           numfor=0)
group by
	contrat.numinterm,
	f_cpta_role(contrat.numgar,2,2),
	facture_regul.idcompta,
	contrat.numorg,
	appel_regularise.numquerable,
	appel_regularise.numquit,
	emission.datemis,
	appel_regularise.debut,
	appel_regularise.monnaie_d,
	facture_regul.numfact_regul,
	'M' ||ARTHUS.pk_personne.f_nom_compta(contrat.numorg),
	'G' ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,2,appel_regularise.debut)),
	ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,1,appel_regularise.debut)),
	CONTRAT.REFCIE_CHAPEAU,
	to_char(CONTRAT.NUMGAR_REF),
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,appel_regularise.debut),1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),999999999 ),
	'S' ||CONTRAT.REFCIE_CHAPEAU,
	'H' ||CONTRAT.REFCIE_CHAPEAU,
	to_char(CONTRAT.NUMGAR),
	CONTRAT.PORTEFEUILLE,
	ARTHUS.pk_personne.f_nom_compta(appel_regularise.numquerable),to_char(appel_regularise.debut,'DD/MM/YYYY')
------------------------------------------------------------------------------------------------
--			Retrocessions de commissions par garanties
------------------------------------------------------------------------------------------------
Union All
	Select	contrat.numinterm 						numsoc,
	f_cpta_role(qttc_gar.numfor,1,2)						rolesoc,
	'qttc'										sur_entite,
	facture_regul.numfact_regul									cle_unique,
	'fact_regul'										entite,
	1	  										REG_PIECE,
	facture_regul.numfact_regul									cle,
	facture_regul.idcompta									idcompta,
	10		 									codope,
	'' 											scdope,
	''				    							codjnal,
	2											type_ope,
	f_assureur(qttc_gar.numfor)							cie,
	appel_regularise.numquerable 							indv,
	qttc_gar.numfor 									gar,
	0 											int,
	'' 											bqe,
	Substr( to_char(facture_regul.numfact_regul, '00000000'), 2, 8 ) 			refpiece,
	emission.datemis 								dat_piece,
	appel_regularise.numquit							lib_piece_1,
	appel_regularise.numquerable						lib_piece_2,
	0				montant1,
	0   			montant2,
	0				montant3,
	0				montant4,
	0 				montant5,
	0 				montant6,
	0				montant7,
	0 				montant8,
	0 				montant9,
	0           	montant10,
	0            	montant11,
	0         		montant12,
	0         		montant13,
	0        		montant14,
	0 				montant15,
	0 				montant16,
	0 				montant17,
	0 				montant18,
	0				montant19,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,'', qttc_retro.numbene,qttc_gar.numfor)  montant20,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,1, qttc_retro.numbene,qttc_gar.numfor)  montant21,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,2, qttc_retro.numbene,qttc_gar.numfor)  montant22,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,3, qttc_retro.numbene,qttc_gar.numfor)  montant23,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,4, qttc_retro.numbene,qttc_gar.numfor)  montant24,
	0											montant25,
	0											montant26,
	0											montant27,
	0											montant28,
	0											montant29,
	0											montant30,
	qttc_gar.monnaie_d						devise,
	0				montant1_ct,
	0   			montant2_ct,
	0				montant3_ct,
	0				montant4_ct,
	0 				montant5_ct,
	0 				montant6_ct,
	0				montant7_ct,
	0 				montant8_ct,
	0 				montant9_ct,
	0           	montant10_ct,
	0            	montant11_ct,
	0         		montant12_ct,
	0         		montant13_ct,
	0         		montant14_ct,
	0 				montant15_ct,
	0 				montant16_ct,
	0 				montant17_ct,
	0 				montant18_ct,
	0 				montant19_ct,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,'', qttc_retro.numbene,qttc_gar.numfor) 	montant20_ct,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,1, qttc_retro.numbene,qttc_gar.numfor) 	montant21_ct,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,2, qttc_retro.numbene,qttc_gar.numfor) 	montant22_ct,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,3, qttc_retro.numbene,qttc_gar.numfor) 	montant23_ct,
	-ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,4, qttc_retro.numbene,qttc_gar.numfor) 	montant24_ct,
	0											montant25_ct,
	0											montant26_ct,
	0											montant27_ct,
	0											montant28_ct,
	0											montant29_ct,
	0											montant30_ct,
	qttc_gar.monnaie_d						devise_ct,
	'C' || ARTHUS.pk_personne.f_nom_compta(qttc_retro.numbene)	VAR01,
	'NV'											VAR02,
	'NV'											VAR03,
	'NV'											VAR04,
	'NV'											VAR05,
	'NV'											VAR06,
	f_code_reass(appel_regularise.numgar,qttc_gar.numfor,appel_regularise.debut)		VAR07,
	to_char(f_nat_risq(appel_regularise.numgar,qttc_gar.numfor))						VAR08,
	to_char(f_code_cmcr(appel_regularise.numgar,qttc_gar.numfor))						VAR09,
	'M' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(qttc_gar.numfor,1,2))			VAR10,
	'G'  ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,2,appel_regularise.debut)) 			VAR11,
	'K1' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(qttc_gar.numfor,1,2))	VAR12,
	ARTHUS.pk_personne.f_nom_compta(qttc_retro.numbene)						VAR13,
	CONTRAT.REFCIE_CHAPEAU								VAR14,
	to_char(CONTRAT.NUMGAR_REF)							VAR15,
	'NV'											VAR16,
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,appel_regularise.debut),1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),999999999 ) VAR17,
	'S' ||CONTRAT.REFCIE_CHAPEAU					VAR18,
	'H' ||CONTRAT.REFCIE_CHAPEAU							VAR19,
	to_char(CONTRAT.NUMGAR)								VAR20,
	ARTHUS.pk_personne.f_nom_compta(appel_regularise.numquerable)	VAR21,
	CONTRAT.PORTEFEUILLE							VAR22,
	to_char(appel_regularise.debut,'YYYY')				VAR23,
	'NV'											VAR24,
	'NV'											VAR25,
	'NV'											VAR26,
	'NV'											VAR27,
	'NV'											VAR28,
	'NV'											VAR29,
	to_char(appel_regularise.debut,'DD/MM/YYYY') 		VAR30
From 	contrat,
	qttc_gar,
	qttc_retro,
	qttc_global appel_regularise,
	qttc_global	appel_regularisant,
	emission,
	facture_regul
Where	facture_regul.codope		= 4
and	facture_regul.idcompta		= -1
and	facture_regul.numfact		= appel_regularisant.numquit
and	appel_regularisant.numquit 	= emission.numfact
and	emission.codope 			= 4
and 	emission.type_doc			= 1
and	emission.numrelance		= 0
and	appel_regularise.numquit	= facture_regul.numfact_regul
and	appel_regularise.mt_ttc 	Is Not Null
and	qttc_gar.numquit			= appel_regularise.numquit
and 	qttc_gar.numquit			= qttc_retro.numquit
and 	qttc_gar.numfor   		= qttc_retro.numfor
and	contrat.numgar 			= appel_regularise.numgar
group by
	contrat.numinterm,
	f_cpta_role(qttc_gar.numfor,1,2),
	facture_regul.idcompta,
	f_assureur(qttc_gar.numfor),
	appel_regularise.numquerable,
	ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,'', qttc_retro.numbene,qttc_gar.numfor),
	ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,1, qttc_retro.numbene,qttc_gar.numfor),
	ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,2, qttc_retro.numbene,qttc_gar.numfor),
	ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,3, qttc_retro.numbene,qttc_gar.numfor),
	ARTHUS.pk_cotis.totretro_d(qttc_gar.numquit,4, qttc_retro.numbene,qttc_gar.numfor),
	qttc_gar.numfor,
	appel_regularise.numquit,
	emission.datemis,
	appel_regularise.debut,
	qttc_gar.monnaie_d,
	facture_regul.numfact_regul,
	f_code_reass(appel_regularise.numgar,qttc_gar.numfor,appel_regularise.debut),
	to_char(f_nat_risq(appel_regularise.numgar,qttc_gar.numfor)),
	to_char(f_code_cmcr(appel_regularise.numgar,qttc_gar.numfor)),
	'M' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(qttc_gar.numfor,1,2)),
	'G' ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,appel_regularise.numgar,2,appel_regularise.debut)),
	'K1'||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(qttc_gar.numfor,1,2)),
	'C' ||ARTHUS.pk_personne.f_nom_compta(qttc_retro.numbene),
	ARTHUS.pk_personne.f_nom_compta(qttc_retro.numbene),
	CONTRAT.REFCIE_CHAPEAU,
	'S' ||CONTRAT.REFCIE_CHAPEAU,
	'H' ||CONTRAT.REFCIE_CHAPEAU,
	to_char(CONTRAT.NUMGAR_REF),
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,appel_regularise.debut),1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),999999999 ),
	to_char(CONTRAT.NUMGAR),
	CONTRAT.PORTEFEUILLE,
	ARTHUS.pk_personne.f_nom_compta(appel_regularise.numquerable),
	to_char(appel_regularise.debut,'DD/MM/YYYY')
GO
CREATE OR REPLACE PUBLIC SYNONYM V_COMPTA10_R FOR ARTHUS.V_COMPTA10_R
