CREATE FORCE VIEW ARTHUS.V_COMPTA51 AS
Select	contrat.numinterm 	    	numsoc,
	decode (f_force_gest(numfor),
			0, decode(sinistre.typbene,
					  3, decode (f_cpta_role(sinistre.numfor,1,1),1,2,2,2,3,4,4,4),
					  f_cpta_role(sinistre.numfor,1,1)),
			1, decode(decode(sinistre.typbene,
							  3, decode (f_cpta_role(sinistre.numfor,1,1),1,2,2,2,3,4,4,4),
							  f_cpta_role(sinistre.numfor,1,1)),
					 1,1,
					 2,1,
					 3,1,
					 4,1)
			) rolesoc,
	'decaismt'				sur_entite,
	decaismt.numdecaismt	cle_unique,
	'decaismt' 				entite,
	1	  					REG_PIECE,
	decaismt.numdecaismt	cle,
	decaismt.idcompta,
	51		 			 	codope,
	''						scdope,
	nvl(compte.journal,'0')				codjnal,
	1 						type_ope,
	f_soc_assu(sinistre.numfor,1,2)	cie,
	decaismt.numbene 				indv,
	sinistre.numfor 				gar,
	f_intermediaire(2,sinistre.numgar,1,decaismt.datpay) int,
	compte.cmpt_gene				bqe,
	substr(to_char(decaismt.numdecaismt,'00000000'),2,8) refpiece,
	decaismt.datpay		dat_piece,
	decaismt.numdecaismt	lib_piece_1,
	decaismt.numbene	lib_piece_2,
	decode(f_force_type_mt(numfor),1,0,sum(sinistre_dev.mtreel_CT + nvl(ecart_piece.MONTANT,0))) 	montant1,
	decode(f_force_type_mt(numfor),1,sum(sinistre_dev.mtreel_CT + nvl(ecart_piece.MONTANT,0)),0) 	montant2,
	(decode(f_force_type_mt(numfor),1,0,sum(sinistre_dev.mtreel_CT + nvl(ecart_piece.MONTANT,0))))+
	(decode(f_force_type_mt(numfor),1,sum(sinistre_dev.mtreel_CT + nvl(ecart_piece.MONTANT,0)),0)) 	montant3,
	0 						montant4,
	0 						montant5,
	0 						montant6,
	0						montant7,
	0						montant8,
	0						montant9,
	0						montant10,
	0						montant11,
	0						montant12,
	0						montant13,
	0						montant14,
	0						montant15,
	0						montant16,
	0						montant17,
	0						montant18,
	0						montant19,
	0						montant20,
	0						montant21,
	0						montant22,
	0						montant23,
	0						montant24,
	0						montant25,
	0						montant26,
	0						montant27,
	0						montant28,
	0						montant29,
	0						montant30,
	sinistre_dev.dev_ct		devise,
	decode(f_force_type_mt(numfor),1,0,sum(sinistre_dev.mtreel_CT + nvl(ecart_piece.MONTANT,0))) montant1_CT,
	decode(f_force_type_mt(numfor),1,sum(sinistre_dev.mtreel_CT + nvl(ecart_piece.MONTANT,0)),0) montant2_CT,
	(decode(f_force_type_mt(numfor),1,0,sum(sinistre_dev.mtreel_CT + nvl(ecart_piece.MONTANT,0))))+
	(decode(f_force_type_mt(numfor),1,sum(sinistre_dev.mtreel_CT + nvl(ecart_piece.MONTANT,0)),0)) 	montant3_CT,
	0 						montant4_CT,
	0 						montant5_CT,
	0 						montant6_CT,
	0						montant7_CT,
	0						montant8_CT,
	0						montant9_CT,
	0						montant10_CT,
	0						montant11_CT,
	0						montant12_CT,
	0						montant13_CT,
	0						montant14_CT,
	0						montant15_CT,
	0						montant16_CT,
	0						montant17_CT,
	0						montant18_CT,
	0						montant19_CT,
	0						montant20_CT,
	0						montant21_CT,
	0						montant22_CT,
	0						montant23_CT,
	0						montant24_CT,
	0						montant25_CT,
	0						montant26_CT,
	0						montant27_CT,
	0						montant28_CT,
	0						montant29_CT,
	0						montant30_CT,
	sinistre_dev.dev_CT				devise_CT,
	'NV'							VAR01,
	nvl(compte.journal,'0')				VAR02,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,2)	VAR03,
	compte.cmpt_gene					VAR04,
	'NV'							VAR05,
	'NV'							VAR06,
	f_code_reass(sinistre.numgar,sinistre.numfor,decaismt.datpay) VAR07,
	to_char(f_nat_risq(sinistre.numgar,sinistre.numfor)) VAR08,
	to_char(f_code_cmcr(sinistre.numgar,sinistre.numfor)) VAR09,
	'NV'							VAR10,
	'G' ||ARTHUS.pk_personne.f_nom_compta(decode(decode (f_force_gest(numfor),
			0, decode(sinistre.typbene,
					  3, decode (f_cpta_role(sinistre.numfor,1,1),1,2,2,2,3,4,4,4),
					  f_cpta_role(sinistre.numfor,1,1)),
			1, decode(decode(sinistre.typbene,
							  3, decode (f_cpta_role(sinistre.numfor,1,1),1,2,2,2,3,4,4,4),
							  f_cpta_role(sinistre.numfor,1,1)),
					 1,1,
					 2,1,
					 3,1,
					 4,1)
			), 3, sinistre.numbene,	f_intermediaire(2,sinistre.numgar,2,decaismt.datpay)
	)) 							VAR11,
	'K1' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(sinistre.numfor,1,2)) VAR12,
	ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,sinistre.numgar,1,decaismt.datpay)) VAR13,
	CONTRAT.REFCIE_CHAPEAU 				VAR14,
	to_char(CONTRAT.NUMGAR_REF) 			VAR15,
	'NV'							VAR16,
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,decaismt.datpay),
		   1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),
		   999999999 ) 				VAR17,
	'NV'							VAR18,
	'NV'							VAR19,
	to_char(CONTRAT.NUMGAR) 			VAR20,
	'NV'							VAR21,
	CONTRAT.PORTEFEUILLE				VAR22,
	to_char(decaismt.datpay,'YYYY')		VAR23,
	'NV'							VAR24,
	'NV'							VAR25,
	'NV'							VAR26,
	'NV'							VAR27,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,3,10)	VAR28,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,1)	VAR29,
	to_char(decaismt.datpay,'DD/MM/YYYY')	VAR30
From	sinistre,
		ecart_piece,
		sinistre_dev,
		decompte,
		affectation,
		decaismt,
		compte,
		contrat
Where	sinistre.numdec		= decompte.numdec
and	contrat.numgar 			= sinistre.numgar
and sinistre.numsin 		= sinistre_dev.numsin
and sinistre.numdec			= affectation.numaffec
and	affectation.codope		= 1
and	compte.numcpte			= decaismt.numcpte
and	compte.type	= 1
and affectation.numdecaismt	= decaismt.numdecaismt
and	decaismt.flagpay 		= 1
and sinistre.numsin =  ecart_piece.numpiece(+)
and 1= ecart_piece.codope(+)
group by
	nvl(compte.journal,'0')	,
	contrat.numinterm,
	decode (f_force_gest(numfor),
			0, decode(sinistre.typbene,
					  3, decode (f_cpta_role(sinistre.numfor,1,1),1,2,2,2,3,4,4,4),
					  f_cpta_role(sinistre.numfor,1,1)),
			1, decode(decode(sinistre.typbene,
							  3, decode (f_cpta_role(sinistre.numfor,1,1),1,2,2,2,3,4,4,4),
							  f_cpta_role(sinistre.numfor,1,1)),
					 1,1,
					 2,1,
					 3,1,
					 4,1)
			),
	decaismt.numdecaismt,
	decaismt.idcompta,
	f_soc_assu(sinistre.numfor,1,2)	,
	decaismt.numbene ,
	sinistre.numfor,
	f_intermediaire(2,sinistre.numgar,1,decaismt.datpay),
	compte.cmpt_gene,
	substr(to_char(decaismt.numdecaismt,'00000000'),2,8),
	decaismt.datpay,
	sinistre.monnaie,
	sinistre_dev.dev_ct,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,2),
	f_code_reass(sinistre.numgar,sinistre.numfor,decaismt.datpay),
	f_nat_risq(sinistre.numgar,sinistre.numfor),
	f_code_cmcr(sinistre.numgar,sinistre.numfor),
	'G' ||ARTHUS.pk_personne.f_nom_compta(decode(decode (f_force_gest(numfor),
			0, decode(sinistre.typbene,
					  3, decode (f_cpta_role(sinistre.numfor,1,1),1,2,2,2,3,4,4,4),
					  f_cpta_role(sinistre.numfor,1,1)),
			1, decode(decode(sinistre.typbene,
							  3, decode (f_cpta_role(sinistre.numfor,1,1),1,2,2,2,3,4,4,4),
							  f_cpta_role(sinistre.numfor,1,1)),
					 1,1,
					 2,1,
					 3,1,
					 4,1)
			), 3, sinistre.numbene,	f_intermediaire(2,sinistre.numgar,2,decaismt.datpay)
	)),
	'K1' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(sinistre.numfor,1,2)),
	ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,sinistre.numgar,1,decaismt.datpay)),
	CONTRAT.REFCIE_CHAPEAU,
	CONTRAT.NUMGAR_REF,
	CONTRAT.PORTEFEUILLE,
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,decaismt.datpay),
		   1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),
		   999999999 ),
	CONTRAT.NUMGAR,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,3,10),
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,1),
	to_char(decaismt.datpay,'DD/MM/YYYY')
union all
 Select	contrat.numinterm 	    	numsoc,
	f_cpta_role(decompte.numgar,2,1) rolesoc,
	'decaismt'				sur_entite,
	decaismt.numdecaismt	cle_unique,
	'decaismt' 				entite,
	1	  					REG_PIECE,
	decaismt.numdecaismt	cle,
	decaismt.idcompta,
	51		 			 	codope,
	''						scdope,
	nvl(compte.journal,'0')				codjnal,
	1 						type_ope,
	f_soc_assu(decompte.numgar,2,2)	cie,
	decaismt.numbene 				indv,
	0			      				gar,
	f_intermediaire(2,decompte.numgar,1,decaismt.datpay) int,
	compte.cmpt_gene				bqe,
	substr(to_char(decaismt.numdecaismt,'00000000'),2,8) refpiece,
	decaismt.datpay    			dat_piece,
	decaismt.numdecaismt			lib_piece_1,
	decaismt.numbene				lib_piece_2,
	0						montant1,
	0						montant2,
	sum(decaismt.montant_CT + decaismt.montant_EC) montant3,
	0 						montant4,
	0 						montant5,
	0 						montant6,
	0						montant7,
	0						montant8,
	0						montant9,
	0						montant10,
	0						montant11,
	0						montant12,
	0						montant13,
	0						montant14,
	0						montant15,
	0						montant16,
	0						montant17,
	0						montant18,
	0						montant19,
	0						montant20,
	0						montant21,
	0						montant22,
	0						montant23,
	0						montant24,
	0						montant25,
	0						montant26,
	0						montant27,
	0						montant28,
	0						montant29,
	0						montant30,
	decaismt.devise_ct		devise,
	0						montant1,
	0						montant2,
	sum(decaismt.montant_CT + decaismt.montant_EC) montant3_CT,
	0 						montant4_CT,
	0 						montant5_CT,
	0 						montant6_CT,
	0						montant7_CT,
	0						montant8_CT,
	0						montant9_CT,
	0						montant10_CT,
	0						montant11_CT,
	0						montant12_CT,
	0						montant13_CT,
	0						montant14_CT,
	0						montant15_CT,
	0						montant16_CT,
	0						montant17_CT,
	0						montant18_CT,
	0						montant19_CT,
	0						montant20_CT,
	0						montant21_CT,
	0						montant22_CT,
	0						montant23_CT,
	0						montant24_CT,
	0						montant25_CT,
	0						montant26_CT,
	0						montant27_CT,
	0						montant28_CT,
	0						montant29_CT,
	0						montant30_CT,
	decaismt.devise_CT		devise_CT,
	'NV'							VAR01,
	nvl(compte.journal,'0')				VAR02,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,2)	VAR03,
	compte.cmpt_gene					VAR04,
	'NV'							VAR05,
	'NV'							VAR06,
	'NV'							VAR07,
	'NV'							VAR08,
	'NV'							VAR09,
	'NV'							VAR10,
	'G' ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,decompte.numgar,2,decaismt.datpay)) VAR11,
	'K1' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(decompte.numgar,2,2)) VAR12,
	ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,decompte.numgar,1,decaismt.datpay)) VAR13,
	CONTRAT.REFCIE_CHAPEAU 				VAR14,
	to_char(CONTRAT.NUMGAR_REF) 			VAR15,
	'NV'							VAR16,
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,decaismt.datpay),
		   1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),
		   999999999 ) 				VAR17,
	'NV'							VAR18,
	'NV'							VAR19,
	to_char(CONTRAT.NUMGAR) 			VAR20,
	'NV'							VAR21,
	CONTRAT.PORTEFEUILLE				VAR22,
	to_char(decaismt.datpay,'YYYY')		VAR23,
	'NV'							VAR24,
	'NV'							VAR25,
	'NV'							VAR26,
	'NV'							VAR27,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,3,10)	VAR28,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,1)	VAR29,
	to_char(decaismt.datpay,'DD/MM/YYYY')	VAR30
From	decompte,
		affectation,
		decaismt,
		compte,
		contrat
Where contrat.numgar 			= decompte.numgar
and decompte.numdec			= affectation.numaffec
and	affectation.codope		= 1
and	compte.numcpte			= decaismt.numcpte
and	compte.type	= 1
and affectation.numdecaismt	= decaismt.numdecaismt
and	decaismt.flagpay 		= 1
group by
	nvl(compte.journal,'0'),
	contrat.numinterm,
	f_cpta_role(decompte.numgar,2,1),
	decaismt.numdecaismt,
	decaismt.idcompta,
	f_soc_assu(decompte.numgar,2,2)	,
	decaismt.numbene ,
	f_intermediaire(2,decompte.numgar,1,decaismt.datpay),
	compte.cmpt_gene,
	substr(to_char(decaismt.numdecaismt,'00000000'),2,8),
	decaismt.datpay,
	decaismt.devise_ct,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,2),
	'G' ||ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,decompte.numgar,2,decaismt.datpay)),
	'K1' ||ARTHUS.pk_personne.f_nom_compta(f_soc_assu(decompte.numgar,2,2)),
	ARTHUS.pk_personne.f_nom_compta(f_intermediaire(2,decompte.numgar,1,decaismt.datpay)),
	CONTRAT.REFCIE_CHAPEAU,
	CONTRAT.NUMGAR_REF,
	decode(ARTHUS.pk_personne.f_dependance(contrat.numcli,99,decaismt.datpay),
		   1,ARTHUS.pk_personne.f_nom_compta(contrat.numcli),
		   999999999 ),
	CONTRAT.NUMGAR,
	CONTRAT.PORTEFEUILLE,
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,3,10),
	F_CPTA_LIB_REGLT(decaismt.numdecaismt,1),
	to_char(decaismt.datpay,'DD/MM/YYYY')
GO
CREATE OR REPLACE PUBLIC SYNONYM V_COMPTA51 FOR ARTHUS.V_COMPTA51
