CREATE FORCE VIEW ARTHUS.V_CPTA_COTIS_REVERS_TAXE AS
Select
	compte.numsoc					numsoc,
	0								rolesoc,
	'qttc'							sur_entite,
	qttc_affec_tfc.numquit			cle_unique,
	'decaismt'						entite,
	decaismt.numdecaismt			cle,
	decaismt.idcompta				idcompta,
	40								codope,
	'C0400'							scdope,
	'CL1'							codjnal,
	1								type_ope,
	revers_taxe.numorg				cie,
	qttc_affec_tfc.numbene			indv,
	qttc_affec_tfc.numfor			gar,
	0 								int,
	compte.cmpt_gene 				bqe,
	Substr(to_char(decaismt.numdecaismt, '00000000'), 2, 8) refpiece,
	revers_taxe.datrevers 			dat_piece,
	qttc_affec_tfc.numquit			lib_piece_1,
	qttc_affec_tfc.numfor			lib_piece_2,
	ARTHUS.pk_cotis.mt_affec_tfc(	qttc_affec_tfc.numquit,
							qttc_affec_tfc.idrevers,
							qttc_affec_tfc.idaffec,
							qttc_affec_tfc.numfor,
							'',
							1)
          							montant1,
	0    							montant2,
	0    							montant3,
	0    							montant4,
	0    							montant5,
	0    							montant6,
	qttc_affec_tfc.monnaie			devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From
	compte,
	qttc_affec_tfc,
	revers_taxe,
	affectation,
	decaismt
Where	compte.numcpte		= decaismt.numcpte
and	decaismt.codope			= 6
and	affectation.numdecaismt	= decaismt.numdecaismt
and	affectation.numaffec 	= revers_taxe.IDREVTAX
and	qttc_affec_tfc.idrevers = revers_taxe.IDREVTAX
Group by
	compte.numsoc,
	qttc_affec_tfc.idrevers,
	qttc_affec_tfc.idaffec,
	qttc_affec_tfc.numquit,
	qttc_affec_tfc.numbene,
	qttc_affec_tfc.numfor,
	qttc_affec_tfc.monnaie,
	decaismt.numdecaismt,
	decaismt.idcompta,
	decaismt.codope	,
	revers_taxe.numorg,
	compte.cmpt_gene ,
	revers_taxe.IDREVTAX,
	revers_taxe.datrevers,
	revers_taxe.debut
GO
CREATE OR REPLACE PUBLIC SYNONYM V_CPTA_COTIS_REVERS_TAXE FOR ARTHUS.V_CPTA_COTIS_REVERS_TAXE
