CREATE FORCE VIEW ARTHUS.V_CPTA_COTIS_ENCAIS AS
Select	compte.numsoc,
	0							rolesoc,
	'remise_banque'				sur_entite,
	remise_globale.numremise	cle_unique,
	'encaismt'					entite,
	encaismt.numencaismt		cle,
	encaismt.idcompta			idcompta,
	20						codope,
	'C0200'					scdope,
	'CL1'			codjnal,
	1				type_ope,
	0 				cie,
	encaismt.numcli	indv,
	0 				gar,
	0 				int,
	compte.cmpt_gene 		bqe,
	Substr( to_char(remise_globale.numremise, '00000000'), 2, 8 )
					refpiece,
	remise_globale.daterem 		dat_piece,
	remise_globale.numremise	lib_piece_1,
	remise_globale.numcpte		lib_piece_2,
	encaismt.montant 		montant1,
	0 				montant2,
	0 				montant3,
	0 				montant4,
	0 				montant5,
	0				montant6,
	encaismt.monnaie		devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From	compte,
	remise_globale,
	encaismt
Where	compte.numcpte		= remise_globale.numcpte
and	encaismt.codope	+ 0	= 4
and	encaismt.numencaismt in (
	Select	numencaismt
	From	remise_banque
	Where	remise_banque.numremise = remise_globale.numremise)
Union All
/*	2		Encaissement de cotisations
				PRELEVEMENT
			---------------------------			*/
Select	compte.numsoc,
	0	rolesoc,
	'prelevement'				sur_entite,
	remise_prelev.numremise		cle_unique,
	'encaismt'					entite,
	encaismt.numencaismt		cle,
	encaismt.idcompta			dcompta,
	20				codope,
	'C0200'			scdope,
	'CL1'			codjnal,
	2				type_ope,
	0 				cie,
	encaismt.numcli	indv,
	0 				gar,
	0 				int,
	compte.cmpt_gene 		bqe,
	Substr( to_char(remise_prelev.numremise, '00000000'), 2, 8 )
					refpiece,
	remise_prelev.datrem 		dat_piece,
	remise_prelev.numremise		lib_piece_1,
	remise_prelev.numcpte		lib_piece_2,
	encaismt.montant 		montant1,
	0 				montant2,
	0 				montant3,
	0 				montant4,
	0 				montant5,
	0				montant6,
	encaismt.monnaie		devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From	compte,
	remise_prelev,
	encaismt
Where	compte.numcpte		= encaismt.numcpte
and	encaismt.codope	+ 0	= 4
and	encaismt.numencaismt in (
	Select	numencaismt
	From	prelevement
	Where	prelevement.numremise = remise_prelev.numremise
	)
Union All
-- 3	Encaissement hors remise
Select	compte.numsoc,
	0						rolesoc,
	'encaismt'				sur_entite,
	encaismt.numencaismt	cle_unique,
	'encaismt'				entite,
	encaismt.numencaismt	cle,
	encaismt.idcompta		idcompta,
	20						codope,
	'C0200'					scdope,
	'CL1'					codjnal,
	3						type_ope,
	0 						cie,
	encaismt.numcli			indv,
	0 						gar,
	0 						int,
	compte.cmpt_gene 		bqe,
	Substr( to_char(encaismt.numencaismt, '00000000'), 2, 8 ) 	refpiece,
	encaismt.datpay 		dat_piece,
	encaismt.refpmt 		lib_piece_1,
	encaismt.numcli 		lib_piece_2,
	encaismt.montant 		montant1,
	0 						montant2,
	0 						montant3,
	0 						montant4,
	0 						montant5,
	encaismt.montant 		montant6,
	encaismt.monnaie		devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From
	compte,
	encaismt
Where	compte.numcpte		= encaismt.numcpte
and 	Not Exists (
	Select	1
	From	prelevement
	Where	prelevement.numencaismt = encaismt.numencaismt)
and 	Not Exists (
	Select	1
	From	remise_banque
	Where	remise_banque.numencaismt = encaismt.numencaismt)
and	encaismt.codope + 0	= 4
Union All
/*	4		Encaissement de cotisations
			REMISE BANQUE -> Compte client
			---------------------------			*/
Select	compte.numsoc,
	0	rolesoc,
	'encaismt'			sur_entite,
	encaismt.numencaismt		cle_unique,
	'encaismt'			entite,
	encaismt.numencaismt		cle,
	encaismt.idcompta		idcompta,
	20				codope,
	'C0200'			scdope,
	'CL1'			codjnal,
	4				type_ope,
	0 				cie,
	encaismt.numcli			indv,
	0 				gar,
	0 				int,
	compte.cmpt_gene 		bqe,
	Substr( to_char(remise_globale.numremise, '00000000'), 2, 8 )
					refpiece,
	remise_globale.daterem 		dat_piece,
	encaismt.refpmt			lib_piece_1,
	encaismt.numcli			lib_piece_2,
	0						montant1,
	0 						montant2,
	0 						montant3,
	0 						montant4,
	0 						montant5,
	encaismt.montant		montant6,
	encaismt.monnaie		devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From	compte,
	remise_globale,
	encaismt
Where	compte.numcpte		= remise_globale.numcpte
and	encaismt.codope	+ 0	= 4
and	encaismt.numencaismt in (
	Select	numencaismt
	From	remise_banque
	Where	remise_banque.numremise = remise_globale.numremise)
Union All
/*	5		Encaissement de cotisations
			Prelevement ->	Compte d'attente
			---------------------------			*/
Select	compte.numsoc,
	0						rolesoc,
	'encaismt'				sur_entite,
	encaismt.numencaismt	cle_unique,
	'encaismt'				entite,
	encaismt.numencaismt	cle,
	encaismt.idcompta		idcompta,
	20						codope,
	'C0200'					scdope,
	'CL1'					codjnal,
	5						type_ope,
	0 						cie,
	encaismt.numcli			indv,
	0 						gar,
	0 						int,
	compte.cmpt_gene 		bqe,
	Substr( to_char(remise_prelev.numremise, '00000000'), 2, 8 ) refpiece,
	remise_prelev.datrem 	dat_piece,
	encaismt.numencaismt	lib_piece_1,
	encaismt.numcli			lib_piece_2,
	0						montant1,
	0 						montant2,
	0 						montant3,
	0 						montant4,
	0 						montant5,
	encaismt.montant		montant6,
	encaismt.monnaie		devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From	compte,
	remise_prelev,
	encaismt
Where	compte.numcpte		= encaismt.numcpte
and	encaismt.codope	+ 0	= 4
and	encaismt.numencaismt in (
	Select	numencaismt
	From	prelevement
	Where	prelevement.numremise = remise_prelev.numremise
	)
Union All	/* ***************************** ANNULATIONS ****************************/
			/*		 Banque															*/
Select	compte.numsoc,
	0							rolesoc,
	'encaismt'					sur_entite,
	encaismt.numencaismt		cle_unique,
	'annul'						entite,
	annul_encais.numencaismt	cle,
	annul_encais.idcompta		idcompta,
	21							codope,
	'C9200'						scdope,
	'CL1'						codjnal,
	7							type_ope,
	0 							cie,
	encaismt.numcli				indv,
	0 							gar,
	0 							int,
	compte.cmpt_gene 			bqe,
	Substr( to_char(encaismt.numencaismt, '00000000'), 2, 8 )
								refpiece,
	annul_encais.date_annul		dat_piece,
	encaismt.refpmt				lib_piece_1,
	encaismt.numcli				lib_piece_2,
	abs(encaismt.montant) 		montant1,
	0							montant2,
	0 							montant3,
	0 							montant4,
	0 							montant5,
	0 							montant6,
	encaismt.monnaie			devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From	compte,
	encaismt,
	annul_encais
Where	compte.numcpte		= encaismt.numcpte
and	encaismt.numencaismt	= annul_encais.numencaismt
-- CTT on ne prend pas en compte les opérations techniques dont le compte comptable n'est pas renseigné
-- ...finalement la  saisie du compte comptable est rendue obligatoire dans la forme so12
--and compte.cmpt_gene is not null
Union All	/* ***************************** ANNULATIONS ****************************/
			/*		 Desaffectation cotisation										*/
Select	compte.numsoc,
	0							rolesoc,
	'encaismt'					sur_entite,
	compte_client.numencaismt	cle_unique,
	'compte_client'				entite,
	compte_client.idaffec		cle,
	compte_client.idcompta		idcompta,
	21							codope,
	'C9200'						scdope,
	'CL1'						codjnal,
	8							type_ope,
	0 							cie,
	encaismt.numcli				indv,
	0 							gar,
	0 							int,
	compte.cmpt_gene 			bqe,
	Substr( to_char(encaismt.numencaismt, '00000000'), 2, 8 )
								refpiece,
	annul_encais.date_annul		dat_piece,
	compte_client.numfact		lib_piece_1,
	compte_client.numcli		lib_piece_2,
	0							montant1,
	compte_client.montant		montant2,
	0 							montant3,
	0 							montant4,
	0 							montant5,
	0 							montant6,
	compte_client.monnaie		devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From	compte,
	annul_encais,
	encaismt,
	compte_client
Where	compte.numcpte		= encaismt.numcpte
and	annul_encais.numencaismt = encaismt.numencaismt
and	encaismt.numencaismt = compte_client.numencaismt
and	compte_client.montant < 0
and	compte_client.codope in (4, 8)
-- CTT on ne prend pas en compte les opérations techniques dont le compte comptable n'est pas renseigné
-- ...finalement la  saisie du compte comptable est rendue obligatoire dans la forme so12
--and compte.cmpt_gene is not null
Union All	/* ***************************** AFFECTATIONS *******************************/
			/*		Affectation COMPTE CLIENT -> cotisations 							*/
Select	compte.numsoc			numsoc,
	f_cpta_role(contrat.numgar,2,2)	rolesoc,
	'qttc'						sur_entite,
	qttc_global.numquit			cle_unique,
	'compte_client'				entite,
	compte_client.idaffec		cle,
	compte_client.idcompta		idcompta,
	25							codope,
	'C025'||f_cpta_role(contrat.numgar,2,2)	scdope,
	'ASSUR'						codjnal,
	9							type_ope,
	contrat.numorg 				cie,
	compte_client.numcli 		indv,
	0 							gar,
	0 							int,
	compte.cmpt_gene 			bqe,
	Substr( to_char(encaismt.numencaismt, '00000000'), 2, 8 )
								refpiece,
	encaismt.datpay 			dat_piece,
	qttc_global.numquit			lib_piece_1,
	qttc_global.numquerable		lib_piece_2,
	0							montant1,
	compte_client.montant		montant2,
	0 							montant3,
	0 							montant4,
	0 							montant5,
	-compte_client.montant		montant6,
	compte_client.monnaie		devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From
	compte,
	contrat,
	qttc_global,
	encaismt,
	compte_client
Where	compte.numcpte		= encaismt.numcpte
and	contrat.numgar		= qttc_global.numgar
and	qttc_global.numquit	= compte_client.numfact
and	encaismt.numencaismt	= compte_client.numencaismt
and	compte_client.montant	> 0
and	compte_client.codope	= 4
/* and Not Exists (
	Select	1
	From	idaffec_attente
	Where	idaffec_attente.idaffec = compte_client.idaffec)	*/
and Not Exists (
	Select	1
	From	idaffec_regul
	Where	idaffec_regul.idaffec = compte_client.idaffec)
Union All	/* ***************************** AFFECTATIONS *******************************/
			/*		Desaffectation de cotisations										*/
Select	compte.numsoc			numsoc,
	f_cpta_role(contrat.numgar,2,2)	rolesoc,
	'qttc'						sur_entite,
	qttc_global.numquit			cle_unique,
	'compte_client'				entite,
	compte_client.idaffec		cle,
	compte_client.idcompta		idcompta,
	26		 					codope,
	'C925'||f_cpta_role(contrat.numgar,2,2)	scdope,
	'ASSUR'						codjnal,
	10							type_ope,
	contrat.numorg 				cie,
	compte_client.numcli 		indv,
	0 							gar,
	0 							int,
	compte.cmpt_gene 			bqe,
	Substr( to_char(compte_client.idaffec, '00000000'), 2, 8 ) 	refpiece,
	compte_client.datope		dat_piece,
	qttc_global.numquit 		lib_piece_1,
	qttc_global.numquerable		lib_piece_2,
	0							montant1,
	compte_client.montant		montant2,
	0 							montant3,
	0 							montant4,
	0 							montant5,
	-compte_client.montant		montant6,
	compte_client.monnaie		devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From
	compte,
	contrat,
	qttc_global,
	encaismt,
	compte_client
Where	compte.numcpte		= encaismt.numcpte
and	contrat.numgar			= qttc_global.numgar
and	qttc_global.numquit		= compte_client.numfact
and	encaismt.numencaismt	= compte_client.numencaismt
and	compte_client.montant	< 0
and	compte_client.codope	= 4
and Exists (
	Select	1
	From	idaffec_attente,
		compte_client	attente
	Where	idaffec_attente.idaffec = compte_client.idaffec
		and	attente.idaffec = idaffec_attente.idaffec_attente
		and	attente.codope = 8)
GO
CREATE OR REPLACE PUBLIC SYNONYM V_CPTA_COTIS_ENCAIS FOR ARTHUS.V_CPTA_COTIS_ENCAIS
