CREATE FORCE VIEW ARTHUS.V_CPTA_COTIS_REVERS AS
Select
	compte.numsoc					numsoc,
	3								rolesoc,
	'qttc'							sur_entite,
	qttc_affec.numquit				cle_unique,
	'decaismt'						entite,
	decaismt.numdecaismt			cle,
	decaismt.idcompta				idcompta,
	30								codope,
	'C0303'							scdope,
	'CL1'							codjnal,
	1								type_ope,
	reversement.numorg				cie,
	qttc_global.numquerable			indv,
	qttc_affec.numfor				gar,
	0 								int,
	compte.cmpt_gene 				bqe,
	Substr(to_char(decaismt.numdecaismt, '00000000'), 2, 8) refpiece,
	reversement.datrevers 			dat_piece,
	qttc_affec.numquit				lib_piece_1,
	qttc_global.numquerable			lib_piece_2,
	Sum(qttc_affec.montant)
		- ARTHUS.pk_cotis.comm_prelev(	qttc_affec.numquit,
					qttc_affec.idrevers,
					qttc_affec.idaffec,
					qttc_affec.numfor,
					1,
					2)
		- ARTHUS.pk_cotis.mt_affec_tfc(qttc_affec.numquit,
					qttc_affec.idrevers,
					qttc_affec.idaffec,
					qttc_affec.numfor,
					'',
					1)                              montant1,
	ARTHUS.pk_cotis.comm_prelev(	qttc_affec.numquit,
				qttc_affec.idrevers,
				qttc_affec.idaffec,
				qttc_affec.numfor,
				1,
				2)	                                montant2,
	ARTHUS.pk_cotis.mt_affec_tfc(	qttc_affec.numquit,
				qttc_affec.idrevers,
				qttc_affec.idaffec,
				qttc_affec.numfor,
				2,
				2)                                	montant3,
	ARTHUS.pk_cotis.mt_affec_tfc(	qttc_affec.numquit,
				qttc_affec.idrevers,
				qttc_affec.idaffec,
				qttc_affec.numfor,
				'',
				3)
		+ ARTHUS.pk_cotis.mt_affec_tfc(qttc_affec.numquit,
					qttc_affec.idrevers,
					qttc_affec.idaffec,
					qttc_affec.numfor,
					'',
					4)                             	montant4,
	ARTHUS.pk_cotis.mt_affec_tfc(	qttc_affec.numquit,
				qttc_affec.idrevers,
				qttc_affec.idaffec,
				qttc_affec.numfor,
				'',
				1)				 					montant5,
	0 								montant6,
	qttc_affec.monnaie				devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From
	compte,
	qttc_global,
	qttc_affec,
	reversement,
	affectation,
	decaismt
Where	compte.numcpte		= decaismt.numcpte
and	qttc_global.numquit 	= qttc_affec.numquit
and	qttc_affec.idrevers 	= reversement.idrevers
and	reversement.idrevers	= affectation.numaffec
and	affectation.numdecaismt	= decaismt.numdecaismt
and	decaismt.codope			= 5
Group by
	compte.numsoc,
	qttc_affec.idrevers,
	qttc_affec.idaffec,
	qttc_global.numgar,
	qttc_affec.numquit,
	qttc_global.numquerable,
	decaismt.numdecaismt,
	decaismt.idcompta,
	decaismt.codope	,
	reversement.numorg,
	qttc_affec.numfor,
	qttc_affec.monnaie,
	compte.cmpt_gene ,
	reversement.idrevers,
	reversement.datrevers,
	reversement.debut
Union All	/*
			Reversement cotisations
			    Montant reverse
			-----------------------			*/
Select	compte.numsoc			numsoc,
	3							rolesoc,
	'decaismt'					sur_entite,
	decaismt.numdecaismt		cle_unique,
	'decaismt'					entite,
	decaismt.numdecaismt		cle,
	decaismt.idcompta			idcompta,
	30							codope,
	'C0303'						scdope,
	'CL1'						codjnal,
	2							type_ope,
	reversement.numorg			cie,
	reversement.numorg			indv,
	0							gar,
	0 							int,
	compte.cmpt_gene 			bqe,
	Substr(to_char(decaismt.numdecaismt, '00000000'),2, 8) refpiece,
	reversement.datrevers 		dat_piece,
	reversement.idrevers		lib_piece_1,
	reversement.numorg			lib_piece_2,
    0                        	montant1,
    0                        	montant2,
    0                        	montant3,
    0                        	montant4,
	0			 				montant5,
	decaismt.montant			montant6,
	decaismt.monnaie			devise,
	'V01'			VAR01,
	'V02'			VAR02,
	'V03'			VAR03,
	'V04'			VAR04,
	'V05'			VAR05,
	'V06'			VAR06,
	'V07'			VAR07,
	'V08'			VAR08,
	'V09'			VAR09,
	'V10'			VAR10,
	'V11'			VAR11,
	'V12'			VAR12,
	'V13'			VAR13,
	'V14'			VAR14,
	'V15'			VAR15,
	'V16'			VAR16,
	'V17'			VAR17,
	'V18'			VAR18,
	'V19'			VAR19,
	'V20'			VAR20,
	'V21'			VAR21,
	'V22'			VAR22,
	'V23'			VAR23,
	'V24'			VAR24,
	'V25'			VAR25,
	'V26'			VAR26,
	'V27'			VAR27,
	'V28'			VAR28,
	'V29'			VAR29,
	'V30'			VAR30
From	compte,
	reversement,
	affectation,
	decaismt
Where	compte.numcpte		= decaismt.numcpte
and	affectation.numaffec	= reversement.idrevers
and	affectation.numdecaismt = decaismt.numdecaismt
and	decaismt.codope			= 5
GO
CREATE OR REPLACE PUBLIC SYNONYM V_CPTA_COTIS_REVERS FOR ARTHUS.V_CPTA_COTIS_REVERS
