CREATE FORCE VIEW ARTHUS.V_DECOMPTE_CPTA AS
SELECT AUTRB,AUTRB_D,CPTCOMP,DATPAY,DEBIT,
          DEBIT_D,DEVISE_CT,DEVISE_EC,FLAGEDIT,IDCOMPTA,
          MODPMT,MONNAIE,MONNAIE_D,MONTANT,MONTANT_CT,
          MONTANT_D,MONTANT_EC,MTFRAIS,MTFRAIS_D,MTREEL,
          MTREEL_D,MTREMB,MTREMB_D,NBFEUILLE,NUMBENE,
          NUMBQUE,NUMDCPTCIE,NUMDEC,NUMDEST,NUMGAR,
          NUMINDIV,NUMPMT,REFPMT,ROLEDEST,SENS_EC,
          TYPBENE,TYPE_EC
     FROM decompte
UNION ALL
   SELECT AUTRB,AUTRB_D,CPTCOMP,DATPAY,DEBIT,
          DEBIT_D,DEVISE_CT,DEVISE_EC,FLAGEDIT,IDCOMPTA_INIT IDCOMPTA,
          MODPMT,MONNAIE,MONNAIE_D,MONTANT,MONTANT_CT,
          MONTANT_D,MONTANT_EC,MTFRAIS,MTFRAIS_D,MTREEL,
          MTREEL_D,MTREMB,MTREMB_D,NBFEUILLE,NUMBENE,
          NUMBQUE,NUMDCPTCIE,NUMDEC,NUMDEST,NUMGAR,
          NUMINDIV,NUMPMT,REFPMT,ROLEDEST,SENS_EC,
          TYPBENE,TYPE_EC
     FROM decompte_annul
    WHERE NOT EXISTS (
          SELECT 1
            FROM decompte
           WHERE decompte.numdec = decompte_annul.numdec )
GO
CREATE OR REPLACE PUBLIC SYNONYM V_DECOMPTE_CPTA FOR ARTHUS.V_DECOMPTE_CPTA
