CREATE FORCE VIEW ARTHUS.V_ECART_PIECE AS
SELECT ALL 1 NUMSOC,
		GRNTS.NUMCLI,
		F_NOM(GRNTS.NUMCLI, 32) NOMCLI,
		GRNTS.REFCIE_CHAPEAU,
		GRNTS.REFCIE,
		GRNTS.NUMGAR,
		ECART_PIECE.CODOPE,
		ECART_PIECE.MONTANT,
		ECART_PIECE.DATE_OPE,
		ECART_PIECE.TYPE_ECART TYPE,
		ECART_PIECE.NUMASSUREUR NUMORG,
		ECART_PIECE.NUMBDX NUMDCPTCIE,
		F_NOM(ECART_PIECE.NUMASSUREUR, 32) NOMORG,
		SINISTRE.NUMBENE,
		SINISTRE.NUMASSU,
		TO_CHAR(ECART_PIECE.DATE_OPE, 'YYYY') EXERCICE,
		GAR_CNTRT.NOMGAR,
		GAR_CNTRT.DATAPLI DATEDEB,
		GAR_CNTRT.DATPER DATEFIN
FROM GRNTS, SINISTRE, ECART_PIECE, GAR_CNTRT
	WHERE ((SINISTRE.NUMGAR = GRNTS.NUMGAR)
		AND (ECART_PIECE.NUMPIECE = SINISTRE.NUMSIN)
		AND (SINISTRE.NUMFOR = GAR_CNTRT.NUMFOR))
GO
CREATE OR REPLACE PUBLIC SYNONYM V_ECART_PIECE FOR ARTHUS.V_ECART_PIECE
