CREATE FORCE VIEW ARTHUS.V_GS22 AS
SELECT ALL SINISTRE_SANTE.NUM_DOSSIER,
    SINISTRE_SANTE.NUMLIGNE,
    SINISTRE_SANTE.SITUATION,
    F_LBLE('ET_DOSSPL', SINISTRE_SANTE.SITUATION) libSituLigne,
    SINISTRE_SANTE.MOTIF MotifLigne,
    F_LBLE('HISTO_DL'
    ||SINISTRE_SANTE.SITUATION, SINISTRE_SANTE.MOTIF) libMotifLigne,
    SINISTRE_SANTE.NUMUTIL,
    UTILISATEURS.NOM
  FROM SINISTRE_SANTE,
    UTILISATEURS
  WHERE SINISTRE_SANTE.NUMUTIL = UTILISATEURS.NUMUTIL
  ORDER BY SINISTRE_SANTE.NUM_DOSSIER,
    SINISTRE_SANTE.NUMLIGNE
GO
CREATE OR REPLACE PUBLIC SYNONYM V_GS22 FOR ARTHUS.V_GS22
