CREATE FORCE VIEW ARTHUS.V_GS23 AS
SELECT  HISTO_DOSSIER.DEBUT,
    HISTO_DOSSIER.ETAT,
    F_LBLE('ET_DOSSP', HISTO_DOSSIER.ETAT) libEtatDoss,
    HISTO_DOSSIER.MOTIF,
    F_LBLE('HISTO_D'
    ||HISTO_DOSSIER.ETAT, HISTO_DOSSIER.MOTIF) libMotifDoss,
    DOSSIER_SANTE.NUM_DOSSIER,
    DOSSIER_SANTE.NUMUTIL,
    UTILISATEURS.NOM
  FROM HISTO_DOSSIER,
    DOSSIER_SANTE,
    UTILISATEURS
  WHERE HISTO_DOSSIER.DEBUT =
    (SELECT MAX(H.DEBUT) FROM HISTO_DOSSIER H
    WHERE DOSSIER_SANTE.NUM_DOSSIER = H.NUM_DOSSIER
    )
  AND DOSSIER_SANTE.NUMUTIL = UTILISATEURS.NUMUTIL
  AND DOSSIER_SANTE.NUM_DOSSIER = HISTO_DOSSIER.NUM_DOSSIER
  GROUP BY DOSSIER_SANTE.NUM_DOSSIER,
    HISTO_DOSSIER.DEBUT,
    HISTO_DOSSIER.ETAT,
    HISTO_DOSSIER.MOTIF,
    DOSSIER_SANTE.NUMUTIL,
    UTILISATEURS.NOM
GO
CREATE OR REPLACE PUBLIC SYNONYM V_GS23 FOR ARTHUS.V_GS23
