CREATE FORCE VIEW ARTHUS.V_HISTO_TRAV_TRANSFERT AS
Select	distinct(histo_transfert.new_numgar)
From	histo_transfert
GO
CREATE OR REPLACE PUBLIC SYNONYM V_HISTO_TRAV_TRANSFERT FOR ARTHUS.V_HISTO_TRAV_TRANSFERT
