CREATE FORCE VIEW ARTHUS.V_LIST_DECAISMT AS
SELECT DISTINCT DECAISMT.NUMDECAISMT,
                DECAISMT.NUMEDIT,
                DECAISMT.CODOPE,
                DECAISMT.NUMCPTE,
                DECAISMT.MODPMT,
                DECAISMT.NUMBENE,
                DECAISMT.REFPMT,
                DECAISMT.DATEDIT,
                DECAISMT.MONTANT,
                DECAISMT.MONTANT_D,
                DECAISMT.MONNAIE,
                DECAISMT.MONNAIE_D
  FROM ARTHUS.DECAISMT, ARTHUS.AFFECTATION, ARTHUS.DCPT, ARTHUS.PRMT, ARTHUS.SNTR
 WHERE DECAISMT.NUMDECAISMT = AFFECTATION.NUMDECAISMT
   AND DECAISMT.NUMUTIL >= 0
   AND DECAISMT.FLAGPAY = DECODE(DECAISMT.MODPMT, PRMT.MDCHQ, -1, 1)
   AND DCPT.NUMDEC = AFFECTATION.NUMAFFEC
   AND SNTR.NUMDEC = DCPT.NUMDEC
   AND SNTR.EDTDCPT = 1
GO
CREATE OR REPLACE PUBLIC SYNONYM V_LIST_DECAISMT FOR ARTHUS.V_LIST_DECAISMT
