CREATE FORCE VIEW ARTHUS.V_LIG_DOSS_SIMPLE AS
select "NUM_DOSSIER","NUMLIGNE","NUMINDIV","DATSIN","CODPAYS","CODFRAIS","COD_ICD9","QUANTITE","COEFF","DEVISE_IN","DEVISE_OUT","DEVISE_AUTRB","MTFRAIS_IN","MTFRAIS","SITUATION","MOTIF","AUTRB_DAUTRB","AUTRB","TAUX","BASEREMB","MTREMB","MTREMB_REEL","MTPREST","MTPREST_REEL","MT_BANQUE","CREATION","MAJ","NUMUTIL","REFERENCE","D_ED_FL","DATSIN_FIN","TYP_ELT","ELT_CORP","EXCLUSION","BLOCAGE","NUMORG","NUM_BORD","NUMENVOI","NUMFACT","FRCG","FRCG1","FRCG2","FRCG3","FRCG4","FRCG5","FRCG6","FRCG7","FRCG8","FRCG9","FRCG10","NUMASSU_RC","NUMANNUL","NUMORIGINE"
from sinistre_sante
where numannul is null
and (num_dossier, numligne) not in
	(select num_dossier, numorigine
	 from sinistre_sante
	 where numorigine is not null
	 UNION
	 select num_dossier, numannul
	 from sinistre_sante
	 where numannul is not null)
GO
CREATE OR REPLACE PUBLIC SYNONYM V_LIG_DOSS_SIMPLE FOR ARTHUS.V_LIG_DOSS_SIMPLE
