CREATE FORCE VIEW ARTHUS.V_OP_EC AS
SELECT DISTINCT REMISE_OP_DETAIL.NUMREMISE,
			REMISE_OP_DETAIL.NUMVIREMENT,
			SUM(REMISE_OP_DETAIL.MONTANT) MONTANT,
			REMISE_OP_DETAIL.MONNAIE,
			SUM(REMISE_OP_DETAIL.MONTANT_D) MONTANT_D,
			REMISE_OP_DETAIL.MONNAIE_D,
			SUM(REMISE_OP_DETAIL.MONTANT_CT) MONTANT_CT,
			REMISE_OP_DETAIL.MONNAIE_CT,
			SUM(REMISE_OP_DETAIL.MONTANT_EC) MONTANT_EC,
			REMISE_OP_DETAIL.DEVISE_EC,
			REMISE_OP_DETAIL.INTITULE
	FROM REMISE_OP_DETAIL
	GROUP BY REMISE_OP_DETAIL.NUMVIREMENT,
			 REMISE_OP_DETAIL.INTITULE,
			 REMISE_OP_DETAIL.MONNAIE_D,
			 REMISE_OP_DETAIL.MONNAIE,
			 REMISE_OP_DETAIL.NUMCPTE,
			 REMISE_OP_DETAIL.NUMREMISE,
			 REMISE_OP_DETAIL.DEVISE_EC,
			 REMISE_OP_DETAIL.MONNAIE_CT
GO
CREATE OR REPLACE PUBLIC SYNONYM V_OP_EC FOR ARTHUS.V_OP_EC
