CREATE FORCE VIEW ARTHUS.V_PAPIER_OPE AS
select  "CODOPE","NUMCPTE","MODPMT","PAPID","DEFAUT","SUPPORT" from papier_ope
where   defaut is not null
GO
CREATE OR REPLACE PUBLIC SYNONYM V_PAPIER_OPE FOR ARTHUS.V_PAPIER_OPE
