CREATE FORCE VIEW ARTHUS.V_PRICHARGE AS
select	contrat.numinterm			numsoc,
	pricharge.numpc,
	pricharge.numindiv,
	pricharge.numassu,
	tiers.numindiv			numtiers,
	pricharge.numentree,
	pricharge.numfact,
	pricharge.datehospi			dathspt,
	to_char(pricharge.datehospi,'dd/mm/yyyy')	edatehospi,
	to_char(pricharge.datedit,'dd/mm/yyyy')	edatedit,
	to_char(pricharge.datpay,'dd/mm/yyyy')	edatpay,
	to_char(pricharge.datecreat,'dd/mm/yyyy')	datecreat,
	indvs_indiv.refcie	refcie_indiv,
	indvs_indiv.nom		nom_indiv,
	indvs_indiv.nomjf	nomjf_indiv,
	indvs_indiv.prenom	prenom_indiv,
	to_char(indvs_indiv.datnais,'dd/mm/yyyy')	edatnais_indiv,
	indvs_indiv.matorg	matorg_indiv,
	indvs_indiv.orgbase	orgbase,
	indvs_assu.refcie	refcie_assu,
	indvs_assu.nom		nom_assu,
	indvs_assu.nomjf	nomjf_assu,
	indvs_assu.prenom	prenom_assu,
	indvs_assu.matorg	matorg_assu,
	tiers.numdpt,
	tiers.numactv,
	tiers.numinser,
	tiers.numcle,
	tiers.nomp		nom_tiers,
        tiers.adr1p		adr1_tiers,
	tiers.adr2p		adr2_tiers,
	tiers.codposp		codpos_tiers,
	tiers.villep		ville_tiers,
	rib.modpmt,
        rib.codbque,
	rib.guichet,
	rib.compte,
	rib.clerib,
	rib.intitule,
	rib.bban,
	rib.clef_iban,
	rib.bic,
	tiers.numindiv numindiv_tiers,
	tiers.nom nomtiers,
	tiers.adr1 adr1tiers,
	tiers.adr2 adr2tiers,
	tiers.codpos codpostiers,
	tiers.ville villetiers,
	'P.C. N°'||pricharge.numpc||
		' Etbl.:'||tiers.numindiv||' - '||tiers.nom||
		' Hspt.Le '||to_char(pricharge.datehospi,'dd/mm/yy') contexte,
	contrat.numgar,
	contrat.refcie		refcie_contrat,
	indvs_cli.nom		cli_nom,
	indvs_cli.prenom	cli_prenom,
	decode(pricharge.typedest,
		1,indvs_assu.nom,
		2,tiers.nomp)		dest_nom,
	decode(pricharge.typedest,
		1,indvs_assu.prenom,
		2,'')			dest_prenom,
	decode(pricharge.typedest,
		1,indvs_assu.adr1,
        	2,tiers.adr1p)		dest_adr1,
	decode(pricharge.typedest,
		1,indvs_assu.adr2,
		2,tiers.adr2p)		dest_adr2,
	decode(pricharge.typedest,
		1,indvs_assu.codpos,
		2,tiers.codposp)	dest_codpos,
	decode(pricharge.typedest,
		1,indvs_assu.ville,
		2,tiers.villep)		dest_ville,
	pricharge.typedest
from	indvs indvs_indiv,
	indvs indvs_assu,
	indvs indvs_cli,
	tiers,
	contrat,
	pricharge,
	rib
where	indvs_indiv.numindiv	= pricharge.numindiv
and	indvs_assu.numindiv	= pricharge.numassu
and	indvs_cli.numindiv	= contrat.numcli
and	contrat.numgar	= pricharge.numgar
and	tiers.numtiers	= pricharge.numtiers
and	rib.idrib=f_bene_rib(tiers.numindiv,1,contrat.numgar,1)
and	rib.numindiv=tiers.numindiv
GO
CREATE OR REPLACE PUBLIC SYNONYM V_PRICHARGE FOR ARTHUS.V_PRICHARGE
