CREATE FORCE VIEW ARTHUS.V_SINISTRE_CPTA2 AS
SELECT CODFRAIS,NUMGAR, NUMINDIV, DATSIN, MTPREST,
          MTREMB,MTFRAIS,DATSAI,NBACTE,AUTRB,
          MTFRAN,SENS,MTMAX,MTREEL,NUMDEC,
          NUMASSU,NUMBENE,NUMSIN,NUMANNUL,USERNAME,
          FLAGAM,TYPBENE,NUMPOPU,NUMFOR,
          NUMMATH,NUMPC,X,IDADHESION,FLAG_REGIME,
          MONNAIE,EDTDCPT,NUMASSU_RC,NUMDEC_RC,DATEDIT_RC,
          NUMDCPTCIE,PDSQLS,SPE_EXE,FRA_DEP,RACMON
     FROM SINISTRE
    WHERE SINISTRE.numdec != 0
UNION ALL
   SELECT CODFRAIS,NUMGAR, NUMINDIV, DATSIN, MTPREST,
          MTREMB,MTFRAIS,DATSAI,NBACTE,AUTRB,
          MTFRAN,SENS,MTMAX,MTREEL,NUMDEC,
          NUMASSU,NUMBENE,NUMSIN,NUMANNUL,USERNAME,
          FLAGAM,TYPBENE,NUMPOPU,NUMFOR,
          NUMMATH,NUMPC,X,IDADHESION,FLAG_REGIME,
          MONNAIE,EDTDCPT,NUMASSU_RC,NUMDEC_RC,DATEDIT_RC,
          NUMDCPTCIE,PDSQLS,SPE_EXE,FRA_DEP,RACMON
     FROM SINISTRE_ANNUL
GO
CREATE OR REPLACE PUBLIC SYNONYM V_SINISTRE_CPTA2 FOR ARTHUS.V_SINISTRE_CPTA2
