CREATE FORCE VIEW ARTHUS.V_SINISTRE_RPT AS
SELECT CODFRAIS, NUMGAR, NUMINDIV, DATSIN, MTPREST, MTREMB, MTFRAIS, 
  DATSAI, NBACTE, AUTRB, MTFRAN, SENS, MTMAX, MTREEL, NUMDEC, NUMASSU, 
  NUMBENE, NUMSIN, NUMANNUL, USERNAME, FLAGAM, TYPBENE, NUMPOPU,
  NUMFOR, NUM_FACT, NUMMATH, NUMPC, X, IDADHESION, PDSQLS, SPE_EXE, 
  FRA_DEP, RACMON, DATEDIT_RC, EDTDCPT, MONNAIE, NUMASSU_RC, 
  NUMDCPTCIE, NUMDEC_RC, FLAG_REGIME 
    FROM SINISTRE 
        WHERE DATSAI > SYSDATE - 500
GO
CREATE OR REPLACE PUBLIC SYNONYM V_SINISTRE_RPT FOR ARTHUS.V_SINISTRE_RPT
