CREATE FORCE VIEW ARTHUS.V_STATUTS_LIG_DOSS AS
SELECT 100 ORDRE, NUM_DOSSIER, NUMLIGNE, NULL STDATE, '       LIQUIDATION' LIB
  FROM ARTHUS.SINISTRE_SANTE
UNION
SELECT ((HISTO_SINISTRE_SANTE.HISTO_SNTR_SANTE * 0.000000000001) + 110) ORDRE,
       HISTO_SINISTRE_SANTE.NUM_DOSSIER,
       HISTO_SINISTRE_SANTE.NUMLIGNE,
       TO_DATE(HISTO_SINISTRE_SANTE.DATETAT, 'dd/mm/yyyy') STDATE,
       (SELECT LIBELLE
          FROM ARTHUS.LIBELLE
         WHERE MNEMO = 'ET_DOSSPL'
           AND CODE = HISTO_SINISTRE_SANTE.ETAT) LIB
  FROM ARTHUS.HISTO_SINISTRE_SANTE
UNION
SELECT 150 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(DATPAY, 'dd/mm/yyyy') STDATE, 'Décomptée' LIB
  FROM ARTHUS.DCPT, ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER
 WHERE SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMDEC = DCPT.NUMDEC
UNION
SELECT 160 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(FILE_EDITION.DATE_EXECUTE, 'dd/mm/yyyy') STDATE, 'Décompte éditée' LIB
  FROM ARTHUS.DCPT, ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER, ARTHUS.AFFECTATION, ARTHUS.DECAISMT, ARTHUS.FILE_EDITION
 WHERE SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMDEC = DCPT.NUMDEC
   AND DCPT.NUMDEC = AFFECTATION.NUMAFFEC
   AND AFFECTATION.NUMDECAISMT = DECAISMT.NUMDECAISMT
   AND DECAISMT.NUMEDIT > 0
   AND FILE_EDITION.NUMEDIT = DECAISMT.NUMEDIT
UNION
SELECT 170 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(REMISE_VIRE.DATREM, 'dd/mm/yyyy') STDATE, 'Payée par virement' LIB
  FROM ARTHUS.DCPT, ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER, ARTHUS.AFFECTATION, ARTHUS.DECAISMT, ARTHUS.REMISE_VIRE_DETAIL, ARTHUS.REMISE_VIRE
 WHERE SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMDEC = DCPT.NUMDEC
   AND DCPT.NUMDEC = AFFECTATION.NUMAFFEC
   AND AFFECTATION.NUMDECAISMT = DECAISMT.NUMDECAISMT
   AND REMISE_VIRE_DETAIL.NUMREMISE = DECAISMT.REFPMT
   AND REMISE_VIRE.NUMREMISE = REMISE_VIRE_DETAIL.NUMREMISE
UNION
SELECT 180 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(REMISE_OP.DATREM, 'dd/mm/yyyy') STDATE, 'Payée par ordre de paiement' LIB
  FROM ARTHUS.DCPT, ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER, ARTHUS.AFFECTATION, ARTHUS.DECAISMT, ARTHUS.REMISE_OP_DETAIL, ARTHUS.REMISE_OP
 WHERE SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMDEC = DCPT.NUMDEC
   AND DCPT.NUMDEC = AFFECTATION.NUMAFFEC
   AND AFFECTATION.NUMDECAISMT = DECAISMT.NUMDECAISMT
   AND REMISE_OP_DETAIL.NUMREMISE = DECAISMT.REFPMT
   AND REMISE_OP.NUMREMISE = REMISE_OP_DETAIL.NUMREMISE
UNION
SELECT 200 ORDRE, NUM_DOSSIER, NUMLIGNE, NULL STDATE, '       C F E' LIB
  FROM ARTHUS.SINISTRE_SANTE
UNION
SELECT 230 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(D_ED_FL, 'dd/mm/yyyy') STDATE, 'Fiche navette éditée' LIB
  FROM ARTHUS.SINISTRE_SANTE
 WHERE D_ED_FL IS NOT NULL
   AND NUMORG IS NOT NULL
UNION
SELECT 240 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(D_ED_FL, 'dd/mm/yyyy') STDATE, 'Fiche navette à éditer' LIB
  FROM ARTHUS.SINISTRE_SANTE
 WHERE D_ED_FL IS NULL
   AND NUMORG IS NOT NULL
UNION
SELECT 250 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(DATFACT, 'dd/mm/yyyy') STDATE, 'Affectée CFE' LIB
  FROM ARTHUS.SINISTRE_SANTE, ARTHUS.FACTURE
 WHERE FACTURE.NUMFACT = SINISTRE_SANTE.NUMFACT
   AND FACTURE.CODOPE = 12
UNION
SELECT 260 ORDRE, NUM_DOSSIER, NUMLIGNE, NULL STDATE, 'Non affectée CFE' LIB
  FROM ARTHUS.SINISTRE_SANTE
 WHERE SINISTRE_SANTE.NUMFACT IS NULL
   AND SINISTRE_SANTE.NUMORG IS NOT NULL
UNION
SELECT 300 ORDRE, NUM_DOSSIER, NUMLIGNE, NULL STDATE, '       ASSUREUR COMPLEMENTAIRE' LIB
  FROM ARTHUS.SINISTRE_SANTE
UNION
SELECT 310 ORDRE, SINISTRE_SANTE.NUM_DOSSIER, SINISTRE_SANTE.NUMLIGNE, NULL STDATE, 'Pas d''assureur complémentaire' LIB
  FROM ARTHUS.SINISTRE_SANTE
 WHERE SINISTRE_SANTE.NUMASSU_RC IS NULL
UNION
SELECT 330 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(DATEDIT_RC, 'dd/mm/yyyy') STDATE, 'Décompte RC non édité' LIB
  FROM ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER
 WHERE SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMASSU_RC IS NOT NULL
   AND SINISTRE.NUMDEC_RC IS NULL
UNION
SELECT 340 ORDRE, NUM_DOSSIER, NUMLIGNE, TO_DATE(DATEDIT_RC, 'dd/mm/yyyy') STDATE, 'Décompte RC édité' LIB
  FROM ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER
 WHERE SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMASSU_RC IS NOT NULL
   AND SINISTRE.NUMDEC_RC IS NOT NULL
UNION
SELECT ALL 350 ORDRE,
       SNTR_DOSSIER.NUM_DOSSIER,
       SNTR_DOSSIER.NUMLIGNE,
       TO_DATE(DCPTCIE.DATCREAT, 'dd/mm/yyyy') STDATE,
       'Dde de remb. en attente de validation' LIB
  FROM ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER, ARTHUS.DCPTCIE
 WHERE SINISTRE.NUMASSU_RC IS NOT NULL
   AND SINISTRE.NUMDEC_RC IS NOT NULL
   AND SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMDCPTCIE = DCPTCIE.NUMDCPTCIE
UNION
SELECT ALL 360 ORDRE,
       SNTR_DOSSIER.NUM_DOSSIER,
       SNTR_DOSSIER.NUMLIGNE,
       TO_DATE(FACTURE.DATFACT, 'dd/mm/yyyy') STDATE,
       'Dde de remboursement validée' LIB
  FROM ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER, ARTHUS.DCPTCIE, ARTHUS.FACTURE
 WHERE SINISTRE.NUMASSU_RC IS NOT NULL
   AND SINISTRE.NUMDEC_RC IS NOT NULL
   AND FACTURE.CODOPE = 12
   AND SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMDCPTCIE = DCPTCIE.NUMDCPTCIE
   AND SINISTRE.NUM_FACT = FACTURE.NUMFACT
UNION
SELECT ALL 370 ORDRE,
       SNTR_DOSSIER.NUM_DOSSIER,
       SNTR_DOSSIER.NUMLIGNE,
       TO_DATE(ENCAISMT.DATPAY, 'dd/mm/yyyy') STDATE,
       'Remboursement effectué' LIB
  FROM ARTHUS.SINISTRE, ARTHUS.SNTR_DOSSIER, ARTHUS.DCPTCIE, ARTHUS.FACTURE, ARTHUS.COMPTE_CLIENT, ARTHUS.ENCAISMT
 WHERE SINISTRE.NUMASSU_RC IS NOT NULL
   AND SINISTRE.NUMDEC_RC IS NOT NULL
   AND FACTURE.CODOPE = 12
   AND SINISTRE.NUMSIN = SNTR_DOSSIER.NUMSIN_SNTR
   AND SINISTRE.NUMDCPTCIE = DCPTCIE.NUMDCPTCIE
   AND SINISTRE.NUM_FACT = FACTURE.NUMFACT
   AND FACTURE.CODOPE = COMPTE_CLIENT.CODOPE
   AND COMPTE_CLIENT.NUMENCAISMT = ENCAISMT.NUMENCAISMT
   AND SINISTRE.NUMASSU_RC = COMPTE_CLIENT.NUMCLI
UNION
SELECT 400 ORDRE, NUM_DOSSIER, NUMLIGNE, NULL STDATE, '       BANQUE' LIB
  FROM ARTHUS.SINISTRE_SANTE
UNION
SELECT ALL 410 ORDRE,
       SNTR_DOSSIER.NUM_DOSSIER,
       SNTR_DOSSIER.NUMLIGNE,
       TO_DATE(CREATION, 'dd/mm/yyyy') STDATE,
       'Pas d''écart constaté' LIB
  FROM ARTHUS.SINISTRE_DEV, ARTHUS.SNTR_DOSSIER, ARTHUS.SINISTRE_SANTE
 WHERE SINISTRE_DEV.MTPREST_IN = SINISTRE_DEV.MTPREST_OUT
   AND SNTR_DOSSIER.NUMLIGNE = SINISTRE_SANTE.NUMLIGNE
   AND SNTR_DOSSIER.NUM_DOSSIER = SINISTRE_SANTE.NUM_DOSSIER
   AND SNTR_DOSSIER.NUMSIN_SNTR = SINISTRE_DEV.NUMSIN
GO
CREATE OR REPLACE PUBLIC SYNONYM V_STATUTS_LIG_DOSS FOR ARTHUS.V_STATUTS_LIG_DOSS
