CREATE FORCE VIEW ARTHUS.V_SUIVI_FACT_TPE AS
select "CODADELI","NUMFACT","NUMREMISE_IMPORT","NUMREMISE_EXPORT","DATFACT","CODBENEFINSEE","CODBENEFCLE","DATNAIBENEF","CODTYPFACT","DATRECEPTOR","DATLIMIAMC","NUMCOMPOS","CODAMCDET","IDCPTEBQ","REFFIN","TYPAVIREG","CODEVEFAC","MONTANT","IDFACTPE","RANGBENEF","USER_FORCAGE","DATTRAIT","ETAT" from v_fact_tpe_import
UNION ALL
select  "CODADELI","NUMFACT","NUMREMISE_IMPORT","NUMREMISE_EXPORT","DATFACT","CODBENEFINSEE","CODBENEFCLE","DATNAIBENEF","CODTYPFACT","DATRECEPTOR","DATLIMIAMC","NUMCOMPOS","CODAMCDET","IDCPTEBQ","REFFIN","TYPAVIREG","CODEVEFAC","MONTANT","IDFACTPE","RANGBENEF","USER_FORCAGE","DATTRAIT","ETAT" from v_fact_tpe_encours
UNION ALL
select "CODADELI","NUMFACT","NUMREMISE_IMPORT","NUMREMISE_EXPORT","DATFACT","CODBENEFINSEE","CODBENEFCLE","DATNAIBENEF","CODTYPFACT","DATRECEPTOR","DATLIMIAMC","NUMCOMPOS","CODAMCDET","IDCPTEBQ","REFFIN","TYPAVIREG","CODEVEFAC","MONTANT","IDFACTPE","RANGBENEF","USER_FORCAGE","DATTRAIT","ETAT" from v_fact_tpe_anomalie
UNION ALL
select "CODADELI","NUMFACT","NUMREMISE_IMPORT","NUMREMISE_EXPORT","DATFACT","CODBENEFINSEE","CODBENEFCLE","DATNAIBENEF","CODTYPFACT","DATRECEPTOR","DATLIMIAMC","NUMCOMPOS","CODAMCDET","IDCPTEBQ","REFFIN","TYPAVIREG","CODEVEFAC","MONTANT","IDFACTPE","RANGBENEF","USER_FORCAGE","DATTRAIT","ETAT" from v_fact_tpe_rejet
UNION ALL
select "CODADELI","NUMFACT","NUMREMISE_IMPORT","NUMREMISE_EXPORT","DATFACT","CODBENEFINSEE","CODBENEFCLE","DATNAIBENEF","CODTYPFACT","DATRECEPTOR","DATLIMIAMC","NUMCOMPOS","CODAMCDET","IDCPTEBQ","REFFIN","TYPAVIREG","CODEVEFAC","MONTANT","IDFACTPE","RANGBENEF","USER_FORCAGE","DATTRAIT","ETAT" from v_fact_tpe_accepte
UNION ALL
select "CODADELI","NUMFACT","NUMREMISE_IMPORT","NUMREMISE_EXPORT","DATFACT","CODBENEFINSEE","CODBENEFCLE","DATNAIBENEF","CODTYPFACT","DATRECEPTOR","DATLIMIAMC","NUMCOMPOS","CODAMCDET","IDCPTEBQ","REFFIN","TYPAVIREG","CODEVEFAC","MONTANT","IDFACTPE","RANGBENEF","USER_FORCAGE","DATTRAIT","ETAT" from v_fact_tpe_paye
UNION ALL
select "CODADELI","NUMFACT","NUMREMISE_IMPORT","NUMREMISE_EXPORT","DATFACT","CODBENEFINSEE","CODBENEFCLE","DATNAIBENEF","CODTYPFACT","DATRECEPTOR","DATLIMIAMC","NUMCOMPOS","CODAMCDET","IDCPTEBQ","REFFIN","TYPAVIREG","CODEVEFAC","MONTANT","IDFACTPE","RANGBENEF","USER_FORCAGE","DATTRAIT","ETAT" from v_fact_tpe_payeautorite
UNION ALL
select "CODADELI","NUMFACT","NUMREMISE_IMPORT","NUMREMISE_EXPORT","DATFACT","CODBENEFINSEE","CODBENEFCLE","DATNAIBENEF","CODTYPFACT","DATRECEPTOR","DATLIMIAMC","NUMCOMPOS","CODAMCDET","IDCPTEBQ","REFFIN","TYPAVIREG","CODEVEFAC","MONTANT","IDFACTPE","RANGBENEF","USER_FORCAGE","DATTRAIT","ETAT" from v_fact_tpe_rejetAMC
GO
CREATE OR REPLACE PUBLIC SYNONYM V_SUIVI_FACT_TPE FOR ARTHUS.V_SUIVI_FACT_TPE
