CREATE FORCE VIEW ARTHUS.V_TIERS_NON_SOLDE AS
SELECT ALL V_TIERS_BALANCE.NUMINDIV,
				V_TIERS_BALANCE.TIERS,
				SUM(V_TIERS_BALANCE.DEBIT+V_TIERS_BALANCE.CREDIT) solde,
				SUM(V_TIERS_BALANCE.DEBIT_D+V_TIERS_BALANCE.CREDIT_D) solde_d,
				V_TIERS_BALANCE.MONNAIE,
				V_TIERS_BALANCE.MONNAIE_D
	FROM V_TIERS_BALANCE
	GROUP BY V_TIERS_BALANCE.NUMINDIV,
				V_TIERS_BALANCE.TIERS,
				V_TIERS_BALANCE.MONNAIE,
				V_TIERS_BALANCE.MONNAIE_D
GO
CREATE OR REPLACE PUBLIC SYNONYM V_TIERS_NON_SOLDE FOR ARTHUS.V_TIERS_NON_SOLDE
