CREATE FORCE VIEW ARTHUS.V_TRTAVT2 AS
SELECT  TR.NUMTR        NUMTR,
        TR.LIBINTTR     LIBINTTR,
        AV.NUMAV        NUMAV,
        AV.LIBINTAV     LIBINTAV,
        AV.DATEFFAV     DATEFFAV,
        AV.DATFINAV     DATFINAV,
        TRT_PROD.NUMPROD NUMPROD
FROM    TRAITE  TR,
        AVENANT AV,
        TRT_PRODUIT TRT_PROD
WHERE   AV.NUMTR = TR.NUMTR
AND     AV.VALIDEAV = 'O'
AND     TR.NUMTR = TRT_PROD.NUMTR
AND     AV.TYPAV = '2'
GO
CREATE OR REPLACE PUBLIC SYNONYM V_TRTAVT2 FOR ARTHUS.V_TRTAVT2
