CREATE FORCE VIEW ARTHUS.VS_GRNTS AS
select "NUMGAR","NUMGAR_REF","REFCIE","REFCIE_CHAPEAU","NUMORG","NUMPROD","NUMCLI","NUMINTERM","NUMUTIL","TYPGAR","COLLEGE","MODE_GESTION","TYPE_CONTRAT","DATSOUS","DATEFF","GEST_COTIS","NAT_CALC","TYPE_TERME","TYPEQUIT","TYPE_CALC","MODE_CALCUL","FRACT","ARRONDI","MREGL","ECHE_ANNIV","REVISION","DELAI","NUMQUERABLE","DELEGATAIRE","DESTINATAIRE","GEST_PREST","DELEG_PREST","DERECHE","ECHESUIV","CELLULE","RENOUV","TYPE_ECHE" from contrat
where exists (select 1 from util_soc
                 where  util_soc.numutil = f_numutil
		 and    util_soc.numsoc = contrat.numinterm)
GO
CREATE OR REPLACE SYNONYM ARTHUS.GRNTS FOR ARTHUS.VS_GRNTS

GO
CREATE OR REPLACE PUBLIC SYNONYM GRNTS FOR ARTHUS.VS_GRNTS

GO
CREATE OR REPLACE PUBLIC SYNONYM VS_GRNTS FOR ARTHUS.VS_GRNTS
