-- Synonyme PUBLIC : F_ADHESION_EXTERNE
-- Cible      : ARTHUS.F_ADHESION_EXTERNE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_ADHESION_EXTERNE FOR ARTHUS.F_ADHESION_EXTERNE;
