-- Synonyme PUBLIC : F_ADHE_SOUSCRIPTION
-- Cible      : ARTHUS.F_ADHE_SOUSCRIPTION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_ADHE_SOUSCRIPTION FOR ARTHUS.F_ADHE_SOUSCRIPTION;
