-- Synonyme PUBLIC : F_ADHESION_INDIV
-- Cible      : ARTHUS.F_ADHESION_INDIV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_ADHESION_INDIV FOR ARTHUS.F_ADHESION_INDIV;
