-- Synonyme PUBLIC : F_ANO_TIERS_PAYANT
-- Cible      : ARTHUS.F_ANO_TIERS_PAYANT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_ANO_TIERS_PAYANT FOR ARTHUS.F_ANO_TIERS_PAYANT;
