-- Synonyme PUBLIC : F_CALCUL_PLAFOND
-- Cible      : ARTHUS.F_CALCUL_PLAFOND
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CALCUL_PLAFOND FOR ARTHUS.F_CALCUL_PLAFOND;
