-- Synonyme PUBLIC : F_CALCUL_SINISTRE_DEV
-- Cible      : ARTHUS.F_CALCUL_SINISTRE_DEV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CALCUL_SINISTRE_DEV FOR ARTHUS.F_CALCUL_SINISTRE_DEV;
