-- Synonyme PUBLIC : F_CODE_REGROUPEMENT
-- Cible      : ARTHUS.F_CODE_REGROUPEMENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CODE_REGROUPEMENT FOR ARTHUS.F_CODE_REGROUPEMENT;
