-- Synonyme PUBLIC : F_CONTREPARTIE_D
-- Cible      : ARTHUS.F_CONTREPARTIE_D
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CONTREPARTIE_D FOR ARTHUS.F_CONTREPARTIE_D;
