-- Synonyme PUBLIC : F_CONTEXTE_INTERM
-- Cible      : ARTHUS.F_CONTEXTE_INTERM
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CONTEXTE_INTERM FOR ARTHUS.F_CONTEXTE_INTERM;
