-- Synonyme PUBLIC : F_COMM_A_PRELEVER
-- Cible      : ARTHUS.F_COMM_A_PRELEVER
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_COMM_A_PRELEVER FOR ARTHUS.F_COMM_A_PRELEVER;
