-- Synonyme PUBLIC : F_CONVERT_MONTANT
-- Cible      : ARTHUS.F_CONVERT_MONTANT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CONVERT_MONTANT FOR ARTHUS.F_CONVERT_MONTANT;
