-- Synonyme PUBLIC : F_CPTA_ROLE_FORCE
-- Cible      : ARTHUS.F_CPTA_ROLE_FORCE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_ROLE_FORCE FOR ARTHUS.F_CPTA_ROLE_FORCE;
