-- Synonyme PUBLIC : F_CPTA_DATE_DECAISMT
-- Cible      : ARTHUS.F_CPTA_DATE_DECAISMT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_DATE_DECAISMT FOR ARTHUS.F_CPTA_DATE_DECAISMT;
