-- Synonyme PUBLIC : F_CPTA_TRESO_VALIDE
-- Cible      : ARTHUS.F_CPTA_TRESO_VALIDE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_TRESO_VALIDE FOR ARTHUS.F_CPTA_TRESO_VALIDE;
