-- Synonyme PUBLIC : F_CPTA_ROLE_TEST
-- Cible      : ARTHUS.F_CPTA_ROLE_TEST
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_ROLE_TEST FOR ARTHUS.F_CPTA_ROLE_TEST;
