-- Synonyme PUBLIC : F_CPTA_INTERM_SANTE
-- Cible      : ARTHUS.F_CPTA_INTERM_SANTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_INTERM_SANTE FOR ARTHUS.F_CPTA_INTERM_SANTE;
