-- Synonyme PUBLIC : F_CPTA_LIB_ANNUL_ENCAIS
-- Cible      : ARTHUS.F_CPTA_LIB_ANNUL_ENCAIS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_LIB_ANNUL_ENCAIS FOR ARTHUS.F_CPTA_LIB_ANNUL_ENCAIS;
