-- Synonyme PUBLIC : F_CPTA_LIB_ENCAISMT
-- Cible      : ARTHUS.F_CPTA_LIB_ENCAISMT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_LIB_ENCAISMT FOR ARTHUS.F_CPTA_LIB_ENCAISMT;
