-- Synonyme PUBLIC : F_CPTA_LIB_REG_DEC_COURT
-- Cible      : ARTHUS.F_CPTA_LIB_REG_DEC_COURT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_LIB_REG_DEC_COURT FOR ARTHUS.F_CPTA_LIB_REG_DEC_COURT;
