-- Synonyme PUBLIC : F_CPTA_DATE_CONSTATATION
-- Cible      : ARTHUS.F_CPTA_DATE_CONSTATATION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_DATE_CONSTATATION FOR ARTHUS.F_CPTA_DATE_CONSTATATION;
