-- Synonyme PUBLIC : F_CPT_ETAT_REMISE
-- Cible      : ARTHUS.F_CPT_ETAT_REMISE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPT_ETAT_REMISE FOR ARTHUS.F_CPT_ETAT_REMISE;
