-- Synonyme PUBLIC : F_CPTA_TYPE_DEV_ENC
-- Cible      : ARTHUS.F_CPTA_TYPE_DEV_ENC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_TYPE_DEV_ENC FOR ARTHUS.F_CPTA_TYPE_DEV_ENC;
