-- Synonyme PUBLIC : F_CPTA_LIB_REGLT
-- Cible      : ARTHUS.F_CPTA_LIB_REGLT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_LIB_REGLT FOR ARTHUS.F_CPTA_LIB_REGLT;
