-- Synonyme PUBLIC : F_CPTA_LIB_ECR_DECAISS
-- Cible      : ARTHUS.F_CPTA_LIB_ECR_DECAISS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_LIB_ECR_DECAISS FOR ARTHUS.F_CPTA_LIB_ECR_DECAISS;
