-- Synonyme PUBLIC : F_CPTA_DATE_ENCAISMT_OPERATION
-- Cible      : ARTHUS.F_CPTA_DATE_ENCAISMT_OPERATION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CPTA_DATE_ENCAISMT_OPERATION FOR ARTHUS.F_CPTA_DATE_ENCAISMT_OPERATION;
