-- Synonyme PUBLIC : F_CTRL_MT_FORFAIT
-- Cible      : ARTHUS.F_CTRL_MT_FORFAIT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CTRL_MT_FORFAIT FOR ARTHUS.F_CTRL_MT_FORFAIT;
