-- Synonyme PUBLIC : F_CTRL_DOUBLON_DENT
-- Cible      : ARTHUS.F_CTRL_DOUBLON_DENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CTRL_DOUBLON_DENT FOR ARTHUS.F_CTRL_DOUBLON_DENT;
