-- Synonyme PUBLIC : F_CTRL_REMISE_BANQUE
-- Cible      : ARTHUS.F_CTRL_REMISE_BANQUE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_CTRL_REMISE_BANQUE FOR ARTHUS.F_CTRL_REMISE_BANQUE;
