-- Synonyme PUBLIC : F_DATEFIN_SNTRT_NUMSIN
-- Cible      : ARTHUS.F_DATEFIN_SNTRT_NUMSIN
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_DATEFIN_SNTRT_NUMSIN FOR ARTHUS.F_DATEFIN_SNTRT_NUMSIN;
