-- Synonyme PUBLIC : F_DATE_NAISSANCE
-- Cible      : ARTHUS.F_DATE_NAISSANCE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_DATE_NAISSANCE FOR ARTHUS.F_DATE_NAISSANCE;
