-- Synonyme PUBLIC : F_DCPT_IDADHESION
-- Cible      : ARTHUS.F_DCPT_IDADHESION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_DCPT_IDADHESION FOR ARTHUS.F_DCPT_IDADHESION;
