-- Synonyme PUBLIC : F_DCPT_REMBTOTAL
-- Cible      : ARTHUS.F_DCPT_REMBTOTAL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_DCPT_REMBTOTAL FOR ARTHUS.F_DCPT_REMBTOTAL;
