-- Synonyme PUBLIC : F_DCPTCIE_REMB_D
-- Cible      : ARTHUS.F_DCPTCIE_REMB_D
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_DCPTCIE_REMB_D FOR ARTHUS.F_DCPTCIE_REMB_D;
