-- Synonyme PUBLIC : F_DERNIER_AVIS_DCPT
-- Cible      : ARTHUS.F_DERNIER_AVIS_DCPT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_DERNIER_AVIS_DCPT FOR ARTHUS.F_DERNIER_AVIS_DCPT;
