-- Synonyme PUBLIC : F_DOMICILE_FISCAL
-- Cible      : ARTHUS.F_DOMICILE_FISCAL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_DOMICILE_FISCAL FOR ARTHUS.F_DOMICILE_FISCAL;
