-- Synonyme PUBLIC : F_DUPLIQUE_DOSSIER_SANTE
-- Cible      : ARTHUS.F_DUPLIQUE_DOSSIER_SANTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_DUPLIQUE_DOSSIER_SANTE FOR ARTHUS.F_DUPLIQUE_DOSSIER_SANTE;
