-- Synonyme PUBLIC : F_ETAT_INSTANCE_UNIQUE
-- Cible      : ARTHUS.F_ETAT_INSTANCE_UNIQUE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_ETAT_INSTANCE_UNIQUE FOR ARTHUS.F_ETAT_INSTANCE_UNIQUE;
