-- Synonyme PUBLIC : F_ETAT_SNTRT_BY_DATE
-- Cible      : ARTHUS.F_ETAT_SNTRT_BY_DATE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_ETAT_SNTRT_BY_DATE FOR ARTHUS.F_ETAT_SNTRT_BY_DATE;
