-- Synonyme PUBLIC : F_ETAT_SNTR_PREV
-- Cible      : ARTHUS.F_ETAT_SNTR_PREV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_ETAT_SNTR_PREV FOR ARTHUS.F_ETAT_SNTR_PREV;
