-- Synonyme PUBLIC : F_ETAT_DOSSIER_SANTE
-- Cible      : ARTHUS.F_ETAT_DOSSIER_SANTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_ETAT_DOSSIER_SANTE FOR ARTHUS.F_ETAT_DOSSIER_SANTE;
