-- Synonyme PUBLIC : F_EXIST_ADHE_PORTE
-- Cible      : ARTHUS.F_EXIST_ADHE_PORTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_EXIST_ADHE_PORTE FOR ARTHUS.F_EXIST_ADHE_PORTE;
