-- Synonyme PUBLIC : F_EXISTE_VARIABLE
-- Cible      : ARTHUS.F_EXISTE_VARIABLE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_EXISTE_VARIABLE FOR ARTHUS.F_EXISTE_VARIABLE;
