-- Synonyme PUBLIC : F_EXIST_PARAM_MSG
-- Cible      : ARTHUS.F_EXIST_PARAM_MSG
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_EXIST_PARAM_MSG FOR ARTHUS.F_EXIST_PARAM_MSG;
