-- Synonyme PUBLIC : F_EXISTE_BENE_FISC
-- Cible      : ARTHUS.F_EXISTE_BENE_FISC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_EXISTE_BENE_FISC FOR ARTHUS.F_EXISTE_BENE_FISC;
