-- Synonyme PUBLIC : F_FIND_BASE_QTTC
-- Cible      : ARTHUS.F_FIND_BASE_QTTC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_FIND_BASE_QTTC FOR ARTHUS.F_FIND_BASE_QTTC;
