-- Synonyme PUBLIC : F_FIND_STATUT_CNTRT
-- Cible      : ARTHUS.F_FIND_STATUT_CNTRT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_FIND_STATUT_CNTRT FOR ARTHUS.F_FIND_STATUT_CNTRT;
