-- Synonyme PUBLIC : F_GET_VALUE_IN_TABLE
-- Cible      : ARTHUS.F_GET_VALUE_IN_TABLE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_GET_VALUE_IN_TABLE FOR ARTHUS.F_GET_VALUE_IN_TABLE;
