-- Synonyme PUBLIC : F_GET_VARCHAR_SPLITED
-- Cible      : ARTHUS.F_GET_VARCHAR_SPLITED
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_GET_VARCHAR_SPLITED FOR ARTHUS.F_GET_VARCHAR_SPLITED;
