-- Synonyme PUBLIC : F_GET_TRANSCO_SP
-- Cible      : ARTHUS.F_GET_TRANSCO_SP
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_GET_TRANSCO_SP FOR ARTHUS.F_GET_TRANSCO_SP;
