-- Synonyme PUBLIC : F_IDHISTO_RAPPEL
-- Cible      : ARTHUS.F_IDHISTO_RAPPEL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_IDHISTO_RAPPEL FOR ARTHUS.F_IDHISTO_RAPPEL;
