-- Synonyme PUBLIC : F_IDADHESION_GAR
-- Cible      : ARTHUS.F_IDADHESION_GAR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_IDADHESION_GAR FOR ARTHUS.F_IDADHESION_GAR;
