-- Synonyme PUBLIC : F_IDTEXTE_DCPT_2
-- Cible      : ARTHUS.F_IDTEXTE_DCPT_2
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_IDTEXTE_DCPT_2 FOR ARTHUS.F_IDTEXTE_DCPT_2;
