-- Synonyme PUBLIC : F_IDADHESION_PREV
-- Cible      : ARTHUS.F_IDADHESION_PREV
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_IDADHESION_PREV FOR ARTHUS.F_IDADHESION_PREV;
