-- Synonyme PUBLIC : F_IDADHESION_CONTRAT
-- Cible      : ARTHUS.F_IDADHESION_CONTRAT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_IDADHESION_CONTRAT FOR ARTHUS.F_IDADHESION_CONTRAT;
