-- Synonyme PUBLIC : F_IDADHESION_DCPT_SANTE
-- Cible      : ARTHUS.F_IDADHESION_DCPT_SANTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_IDADHESION_DCPT_SANTE FOR ARTHUS.F_IDADHESION_DCPT_SANTE;
