-- Synonyme PUBLIC : F_INFO_TIERS_PAYANT
-- Cible      : ARTHUS.F_INFO_TIERS_PAYANT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_INFO_TIERS_PAYANT FOR ARTHUS.F_INFO_TIERS_PAYANT;
