-- Synonyme PUBLIC : F_INSERT_HISTO_CNX_USERS
-- Cible      : ARTHUS.F_INSERT_HISTO_CNX_USERS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_INSERT_HISTO_CNX_USERS FOR ARTHUS.F_INSERT_HISTO_CNX_USERS;
