-- Synonyme PUBLIC : F_IS_ONE_LIEN_GED_OK
-- Cible      : ARTHUS.F_IS_ONE_LIEN_GED_OK
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_IS_ONE_LIEN_GED_OK FOR ARTHUS.F_IS_ONE_LIEN_GED_OK;
