-- Synonyme PUBLIC : F_IS_ALL_LIEN_GED_CHECKED
-- Cible      : ARTHUS.F_IS_ALL_LIEN_GED_CHECKED
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_IS_ALL_LIEN_GED_CHECKED FOR ARTHUS.F_IS_ALL_LIEN_GED_CHECKED;
