-- Synonyme PUBLIC : F_LIBELLE_FORMAT
-- Cible      : ARTHUS.F_LIBELLE_FORMAT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_LIBELLE_FORMAT FOR ARTHUS.F_LIBELLE_FORMAT;
