-- Synonyme PUBLIC : F_MONTANT_SOUMIS
-- Cible      : ARTHUS.F_MONTANT_SOUMIS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_MONTANT_SOUMIS FOR ARTHUS.F_MONTANT_SOUMIS;
