-- Synonyme PUBLIC : F_MT_AFFEC_TFC_NUMQUIT_D
-- Cible      : ARTHUS.F_MT_AFFEC_TFC_NUMQUIT_D
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_MT_AFFEC_TFC_NUMQUIT_D FOR ARTHUS.F_MT_AFFEC_TFC_NUMQUIT_D;
