-- Synonyme PUBLIC : F_NB_TELETRANSMIS
-- Cible      : ARTHUS.F_NB_TELETRANSMIS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_NB_TELETRANSMIS FOR ARTHUS.F_NB_TELETRANSMIS;
