-- Synonyme PUBLIC : F_NUM_IDADHESION
-- Cible      : ARTHUS.F_NUM_IDADHESION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_NUM_IDADHESION FOR ARTHUS.F_NUM_IDADHESION;
