-- Synonyme PUBLIC : F_NUMBORD_DECAISMT
-- Cible      : ARTHUS.F_NUMBORD_DECAISMT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_NUMBORD_DECAISMT FOR ARTHUS.F_NUMBORD_DECAISMT;
