-- Synonyme PUBLIC : F_NUMORG_PRESCRIPTION
-- Cible      : ARTHUS.F_NUMORG_PRESCRIPTION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_NUMORG_PRESCRIPTION FOR ARTHUS.F_NUMORG_PRESCRIPTION;
