-- Synonyme PUBLIC : F_NUMASSU_NOEMIE
-- Cible      : ARTHUS.F_NUMASSU_NOEMIE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_NUMASSU_NOEMIE FOR ARTHUS.F_NUMASSU_NOEMIE;
