-- Synonyme PUBLIC : F_PARAM_OPE_VALIDE
-- Cible      : ARTHUS.F_PARAM_OPE_VALIDE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_PARAM_OPE_VALIDE FOR ARTHUS.F_PARAM_OPE_VALIDE;
