-- Synonyme PUBLIC : F_PERS_IRREVOCABLE
-- Cible      : ARTHUS.F_PERS_IRREVOCABLE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_PERS_IRREVOCABLE FOR ARTHUS.F_PERS_IRREVOCABLE;
