-- Synonyme PUBLIC : F_PORTE_IDENTIFIANT
-- Cible      : ARTHUS.F_PORTE_IDENTIFIANT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_PORTE_IDENTIFIANT FOR ARTHUS.F_PORTE_IDENTIFIANT;
