-- Synonyme PUBLIC : F_PORTE_EMETTEUR
-- Cible      : ARTHUS.F_PORTE_EMETTEUR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_PORTE_EMETTEUR FOR ARTHUS.F_PORTE_EMETTEUR;
