-- Synonyme PUBLIC : F_PRCH_IDADHESION
-- Cible      : ARTHUS.F_PRCH_IDADHESION
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_PRCH_IDADHESION FOR ARTHUS.F_PRCH_IDADHESION;
