-- Synonyme PUBLIC : F_PRESTA_ORIGINE
-- Cible      : ARTHUS.F_PRESTA_ORIGINE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_PRESTA_ORIGINE FOR ARTHUS.F_PRESTA_ORIGINE;
