-- Synonyme PUBLIC : F_REF_PRELEVEMENT
-- Cible      : ARTHUS.F_REF_PRELEVEMENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_REF_PRELEVEMENT FOR ARTHUS.F_REF_PRELEVEMENT;
