-- Synonyme PUBLIC : F_REFEXT_FACTURE
-- Cible      : ARTHUS.F_REFEXT_FACTURE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_REFEXT_FACTURE FOR ARTHUS.F_REFEXT_FACTURE;
