-- Synonyme PUBLIC : F_REMPLACE_TEXTE
-- Cible      : ARTHUS.F_REMPLACE_TEXTE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_REMPLACE_TEXTE FOR ARTHUS.F_REMPLACE_TEXTE;
