-- Synonyme PUBLIC : F_SEL_DATE_RESIL
-- Cible      : ARTHUS.F_SEL_DATE_RESIL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_SEL_DATE_RESIL FOR ARTHUS.F_SEL_DATE_RESIL;
