-- Synonyme PUBLIC : F_SEL_INTERLOCUTEUR
-- Cible      : ARTHUS.F_SEL_INTERLOCUTEUR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_SEL_INTERLOCUTEUR FOR ARTHUS.F_SEL_INTERLOCUTEUR;
