-- Synonyme PUBLIC : F_SEL_INTERLOC_PARAM_OU_DEFAUT
-- Cible      : ARTHUS.F_SEL_INTERLOC_PARAM_OU_DEFAUT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_SEL_INTERLOC_PARAM_OU_DEFAUT FOR ARTHUS.F_SEL_INTERLOC_PARAM_OU_DEFAUT;
