-- Synonyme PUBLIC : F_SEL_PARPORTE_IDENT
-- Cible      : ARTHUS.F_SEL_PARPORTE_IDENT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_SEL_PARPORTE_IDENT FOR ARTHUS.F_SEL_PARPORTE_IDENT;
