-- Synonyme PUBLIC : F_SEL_NUMORG_LIG_DOSS
-- Cible      : ARTHUS.F_SEL_NUMORG_LIG_DOSS
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_SEL_NUMORG_LIG_DOSS FOR ARTHUS.F_SEL_NUMORG_LIG_DOSS;
