-- Synonyme PUBLIC : F_SNTR_PREV_DEBUT
-- Cible      : ARTHUS.F_SNTR_PREV_DEBUT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_SNTR_PREV_DEBUT FOR ARTHUS.F_SNTR_PREV_DEBUT;
