-- Synonyme PUBLIC : F_SUIVI_FACTPE_PREC
-- Cible      : ARTHUS.F_SUIVI_FACTPE_PREC
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_SUIVI_FACTPE_PREC FOR ARTHUS.F_SUIVI_FACTPE_PREC;
