-- Synonyme PUBLIC : F_TERME_A_ECHOIR
-- Cible      : ARTHUS.F_TERME_A_ECHOIR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_TERME_A_ECHOIR FOR ARTHUS.F_TERME_A_ECHOIR;
