-- Synonyme PUBLIC : F_TEST_POUR_SPPRIMER_CORRES
-- Cible      : ARTHUS.F_TEST_POUR_SPPRIMER_CORRES
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_TEST_POUR_SPPRIMER_CORRES FOR ARTHUS.F_TEST_POUR_SPPRIMER_CORRES;
