-- Synonyme PUBLIC : F_TEXTE_VARIABLE
-- Cible      : ARTHUS.F_TEXTE_VARIABLE
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_TEXTE_VARIABLE FOR ARTHUS.F_TEXTE_VARIABLE;
