-- Synonyme PUBLIC : F_TOTQTTC_IND_OUT
-- Cible      : ARTHUS.F_TOTQTTC_IND_OUT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_TOTQTTC_IND_OUT FOR ARTHUS.F_TOTQTTC_IND_OUT;
