-- Synonyme PUBLIC : F_TOTQTTC_IN_OUT
-- Cible      : ARTHUS.F_TOTQTTC_IN_OUT
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_TOTQTTC_IN_OUT FOR ARTHUS.F_TOTQTTC_IN_OUT;
