-- Synonyme PUBLIC : F_TOTFRAIS_GAR_D
-- Cible      : ARTHUS.F_TOTFRAIS_GAR_D
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_TOTFRAIS_GAR_D FOR ARTHUS.F_TOTFRAIS_GAR_D;
