-- Synonyme PUBLIC : F_TOTAL_IDCALCUL
-- Cible      : ARTHUS.F_TOTAL_IDCALCUL
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_TOTAL_IDCALCUL FOR ARTHUS.F_TOTAL_IDCALCUL;
