-- Synonyme PUBLIC : F_TYPE_RATTACH_COUR
-- Cible      : ARTHUS.F_TYPE_RATTACH_COUR
-- Source     : export ALL_SYNONYMS (2026-08-12 11:04)

CREATE PUBLIC SYNONYM F_TYPE_RATTACH_COUR FOR ARTHUS.F_TYPE_RATTACH_COUR;
