# Environnement : local (avec db sur docker)
oracle:
  jdbc:
    host: localhost
    port: 1521
    service: GEREP19CL

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/GEREP19CL
    username: system
    password: ENC(VciztaPiWbe5z+IyVX85EeX1ZKZ3lTq29ID4eii9JDP1z7GpabOwC4OyukVgRIPeC4msRP2SUfcA6U0hqH/n4Q==)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        default_schema: ARTHUS
        synonyms: true
  liquibase:
    enabled: true
    url: jdbc:oracle:thin:@//localhost:1521/GEREP19CL?internal_logon=sysdba
    user: sys
    password: ENC(VciztaPiWbe5z+IyVX85EeX1ZKZ3lTq29ID4eii9JDP1z7GpabOwC4OyukVgRIPeC4msRP2SUfcA6U0hqH/n4Q==)